### PR TITLE
fix: assume router_flavor to default value according to kong version if missing

### LINKED ISSUE #4068: Assume traditional router when `router_flavor` is missing
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

#3935 introduced a check for `router_flavor` in Admin API config: https://github.com/Kong/kubernetes-ingress-controller/blob/ed051792ae2f2e6db2dfc3946f0416aa6abd1e45/internal/manager/utils/kongconfig/root.go#L49-L52

This check returns an error when this key is missing: https://github.com/Kong/kubernetes-ingress-controller/blob/ed051792ae2f2e6db2dfc3946f0416aa6abd1e45/internal/manager/utils/kongconfig/root.go#L106.

This means that Gateway versions which do not include said config field are breaking the KIC <-> Gateway integration.

We're OK in terms of compatibility because https://docs.konghq.com/kubernetes-ingress-controller/latest/references/version-compatibility/ states that KIC 2.7 and above is compatible with GW 3.0+ but we could improve this by assuming we work with `traditional` router when that field is missing.

Related issue: https://github.com/Kong/kubernetes-ingress-controller/issues/4062

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Kong Ingress Controller version

_No response_

### Kubernetes version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

Kong with version below 3.0 (2.8.x) does not have `router_flavor` field in configurations. We need to treat them as using `traditional` router flavor, instead of raising an error, because they can only use the traditional router. This PR returns the default `traditional` router flavor if Kong version is below 3.0. 

**Which issue this PR fixes**:

fixes #4068 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/manager/utils/kongconfig/root.go [hunk 1]
```diff
@@ -103,13 +110,16 @@ func RouterFlavorFromRoot(r Root) (string, error) {
 	const routerFlavorKey = "router_flavor"
 	routerFlavor, exist := rootConfig[routerFlavorKey]
 	if !exist {
-		return "", fmt.Errorf("no value in root configuration for key %q", routerFlavorKey)
+		if kongVersion.Major() < expressionRouterMinimalMajorVersion {
+			return kongRouterFlavorTraditional, nil
+		}
+		return kongRouterFlavorTraditionalCompatible, nil
```
Comment (pmalek) [inline internal/manager/utils/kongconfig/root.go:116]: As discussed on slack: since Gateway 3.0 and above should have this field, I believe this is a good place to return an error. Otherwise, return `kongRouterFlavorTraditional`

```suggestion
		if kongVersion.Major() < expressionRouterMinimalMajorVersion {
			return kongRouterFlavorTraditional, nil
		}
		return "", fmt.Errorf("%q field missing from Gateway's configuration root for version: %s", routerFlavorKey, kongVersion)
```

Comment (pmalek) [reply internal/manager/utils/kongconfig/root.go:116]: If we do the above then changelog would also need to be updated.

Comment (randmonkey) [reply internal/manager/utils/kongconfig/root.go]: updated, and also for CHANGELOG.

File: CHANGELOG.md [hunk 2]
```diff
@@ -84,10 +84,14 @@ Adding a new version? You'll need three changes:
 - Added translator to translate ingresses under `networking.k8s.io/v1` to
   expression based Kong routes. The translator is enabled when feature gate
   `ExpressionRoutes` is turned on and the managed Kong gateway runs in router
-  flavor `expressions`.
+  flavor `expressions`. If `router_flavor` is not given in Kong root 
+  configurations, we assume kong is running with the default router mode 
+  according to its version: `traditional` for versions below 3.0 (2.8 and older);
+  abort with an error for versions over 3.0 (3.0 and newer).
```
Comment (pmalek) [inline CHANGELOG.md:90]:
```suggestion
  flavor `expressions`. We assume `router_flavor` to be `traditional`
  for versions below 3.0. If it is not available in Kong's configuration,
  for versions 3.0 and above, abort with an error .
```

File: internal/manager/utils/kongconfig/root.go [hunk 3]
```diff
@@ -16,6 +16,13 @@ import (
 	"github.com/kong/kubernetes-ingress-controller/v2/internal/adminapi"
 )
 
+const (
+	kongRouterFlavorTraditional           = "traditional"
+	kongRouterFlavorTraditionalCompatible = "traditional_compatible"
```
Comment (pmalek) [inline internal/manager/utils/kongconfig/root.go:21]: Unused?

```suggestion
```

Comment (randmonkey) [reply internal/manager/utils/kongconfig/root.go]: deleted.

File: CHANGELOG.md (hunk 2 above)
Comment (randmonkey) [reply CHANGELOG.md]: done.

**Review by pmalek — APPROVED** [review]

**Review by czeslavo — APPROVED** [review]
