### PR TITLE
fix(KongService) only send PATCH request for services when necessary

### LINKED ISSUE #104: Updates kong services on each synchronization check when not necessary
### Summary

The ingress controller is issuing a `PATCH` to Kong for each service in the environment on each synchronization check. This doesn't necessarily sound bad, but when you have 200+ services and they all issue a `PATCH` at the same time, you get contention on the database that can manifest as errors in the kong-proxy logs and 5XX errors for consumers.

**Kong Ingress controller version**
0.1.0

### Kubernetes version

1.9.3

### What happened
Users experience service outages using kong-ingress with a large number of services due to unnecessary database writes every 10 minutes.

### Expected behvaior
Services in k8s with no changes needed in Kong should detect that no change is necessary and avoid sending a `PATCH`, similar to how plugins function.

### PR DESCRIPTION
**Pull request by fffonion**
**What this PR does / why we need it**: only send PATCH request to Kong when the kongIngress changed, this will solve a problem that may result in high database pressure in Kong.

**Which issue this PR fixes** : fixes #104

### CODE REVIEW

File: internal/ingress/controller/kong.go [hunk 1]
```diff
@@ -247,7 +247,12 @@ func (n *NGINXController) syncServices(ingressCfg *ingress.Configuration) (bool,
 				}
 
 				if s != nil {
+					// if kongIngress object does not exist, don't create the service in Kong
+					outOfSync := false
 					if kongIngress != nil && kongIngress.Proxy != nil {
+						// check if we need to patch KongService later
+						outOfSync = !reflect.DeepEqual(s, kongIngress.Proxy)
```
Comment (hbagdi) [inline internal/ingress/controller/kong.go]: The comparison seems flawed. Have you tested this?
`kongadminv1.Service` and `Proxy` are two different objects with `Service` containing fields which are not present in `Proxy` struct.

It will be better to write a separate method comparing the two objects field by field.
Also, think about cases where, the fields are populated in `s` but not `in `kongIngress.Proxy`, which results in a `PATCH` when not needed.

Some helpful context here: `kongIngress.Proxy` is used to override properties defined in `s` only.  If fields are absent in `kongIngress.Proxy`, then the value in `s` take precedence.

File: internal/ingress/controller/kong.go [hunk 2]
```diff
@@ -269,8 +274,9 @@ func (n *NGINXController) syncServices(ingressCfg *ingress.Configuration) (bool,
 							s.WriteTimeout = kongIngress.Proxy.WriteTimeout
 						}
 
-						if kongIngress.Proxy.Retries > 0 {
+						if kongIngress.Proxy.Retries > 0 && s.Retries != kongIngress.Proxy.Retries {
```
Comment (hbagdi) [inline internal/ingress/controller/kong.go]: If a kongIngress object sets up ReadTimeout (or any timeout for that matter) as 100000, then this logic will not update the corresponding service object in Kong, right?

Comment (fffonion) [reply internal/ingress/controller/kong.go]: Nice catch! I've added the comparison for `ConnectTime` as well.
