### PR TITLE
Integration test fixes

### LINKED ISSUE #1432: CI Flakes
Investigate recent CI flakes that appear to manifest themselves in integration tests during TCPIngress or UDPIngress tests by triggering a test timeout.

### LINKED ISSUE #1444: KIC 2.0 Integration Tests - Expanded cleanup and cleanup validation
This is a reminder to do some refactoring and expansion of our integration tests for KIC 2.0, to help keep CI running smoothly as complexity has been growing a lot recently in our tests.

### PR DESCRIPTION
**Pull request by shaneutt**
**What this PR does / why we need it**:

This fixes several flakes and provides some general cleanup for our integration tests.

**Which issue this PR fixes**

fixes #1432
fixes #1444

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: railgun/test/integration/suite_test.go [hunk 1]
```diff
@@ -75,7 +75,7 @@ var (
 	cluster ktfkind.Cluster
 
 	// watchNamespaces is a list of namespaces the controller watches
-	watchNamespaces = strings.Join([]string{elsewhere, corev1.NamespaceDefault}, ",")
+	watchNamespaces = strings.Join([]string{elsewhere, corev1.NamespaceDefault, "tcpingress"}, ",")
```
Comment (rainest) [inline railgun/test/integration/suite_test.go:78]: Since this gets used in both the suite and TCPIngress test, it should be moved to a constant (similar to `elsewhere`) to avoid an inadvertent change making them out of sync.

**Review by rainest — APPROVED** [review]
One minor change to declare a constant for the new namespace, but otherwise looks good.

File: railgun/test/integration/suite_test.go (hunk 1 above)
Comment (shaneutt) [reply railgun/test/integration/suite_test.go:78]: sure :+1:

Comment (shaneutt) [reply railgun/test/integration/suite_test.go]: Sounds good, taken care of in e4f606c0bf3a529837fc25e507b81f05538cfc7d

File: pkg/util/debug_logging.go [hunk 2]
```diff
@@ -43,11 +44,15 @@ func MakeDebugLoggerWithReducedRedudancy(writer io.Writer, formatter logrus.Form
 	// setup the logger with debug level logging
 	log := logrus.New()
 	log.Level = logrus.DebugLevel
-	log.Formatter = formatter
+
+	// setup the nilFormatter to allow stifling log entries
+	nilFormatter := newNilFormatter(formatter)
+	log.Formatter = nilFormatter
```
Comment (ccfishk) [inline pkg/util/debug_logging.go:50]: My Suggestion here is develop a test case for the log mechanism that specifically resolve the "Data Race" of the default log mechanism.

File: railgun/test/integration/suite_test.go (hunk 1 above)
Comment (rainest) [reply railgun/test/integration/suite_test.go]: My bad, I shouldn't just say "this". To reword, the `watchNamespaces` string is fine, but it should be composed of constant namespace names, and tests should also use those names. So something like:

A constant declaration of `tcpIngressNamespace = "tcpingress"` like https://github.com/Kong/kubernetes-ingress-controller/blob/2f2a85707e785049e3f4c82750130a0dc9d4cb6e/railgun/test/integration/suite_test.go#L56-L57

```
watchNamespaces = strings.Join([]string{elsewhere, tcpIngressNamespace, corev1.NamespaceDefault}, ",")
```

And in tcpingress_test.go, `namespace := tcpIngressNamespace`

Comment (shaneutt) [reply railgun/test/integration/suite_test.go]: Sure no worries, 0e94e619f8b367f0405d7be279e5f04f7b672e47 is the new patch for this :+1:

File: pkg/util/debug_logging.go (hunk 2 above)
Comment (shaneutt) [reply pkg/util/debug_logging.go:50]: Sounds good, added in 9c0d1fb3d43cf0aa942900daa92f5ead808909a3
