### PR TITLE
fix: make status queue not block when no sub exists

### LINKED ISSUE #4260: HTTPRoute: Endless blocking issue due to absence of logic for receiving from channels
### Is there an existing issue for this?

- [X] I have searched the existing issues

I've already reported this issue in kong repo, but it doesn't seem to be getting tracked. 
https://github.com/Kong/kong/issues/10923

I might have reported it in the wrong repo, so I've created it here as well

### Current Behavior

PATCH commit: https://github.com/parkjeongryul/kubernetes-ingress-controller/commit/e0d7145dc99d93810f7d738482a05af83e68137b

There is `kubernetesObjectStatusQueue`. (which size is 8192)

But there is only a PUBLISHER(send to chan) for that queue and no SUBSCRIBERS(receieve from chan)... 
(And why do we need this queue?) 

So it seems that after a certain GKV's 8192 event (creation or deletion), the kong ingress controller is forever broken.

### Expected Behavior

The reconcile function of HTTPRoute must always operate correctly.

### Steps To Reproduce

```markdown
This is our destroy-kong.sh
The behavior is reproduced near the end of the script.


user@AL01974378 vks % cat destroy-kong.sh 
#!/bin/bash

# Function to create and delete HttpRoute
create_and_delete_httproute() {
  for j in {1..100}
  do
    # Define HttpRoute, Service, and Deployment YAML content as a bash variable.
    RESOURCES_YAML=$(cat <<EOF
apiVersion: v1
kind: Namespace
metadata:
  name: echo-ns-$1
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: echo-tmp-$1
  namespace: echo-ns-$1
  annotations:
    konghq.com/strip-path: 'true'
spec:
  parentRefs:
  - name: clous-api
    namespace: clous-api
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /echo-tmp-$1
    backendRefs:
    - name: echo
      kind: Service
      port: 1027
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo
  name: echo
  namespace: echo-ns-$1
spec:
  ports:
  - port: 1025
    name: tcp
    protocol: TCP
    targetPort: 1025
  - port: 1026
    name: udp
    protocol: TCP
    targetPort: 1026
  - port: 1027
    name: http
    protocol: TCP
    targetPort: 1027
  selector:
    app: echo
EOF
    )

    # Create HttpRoute, Service, and Deployment
    echo "Creating resources in echo-ns-$1... $j steps"
    echo "${RESOURCES_YAML}" | kubectl apply -f -

    # Delete Namespace
    echo "Deleting namespace echo-ns-$1... $j steps"
    kubectl delete ns echo-ns-$1
  done
}

# Start 40 parallel tasks to create and delete HttpRoutes, Services, and Deployments
for i in {1..40}
do
  create_and_delete_httproute $i &
done

# Wait for all
wait
```

### Kong Ingress Controller version

```shell
v2.9.2
```

### Kubernetes version

```shell
v1.23.15
```

### Anything else?

### PR DESCRIPTION
**Pull request by czeslavo**
**What this PR does / why we need it**:

Fixes the `status.Queue` so that it does not block on `Publish` when no `Subscribe` was called before, adds missing subscriptions for Gateway API *Routes and covers the regression with tests. Also adds `--update-status-queue-buffer-size` to allow reproduction.

**Which issue this PR fixes**:

Fixes #4260.

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Review by randmonkey — COMMENTED** [review]
Seems that the PR did not add the status queue to `TLSRoute`?

File: internal/util/kubernetes/object/status/queue_test.go [hunk 1]
```diff
@@ -133,3 +133,78 @@ var (
...
+			publishedAt = time.Now()
+			close(publishDone)
+		}()
+
+		// Give some time for Publish to block.
+		time.Sleep(10 * time.Millisecond)
+
+		// Consume one event to unblock Publish.
+		consumedEventAt := time.Now()
+		<-sub
```
Comment (pmalek) [inline internal/util/kubernetes/object/status/queue_test.go:202]: Wouldn't this be equivalent without the sleep

```suggestion
		// Consume one event to unblock Publish.
		<-sub
		consumedEventAt := time.Now()
```

File: test/envtest/adminapimock.go [hunk 2]
```diff
@@ -1,40 +1,64 @@
...
 
+const dblessConfig = `{
+	"version": "3.3.0",
+	"configuration": {
+		"database": "off",
+		"router_flavor": "traditional",
+		"role": "traditional",
+		"proxy_listeners": [
+			{
+				"backlog=%d+": false,
```
Comment (pmalek) [inline test/envtest/adminapimock.go:18]: Is this expected to contain the format strings ? 🤔

File: test/envtest/adminapimock.go [hunk 3]
```diff
@@ -1,40 +1,64 @@
...
+				"ipv6only=on": false,
+				"ipv6only=off": false,
+				"ssl": false,
+				"so_keepalive=off": false,
+				"so_keepalive=%w*:%w*:%d*": false,
```
Comment (pmalek) [inline test/envtest/adminapimock.go:23]: Ditto here

File: test/envtest/controller.go [hunk 4]
```diff
@@ -58,3 +60,11 @@ func StartReconcilers(ctx context.Context, t *testing.T, scheme *runtime.Scheme,
 		}
 	})
 }
+
+func NewControllerClient(t *testing.T, cfg *rest.Config) ctrlclient.Client {
```
Comment (pmalek) [inline test/envtest/controller.go:64]:
```suggestion
// NewControllerClient returns a new controller-runtime Client for provided rest.Config.
func NewControllerClient(t *testing.T, cfg *rest.Config) ctrlclient.Client {
```

File: test/envtest/k8s_objects_status_envtest_test.go [hunk 5]
```diff
@@ -0,0 +1,198 @@
...
+
+	modifyCfgFn(&cfg)
+
+	go func() {
+		err := manager.Run(ctx, &cfg, util.ConfigDumpDiagnostic{}, logrus.New())
+		require.NoError(t, err)
+	}()
+}
+
+const publishSvcName = "publish-svc"
```
Comment (pmalek) [inline test/envtest/k8s_objects_status_envtest_test.go:139]: Only used above, could potentially be moved inside the closure above?

**Comment by czeslavo** [comment]
> Seems that the PR did not add the status queue to `TLSRoute`?

Good catch, thanks.

File: test/envtest/setup.go [hunk 6]
```diff
@@ -80,5 +80,9 @@ func Setup(t *testing.T, scheme *runtime.Scheme) *rest.Config {
 		wg.Wait()
 	})
 
+	// Set the env vars that the controller expects (not using t.Setenv because envtests are run in parallel).
+	_ = os.Setenv("POD_NAMESPACE", "default")            //nolint:tenv
+	_ = os.Setenv("POD_NAME", "kong-ingress-controller") //nolint:tenv
```
Comment (pmalek) [inline test/envtest/setup.go:85]: 🤔 I'm not sure about this. This way all the tests that are run will receive this and it will never be cleaned. This might potentially be problematic.

Do we need this or is it a nice to have to prevent warning logs?

File: test/envtest/k8s_objects_status_envtest_test.go [hunk 7]
```diff
@@ -0,0 +1,198 @@
...
+					Name: gatewayv1beta1.ObjectName(gw.Name),
+				}},
+			},
+			Rules: []gatewayv1beta1.HTTPRouteRule{{
+				Matches: []gatewayv1beta1.HTTPRouteMatch{{
+					Path: &gatewayv1beta1.HTTPPathMatch{
+						Type:  lo.ToPtr(gatewayv1beta1.PathMatchPathPrefix),
+						Value: lo.ToPtr("/path"),
+					},
+				}},
```
Comment (pmalek) [inline test/envtest/k8s_objects_status_envtest_test.go:82]: You could also use builder for this: https://github.com/Kong/kubernetes-ingress-controller/blob/5f7eca1bbca498837e99def024307a6b762c9f75/internal/util/builder/httproutematch.go

File: internal/util/kubernetes/object/status/queue_test.go (hunk 1 above)
Comment (czeslavo) [reply internal/util/kubernetes/object/status/queue_test.go]: Unfortunately not, this would be flaky (`publishedAt` assignment can happen before `consumedEventAt`) - proved it by running the test with `-count=100000`. 

I changed the test logic to not rely on time - instead, I just verify that the publish goroutine doesn't return immediately and that after we consume one event and the goroutine returns, the channel gets full again: eea6f04

File: test/envtest/setup.go (hunk 6 above)
Comment (czeslavo) [reply test/envtest/setup.go:85]: Yeah, I wanted to get rid of the noisy logs. How about doing it this way: https://github.com/Kong/kubernetes-ingress-controller/pull/4277 then?

File: test/envtest/k8s_objects_status_envtest_test.go (hunk 5 above)
Comment (czeslavo) [reply test/envtest/k8s_objects_status_envtest_test.go]: Actually, it should be used twice - I made a mistake and hardcoded it in the `deployGateway` function's publish service definition: c87f956

File: test/envtest/k8s_objects_status_envtest_test.go (hunk 7 above)
Comment (czeslavo) [reply test/envtest/k8s_objects_status_envtest_test.go]: 👍 eecb107

File: test/envtest/adminapimock.go (hunk 2 above)
Comment (czeslavo) [reply test/envtest/adminapimock.go:18]: Yup, that's taken directly straight from Kong root response. Here are go-kong's API mappings for it https://github.com/Kong/go-kong/blob/c7d04455bcfbe36b655972e232b5e402144ab7cb/kong/listeners.go#L16C2-L16C2.

File: test/envtest/adminapimock.go (hunk 3 above)
Comment (czeslavo) [reply test/envtest/adminapimock.go:23]: Ditto 🙂

File: test/envtest/controller.go (hunk 4 above)
Comment (czeslavo) [reply test/envtest/controller.go:65]: afb78f9

File: test/envtest/adminapimock.go (hunk 3 above)
Comment (pmalek) [reply test/envtest/adminapimock.go:23]: 🤔 ok then

File: internal/util/kubernetes/object/status/queue_test.go [hunk 8]
```diff
@@ -133,3 +134,75 @@ var (
...
+			q.Publish(testObj)
+			close(published)
+		}()
+
+		select {
+		case <-published:
+			t.Fatal("the Publish goroutine should be blocked")
+		case <-sub:
+			// Consume one event from the channel to unblock the Publish goroutine.
+		}
```
Comment (pmalek) [inline internal/util/kubernetes/object/status/queue_test.go:203]: Nice!

File: internal/util/kubernetes/object/status/queue_test.go [hunk 9]
```diff
@@ -133,3 +134,75 @@ var (
...
+
+		<-published
```
[the remark this answers is not in the document]
Comment (czeslavo) [reply internal/util/kubernetes/object/status/queue_test.go]: Makes sense: b9ec876

**Review by pmalek — APPROVED** [review]
