### PR TITLE
fix(admission): ignore unsupported credential types in validating secrets

### LINKED ISSUE #7218: KIC webhook rejects `konghq.com/credential: konnect` Secrets
## Current Behavior

When KGO is used to manage a GW API Gateway and Konnect CP entities at the same time, and the user wants to configure `KonnectAPIAuthConfiguration` by passing a `secretRef` instead of directly setting `token`, KIC's validating webhook deployed by KGO will reject such a secret as it has a `konghq.com/credential` label with an unexpected by KIC `konnect` value.

From the report:

> The use case is that I am planning to migrate from KIC/KONG deployment model to the operator model. Since the operator can also manage Konnect CP, I was thinking to use the operator to
>1. Manage KIC/Kong deployment
>2. Manage Konnect CPs
>
> To achieve 2, I need KonnectAPIAuthConfiguration which takes secretRef  for token storage. The secret that contains the actual token requires  [konghq.com/credential](http://konghq.com/credential): konnect  label, otherwise we see errors like below
>
>  "error": "secret kong-system/konnect-token does not have label konghq.com/credential: konnect",
>
> However, KIC rejects secrets that has this label and gives me below error
> 
>for: "KonnectAuth.yaml": error when patching "KonnectAuth.yaml": admission webhook "secrets.credentials.validation.ingress-controller.konghq.com" denied the request: consumer credential failed validation: invalid credential type konnect
>
>I was wondering if we can configure kic to ignore secrets with this label as it will only be used by the operator

## Expected Behavior

KIC validating webhook should ignore secrets with `konghq.com/credential: konnect` labels.

## Steps To Reproduce

1. Deploy a GW API Gateway, wait for it to be operational.
2. Apply a secret labeled `konghq.com/credential: konnect` and see the webhook rejecting it.

## Operator Version

1.4

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

Ignore secrets with unsupported credential type in `konghq.com/credential` label like `konnect` in validating webhooks. This prevents rejection of `Secret`s used for credentials used in other places.

To keep the secrets with unsupported credential types out of the reconciliation, the PR also updated the predicate in secret controller to reject `Secret` with unsupported credential type in `konghq.com/credential` label.

**Which issue this PR fixes**:

fixes #7218 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/admission/handler.go [hunk 1]
```diff
@@ -295,7 +296,8 @@ func (h RequestHandler) handleSecret(
 	switch request.Operation {
 	case admissionv1.Update, admissionv1.Create:
 		// credential secrets
-		if credType, err := util.ExtractKongCredentialType(&secret); err == nil && credType != "" {
+		// Run ValidateCredential if the secret has the `konghq.com/credential` label and its value is one of supported credential type.
+		if credType, err := util.ExtractKongCredentialType(&secret); err == nil && credentials.SupportedTypes.Has(credType) {
```
Comment (czeslavo) [inline internal/admission/handler.go:300]: This way, we're losing the validation of allowed label values completely. WDYT about adding a slice of known valid values and allowing them explicitly in https://github.com/Kong/kubernetes-ingress-controller/blob/3794e98d14d748fa03403575befdaa3c27de26dd/internal/admission/validation/consumers/credentials/validation.go#L30

```go
	// These are values that are allowed as a credential type out of the KIC context and we should not reject them.
	knownValidValues := []string{"konnect"}
	for _, validValue := range knownValidValues {
		if credentialType == validValue {
			// This is a valid value, we should not reject it here, and skip the further validation as it's dedicated
			// specifically to KIC credentials.
			return nil
		}
	}

	// verify that the credential type provided is valid
	if !SupportedTypes.Has(credentialType) {
		return fmt.Errorf("invalid credential type %s", credentialType)
	}
```

Comment (randmonkey) [reply internal/admission/handler.go:300]: So you have imported one more concept: "Credential types that are known valid but not supported in KIC". This adds more complexity in the validator and controller. Also the "known valid credential" needs extra care for updating if we are adding more types of credentials using the label in other projects. This will bring more work on maintaining given that KIC 3.4 is an LTS.
So IMO ignoring the validation of label value could keep it simpler and less potential future work.

Comment (czeslavo) [reply internal/admission/handler.go:300]: > This adds more complexity in the validator and controller

I think that for the controller, it's the same as what you proposed right now - we should only reconcile Secrets that satisfy `SupportedTypes.Has(credentialType)`. For the validator, it's just this additional step that explicitly ignores allowed values (only `konnect` for now, and most likely, it will never grow).

> Also the "known valid credential" needs extra care for updating if we are adding more types of credentials using the label in other projects. This will bring more work on maintaining given that KIC 3.4 is an LTS. 

I agree it could bring more work if we added more allowed values for this label, but as KGO 1.5 is the last release that deploys KIC as a separate Deployment, we will have no issues with that. Later, we will have KIC's validation webhook integrated into the KO codebase, so we will update it accordingly if we ever want to add a new credential type.

> Other ways could include keep the validation on credential type here, but use other label keys for Secrets used as other types of credentials.

Yes, we made a "mistake" relying on the same label key in KGO as in KIC, but I'm not sure if we can roll it back since it was there from KGO 1.4 already.

Comment (randmonkey) [reply internal/admission/handler.go:300]: > I agree it could bring more work if we added more allowed values for this label, but as KGO 1.5 is the last release that deploys KIC as a separate Deployment, we will have no issues with that. Later, we will have KIC's validation webhook integrated into the KO codebase, so we will update it accordingly if we ever want to add a new credential type.

If we do not expect users to use KO and KIC (3.4 or older) together, I think it is reasonable to do in this way.

Comment (czeslavo) [reply internal/admission/handler.go:300]: KO won't deploy KIC 3.4 for sure. Using KO and KIC at the same time sounds unjustified to me, as you'll be able to achieve the same results with just KO. I think we can bring this topic to Slack and gather others' opinions to reach a decision.

File: internal/admission/validation/consumers/credentials/vars.go [hunk 2]
```diff
@@ -17,6 +17,19 @@ var SupportedTypes = sets.NewString(
 	"mtls-auth",
 )
 
+var ValidTypes = sets.NewString(
```
Comment (czeslavo) [inline internal/admission/validation/consumers/credentials/vars.go:20]: We could add a comment and make sure that `SupportedTypes` is always included in the `ValidTypes`.
```suggestion
// ValidTypes are all types considered as valid. It's a sum of `SupportedTypes` (the ones that KIC reconciles) and other credential types supported outside of KIC (i.e. in KGO).
var ValidTypes = sets.NewString(append(
	SupportedTypes.UnsortedList(),
	// Secrets with `konghq.com/cerdential=konnect is used by KGO.
	// KIC should not reconcile them, but should accept them in validation webhook.
	"konnect",
)...)
```

Comment (randmonkey) [reply internal/admission/validation/consumers/credentials/vars.go:21]: Done.

**Review by czeslavo — APPROVED** [review]
