### PR TITLE
fix(plugins) add suffix to instance_name

### LINKED ISSUE #4516: KongPlugin instance_name needs suffixes on generated plugins
Per conversation with @hbagdi, the plugin `instance_name` field must be globally unique (or possibly workspace unique, though I don't think it should matter for us--the controller can only address a single workspace, so it can't handle cross-workspace concerns even if we wanted to).

Usage of the KongPlugin resource will attempt duplicate `instance_name` values on different Kong plugin instances in several common cases:

- The KongPlugin is applied to multiple resources.
- The KongPlugin is applied to a resource that requires multiple Kong resources, such as an Ingress that cannot be represented with a single Kong route.

In the former case, users can create separate KongPlugins, but this is not ideal. In the latter case, there is no workaround other than not using `instance_name`. 

We need some mechanism of differentiating `instance_name`  values in these cases. This would likely take the form of a short random suffix. Counters or attached resource name are also viable options, though the latter could be quite long.

UX considerations are that this value ultimately gets used as a human-friendly identifier to distinguish multiple plugins of the same type in Manager (or, I guess, jq filters in admin API output), e.g.

instance

The UI can filter on instance names and allows partial matches, so a filter for `instance-` will find both `instance-bn45` and `instance-tf5r`, so a random suffix is close enough to giving all Kong plugins from a single KongPlugin the same name.

Acceptance:

- [ ] When a KongPlugin with `instance_name` set is applied to multiple Kong resources, the resulting Kong plugins have unique `instance_name` values and Kong does not reject configuration.
- [ ] The same is true when a KongPlugin is attached to a resource that requires multiple Kong resources and thus multiple Kong plugins. AFAIK only Ingress, xRoute, and Service are the resources that can have a 1:many resource:Kong entity relationship.
- [ ] Controller documentation describes the transform we use and explains why we use it.

### PR DESCRIPTION
**Pull request by rainest**
**What this PR does / why we need it**:

Attach a short hash (or full hash, in the event of a short hash collision) of the attached entity to generated plugin `instance_name` values.

instance_name must be unique. Applying the same KongPlugin to multiple resources, or resources that generate multiple Kong entities, would violate this rule otherwise.

**Which issue this PR fixes**:

Fix #4516 

**Special notes for your reviewer**:

Although not covered in the original issue, the suffixes need to be consistent to avoid constant config updates in DB mode, so random suffixes or counters (the iteration order can vary and changes when new plugins are added) aren't an option. I initially did the entity name verbatim, but this is indeed quite long. Full hashes are actually longer, but should be extremely rare in practice.

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/dataplane/kongstate/kongstate.go [hunk 1]
```diff
@@ -342,21 +344,40 @@ func buildPlugins(
...
 				plugin.Route = &kong.Route{ID: kong.String(rel.Route)}
+				sha = sha256.Sum256([]byte(rel.Route))
 			}
 			if rel.Consumer != "" {
 				plugin.Consumer = &kong.Consumer{ID: kong.String(rel.Consumer)}
+				sha = sha256.Sum256([]byte(rel.Consumer))
 			}
 			if rel.ConsumerGroup != "" {
 				plugin.ConsumerGroup = &kong.ConsumerGroup{ID: kong.String(rel.ConsumerGroup)}
+				sha = sha256.Sum256([]byte(rel.ConsumerGroup))
```
Comment (randmonkey) [inline internal/dataplane/kongstate/kongstate.go:367]: Although it is very unlikely to happen, could `Consumer` and `ConsumerGroup` have the same name? I suggest to add some bits annotating the type of attached entity, like `service-***`, `route-***`, `consumer-***` or `consumer-group-***`.

**Review by randmonkey — APPROVED** [review]

**Comment by mheap** [comment]
@rainest Will this be released as a patch to 2.11?
