### PR TITLE
fix: validation for update-in-place unique constrained credentials

### LINKED ISSUE #2190: Credentials Validation - updates in place for referenced credentials utilizing a constrained key fail erroneously
### Current Behavior

If you create a consumer credential secret using a constrained key like `basic-auth` and link it to a credential, then later try to update the value of that credential this will fail validation.

### Expected Behavior

Updates in place should pass validation.

### Kong Ingress Controller version

```shell
v1.2.1
```

### Kubernetes version

```shell
1.19
```

### PR DESCRIPTION
**Pull request by shaneutt**
**What this PR does / why we need it**:

We had a previous oversight in our recent validation code and tests which missed the case where a credential `Secret` referenced by a managed `KongConsumer` could wrongly fail validation if it employed a unique constrained key and the value was updated. This patch fixes that issue and adds an integration test item for the missing coverage.

**Which issue this PR fixes**

Resolves #2190 

**Special notes for your reviewer**:

I tested the new integration test for this against in `main`, where it failed (expected) prior to this branch where it now passes.

**PR Readiness Checklist**:

- [x] the `CHANGELOG.md` release notes have been updated

### CODE REVIEW

File: internal/admission/validator.go [hunk 1]
```diff
@@ -123,17 +124,27 @@ func (validator KongHTTPValidator) ValidateConsumer(
...
 		}
 
 		// if valid, store it so we can index it for upcoming constraints validation
 		credentials = append(credentials, secret)
+
+		// later we'll build a global index of all credentials which is needed to
+		// validate unique key constraints. That index should omit the secrets that
+		// are referenced by this consumer to avoid duplication.
+		if _, ok := ignoredSecrets[consumer.Namespace]; !ok {
+			ignoredSecrets[consumer.Namespace] = make(map[string]struct{})
```
Comment (seh) [inline internal/admission/validator.go:138]: Perhaps:
```suggestion
			ignoredSecrets[consumer.Namespace] = make(map[string]struct{}, len(consumer.Credentials))
```

File: internal/admission/validator.go [hunk 2]
```diff
@@ -173,26 +184,34 @@ func (validator KongHTTPValidator) ValidateCredential(
...
+	}
 
-		// unique constraints on consumer credentials are global to all consumers
-		// and credentials, so we must build an index based on all existing credentials.
-		credentialsIndex, err := globalValidationIndexForCredentials(ctx, validator.ManagerClient, managedConsumers)
-		if err != nil {
-			return false, ErrTextConsumerCredentialValidationFailed, err
-		}
+	// now that we know at least one managed consumer is referencing this
+	// secret we perform the base level credentials secret validation.
```
Comment (seh) [inline internal/admission/validator.go:197]:
```suggestion
	// secret we perform the base-level credentials secret validation.
```

File: internal/admission/validator.go [hunk 3]
```diff
@@ -173,26 +184,34 @@ func (validator KongHTTPValidator) ValidateCredential(
...
+	if err := credsvalidation.ValidateCredentials(&secret); err != nil {
+		return false, ErrTextConsumerCredentialValidationFailed, err
+	}
 
-		// validate this new credential against an index of existing credentials
-		secretCopy := secret
-		if err := credentialsIndex.ValidateCredentialsForUniqueKeyConstraints(consumerWhichReferencesThisSecret.Name, &secretCopy); err != nil {
-			return false, ErrTextConsumerCredentialValidationFailed, err
-		}
+	// if base level validation passes we move on to create an index of
```
Comment (seh) [inline internal/admission/validator.go:202]:
```suggestion
	// if base-level validation passes we move on to create an index of
```

**Review by rainest — APPROVED** [review]
