### PR TITLE
fix: check nils in ingressClass.Parameters

### LINKED ISSUE #2958: Nightly integration tests failing - GKE & Kubernetes v1.21.0 (test-previous-kubernetes-gke)
Integration tests in the nightly workflow (test-previous-kubernetes-gke) are failing due to the following error: 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x234ceb2]

goroutine 1491 [running]:
github.com/kong/kubernetes-ingress-controller/v2/internal/store.Store.GetIngressClassParametersV1Alpha1(***0x32a9c58, 0xc000c343d8***, ***0x32a9c58, 0xc000c343f0***, ***0x32a9c58, 0xc000c34408***, ***0x32a9c58, 0xc000c34420***, ***0x32a9c58, 0xc000c34438***, ...***, ...***)
	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/store/store.go:868 +0x1b2
github.com/kong/kubernetes-ingress-controller/v2/internal/dataplane/parser.getIngressClassParametersOrDefault(...)
	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/dataplane/parser/parser.go:679
github.com/kong/kubernetes-ingress-controller/v2/internal/dataplane/parser.(*Parser).ingressRulesFromIngressV1beta1(0xc0005e1a98)
	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/dataplane/parser/translate_ingress.go:24 +0x9a
github.com/kong/kubernetes-ingress-controller/v2/internal/dataplane/parser.(*Parser).Build(0xc0005e1a98)
	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/dataplane/parser/parser.go:72 +0x36
github.com/kong/kubernetes-ingress-controller/v2/internal/dataplane.(*KongClient).Update(0xc000c60180, ***0x329ce60, 0xc000a23440***)
	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/dataplane/kong_client.go:314 +0x385
github.com/kong/kubernetes-ingress-controller/v2/internal/dataplane.(*Synchronizer).startUpdateServer(0xc000b375c0, ***0x329ce60, 0xc000a23440***)
	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/dataplane/synchronizer.go:162 +0xdd
created by github.com/kong/kubernetes-ingress-controller/v2/internal/dataplane.(*Synchronizer).Start
	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/dataplane/synchronizer.go:100 +0x14a
FAIL	github.com/kong/kubernetes-ingress-controller/v2/test/integration	435.831s
```

Sample run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3102816618/jobs/5025633520#step:5:674

It's probably caused by dereferencing `ingressClass.Spec.Parameters.Namespace` which is optional when `ingressClass.Spec.Parameters.Scope` is not set to `Namespace`: https://github.com/Kong/kubernetes-ingress-controller/blob/94969ef3dbb82695edc787cb6c69be41de7bdd30/internal/store/store.go#L868

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

fix panics when some field is `nil` in `ingressClass.spec.parameters`

**Which issue this PR fixes**:

fixes #2958.

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/store/store.go [hunk 1]
```diff
@@ -865,6 +866,12 @@ func (s Store) GetIngressClassParametersV1Alpha1() (*kongv1alpha1.IngressClassPa
 		)}
 	}
 
+	if ingressClass.Spec.Parameters.Scope == nil || ingressClass.Spec.Parameters.Namespace == nil {
+		return nil, ErrNotFound{
+			message: fmt.Sprintf("IngressClass %s should reference namespaced parameters", ingressClass),
+		}
+	}
```
Comment (czeslavo) [inline internal/store/store.go:873]: Shouldn't we handle both `Scope` options (`Cluster` and `Namespace`)?  As I understand, when:
- `ingressClass.Spec.Parameters.Scope in ("Cluster", nil)`,  it's ok to have `ingressClass.Spec.Parameters.Namespace` nil and it means `IngressClass` scope is cluster-wide,
- `ingressClass.Spec.Parameters.Scope == "Namespace"`, we should validate if `ingressClass.Spec.Parameters.Namespace` is not empty and it means `IngressClass` scope is namespaced.

 Am I missing something? Does our controller support cluster-wide `IngressClass`?

Comment (randmonkey) [reply internal/store/store.go:873]: Since `IngressClassParamter` is namespaced, I think we could not suppoer cluster wide `IngressClass` in normal way.

Comment (jrsmroz) [reply internal/store/store.go:873]: Seems like we're going to handle that as separate issue?

Comment (czeslavo) [reply internal/store/store.go:873]: After some reading I think I understand a little bit more:
* `IngressClass` resource is always cluster-wide - ["The IngressClass API itself is always cluster-scoped."](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingressclass-scope) 
* `IngressClass.Spec.Parameters` is a reference to the resource that might be either namespaced or cluster wide. It's specific to the ingress controller. In our case, [`IngressClassParameters` CRD is namespaced](https://github.com/Kong/kubernetes-ingress-controller/blob/08c96459215e86adb297cc595ee67a5f4a4712f5/PROJECT#L57),
* Given above, I conclude it's a valid approach to not accept `IngressClass.Spec.Parameters` referencing cluster-wide resources as we don't support them - `IngressClassParameters` is designed to be namespaced. 

Proposition/question: maybe to avoid future problems with misconfigured `IngressClass.Spec.Parameters` we could add a validation in admission server so that a user is promptly warned?

**Review by czeslavo — APPROVED** [review]

File: internal/store/store.go (hunk 1 above)
Comment (czeslavo) [reply internal/store/store.go:873]: Ah, I missed one more caveat... `IngressClass.Spec.Parameters` has been extended to handle namespaced object references as a result of this upstream issue: https://github.com/kubernetes/enhancements/issues/2365. The feature landed first in Kubernetes 1.22 behind a feature gate, and the gate was removed in 1.25. 

If I understand correctly, that makes our `IngressClassParameters` compatible only with Kubernetes versions >= 1.22 (with feature gate defined) and 1.25 (out of the box). 

That means that if we want to support Kubernetes < 1.22 we will have to introduce another, cluster scoped CRD.

Comment (czeslavo) [reply internal/store/store.go:873]: I guess an alternative would be to make that lack of support is clear in docs and adapt our tests to run conditionally only for supported k8s versions.

**Review by jrsmroz — APPROVED** [review]

File: internal/store/store.go (hunk 1 above)
Comment (rainest) [reply internal/store/store.go:873]: It looks like this was enabled by default in 1.22 and made GA in 1.23--they may have kept the gate around but it's been in place for a while per [the feature gate list](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features). Beyond that, [1.22 will EOL in about a month](https://kubernetes.io/releases/#release-v1-22), so I don't think we have good cause to try and support versions further back than that--had we known this for https://github.com/Kong/kubernetes-ingress-controller/pull/2883#issue-1359432365 I would have had more reason to convert it to cluster-scoped, but alas--it's out in the wild now and even though it's only been there for a short while we can't really pull it back.

We need to update the compatibility tables, but shouldn't have a need to support both cluster-scoped and namespaced variants.

**Comment by rainest** [comment]
Initial failures in integration-tests-dbless were for UDPRoute and TLSRoute:

UDPRoute failed because the listener had no valid Kong port to associate with. Somehow this port was present on the deployment, but was TCP instead of UDP. Not sure how KTF would have that temporarily, but the code there does look at least partially incorrect. UDP stream listens should live in [a different config section](https://github.com/Kong/charts/blob/969273853af9ccc7a407c7badbff27f3dc0ff91e/charts/kong/values.yaml#L340-L367) because of LoadBalancer inability to handle mixed TCP/UDP services:

```
09:51:05-0700 esenin $ grep -r 9999
pkg/clusters/addons/kong/vars.go:	DefaultUDPServicePort = 9999
09:51:08-0700 esenin $ grep -r DefaultUDPServicePort
pkg/clusters/addons/kong/vars.go:	// DefaultUDPServicePort indicates the default open port to be found on the Kong proxy's UDP service.
pkg/clusters/addons/kong/vars.go:	DefaultUDPServicePort = 9999
pkg/clusters/addons/kong/addon.go:	return urlForService(ctx, cluster, types.NamespacedName{Namespace: a.namespace, Name: DefaultUDPServiceName}, DefaultUDPServicePort)
pkg/clusters/addons/kong/addon.go:		"--set", fmt.Sprintf("proxy.stream[1].containerPort=%d", DefaultUDPServicePort),
pkg/clusters/addons/kong/addon.go:		"--set", fmt.Sprintf("proxy.stream[1].servicePort=%d", DefaultUDPServicePort),
pkg/clusters/addons/kong/addon.go:		Port:     DefaultUDPServicePort,
```
However, elsewhere it tries to set the `udp` parameter manually, so that should satisfy what Gateway wants to check:
```
 562 func exposePortsDefault() []string {                                                                                    
  563     return []string{                                                                                                    
  564         "--set", fmt.Sprintf("proxy.stream[0].containerPort=%d", DefaultTCPServicePort),                                
  565         "--set", fmt.Sprintf("proxy.stream[0].servicePort=%d", DefaultTCPServicePort),                                  
  566         "--set", fmt.Sprintf("proxy.stream[1].containerPort=%d", DefaultUDPServicePort),                                                
  567         "--set", fmt.Sprintf("proxy.stream[1].servicePort=%d", DefaultUDPServicePort),                                  
  568         "--set", "proxy.stream[1].parameters[0]=udp",                                                                   
  569         "--set", "proxy.stream[1].parameters[1]=reuseport",                                                             
  570         "--set", fmt.Sprintf("proxy.stream[2].containerPort=%d", DefaultTLSServicePort),                                
  571         "--set", fmt.Sprintf("proxy.stream[2].servicePort=%d", DefaultTLSServicePort),                                  
  572         "--set", "proxy.stream[2].parameters[0]=ssl",                                                                   
  573         "--set", "proxy.stream[2].parameters[1]=reuseport",                                                             
  574     }                                                                                                                   
  575 }
```

TLSRoute unsure. Its listener is fine, but the route itself has no status and was apparently never acknowledged. Controller logs appear to simply not see it.

File: internal/dataplane/parser/ingressclassparemeters_test.go [hunk 2]
```diff
@@ -0,0 +1,158 @@
...
+				ObjectMeta: metav1.ObjectMeta{
+					Namespace: testNamespaceName,
+					Name:      tc.name,
+				},
+				Spec: netv1.IngressClassSpec{
+					Parameters: tc.paramRef,
+				},
+			}
+			cacheStores, err := store.NewCacheStoresFromObjs()
+			assert.NoError(t, err)
```
Comment (pmalek) [inline internal/dataplane/parser/ingressclassparemeters_test.go:140]: Those would better use `require` instead to prevent continuing execution, so that when an error occurs we don't continue the test as it would be pointless.
