### PR TITLE
Fix Ingresses with certificates in 2.x

### LINKED ISSUE #1354: KIC 2.0 - Fix certificate support
Secret fetching appears to be broken currently, cascading on to issues loading certificates. With:

```
$ kubectl get secret -n helmgress test 
NAME   TYPE                DATA   AGE
test   kubernetes.io/tls   2      606d
```
Adding:

```
  tls: 
  - hosts:
    - strippy.example
    secretName: test
```
Results in:
```
time="2021-05-25T23:16:11Z" level=error msg="failed to fetch secret: Secret helmgress/test not found"
```

### PR DESCRIPTION
**Pull request by rainest**
**What this PR does / why we need it**:
- Adds a Secret controller. This controller is always enabled because it's used by almost all other controllers (I believe only the Service controller won't ever use it, and we realistically won't ever run the Service controller alone).
- Tests Ingresses with certificates and SNI annotations. These were previously broken because you couldn't load the Secret containing a certificate.
- Moves alpha.2 items out of the alpha.1 changelog into a new alpha.2 section.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1354

**Special notes for your reviewer**:
I _expect_ this to fix other Secret-based functionality. We use Secrets when loading custom entities, when loading plugin configuration from a `ConfigFrom` setting, when loading credentials, and probably several other places I'm forgetting. These should have been broken without a Secret controller, and should not require additional code to work (most should use existing code shared with 1.x, same as Ingresses with certificates). However, the only features tested in this PR are Ingresses that use certificates and Ingresses that have SNI annotations.

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: railgun/test/integration/suite_test.go [hunk 1]
```diff
@@ -338,6 +348,8 @@ func waitForExistingClusterReadiness(ctx context.Context, cluster ktfkind.Cluste
 			ready <- ktfkind.ProxyReadinessEvent{
 				ProxyAdminURL: proxyAdminURL,
 				ProxyURL:      proxyURL,
+				ProxyHTTPSURL: proxyHTTPSURL,
+				ProxyIP:       proxyIP,
```
Comment (ccfishk) [inline railgun/test/integration/suite_test.go:352]: Isn't ProxyIP included within ProxyURL ?

File: railgun/test/integration/suite_test.go [hunk 2]
```diff
@@ -325,6 +328,13 @@ func waitForExistingClusterReadiness(ctx context.Context, cluster ktfkind.Cluste
 						ready <- ktfkind.ProxyReadinessEvent{Err: err}
 						break
 					}
+					proxyHTTPSURL, err = url.Parse(fmt.Sprintf("https://%s:%d", svc.Status.LoadBalancer.Ingress[0].IP, 443))
+					if err != nil {
+						ready <- ktfkind.ProxyReadinessEvent{Err: err}
+						break
+					}
+					addr := net.ParseIP(svc.Status.LoadBalancer.Ingress[0].IP)
+					proxyIP = &addr
```
Comment (ccfishk) [inline railgun/test/integration/suite_test.go:337]: It would be better validating the IP address since the status changes.

**Review by ccfishk — COMMENTED** [review]
Overall LGTM, just curious : V1 Secrete is K8S nature resource, why generated clientset/versioned/informers files get changed in this case ? 
Can you please drop those changes ?

**Comment by rainest** [comment]
UDPIngress tests breaking appears to be consistent. Not sure how that broke, but need to investigate it, so back to draft.

File: railgun/test/integration/suite_test.go (hunk 1 above)
Comment (rainest) [reply railgun/test/integration/suite_test.go:352]: Yes, though not as the dedicated type, and with additional info we don't want in some cases. We want the IP alone in some cases. We need it here for the DNS overrides (to trick Go's HTTP client into sending the SNI value we want) and IMO it's more convenient for the framework to expose that than parsing it out of the string URLs.

Comment (ccfishk) [reply railgun/test/integration/suite_test.go:352]: This only used in TestMain, agree with the convenience.

File: railgun/test/integration/suite_test.go (hunk 2 above)
Comment (rainest) [reply railgun/test/integration/suite_test.go:337]: It's basically copying what the others do, and they don't validate when populating URLs, only blindly format the URL strings.

@shaneutt I don't often use this particular piece of functionality, but I believe we're just relying on the check above (`len(svc.Status.LoadBalancer.Ingress) == 1`) to guarantee that _any_ status info is present, and assuming that it must then have a valid IP, correct? If not, this entire block is bypassed, the proxy URL variable isn't set, and the `proxyURL != nil` condition after fails, continuing the loop, correct? Is there any case where the status length check would succeed without actually having an IP available? Would we need to tighten this?

**Comment by rainest** [comment]
> Overall LGTM, just curious : V1 Secrete is K8S nature resource, why generated clientset/versioned/informers files get changed in this case ? Can you please drop those changes ?

This doesn't add a clientset (which we definitely don't want to generate, it should be in stock client-go). There are some changes to that source but it's just because some format rule changed and the generator updated it accordingly:  https://github.com/Kong/kubernetes-ingress-controller/pull/1439/files#diff-4d0a24424ebdcaf1278ff41633cfd72930270ae1ec5c784029f03436bbf334b2

The other parts we do need since the controller doesn't natively have any code that would add Secrets to its store, which is why this was broken originally. We do have generated code for the stock types we interact with in there, e.g. https://github.com/Kong/kubernetes-ingress-controller/blob/2.0.0-alpha.1/railgun/controllers/configuration/zz_generated_controllers.go#L44-L104

Shane had indicated that the TCP/UDPIngress test failures were unrelated flakes introduced elsewhere, and while those apparently aren't fixed yet, tests passed after merging in latest next, so un-drafting again.

File: railgun/test/integration/suite_test.go (hunk 2 above)
Comment (ccfishk) [reply railgun/test/integration/suite_test.go:337]: Do you mind I chime in since Shane already on the beach with beer :). 
 technically Line 336 should return a valid IP if no error/exception, since ProxyURL already present, an easier way retrieving proxy IP
proxyURL.Hostname()

**Review by ccfishk — COMMENTED** [review]
Super ! those clientset/versioned/informer files are dropped. In the long term, we dont want have that kind of dependency anymore !

File: railgun/test/integration/suite_test.go (hunk 2 above)
Comment (ccfishk) [reply railgun/test/integration/suite_test.go:337]:
```suggestion
					proxyIP = proxyURL.Hostname()
```

Comment (rainest) [reply railgun/test/integration/suite_test.go:337]: This actually broke because the types aren't the same :facepalm: 

We could parse  `proxyURL.Hostname()` to the dedicated IP type, but thinking over it some more, we could potentially switch to DNS hostnames for the URLs in the future, and if so that'd break parsing. The IP field in status is guaranteed to be an IP string, so using that is safer.

**Comment by shaneutt** [comment]
> UDPIngress tests breaking appears to be consistent. Not sure how that broke, but need to investigate it, so back to draft.

There's several timing issues at play I've been tracking down that aren't specific to `UDPIngress`, but have been manifesting themselves that way. Just a heads up that https://github.com/Kong/kubernetes-ingress-controller/pull/1400 is where these are being worked on and when that merges you should see improved stability.

File: railgun/test/integration/suite_test.go (hunk 2 above)
Comment (ccfishk) [reply railgun/test/integration/suite_test.go:337]: If work in the cloud env, HostName(), or the external IP of the Proxy ( Loadbalancer Type) is a valid DNS which is accessible publicly.

Are you still need an IP address in that case ?

File: railgun/manager/run.go [hunk 3]
```diff
@@ -175,6 +176,15 @@ func Run(ctx context.Context, c *config.Config) error {
 				Proxy:  prx,
 			},
 		},
+		{
+			IsEnabled: &alwaysEnabled,
```
Comment (ccfishk) [inline railgun/manager/run.go:180]: To be more consistent, a SecreteEnablement field can be defined within controller config structure as all other controller do. Please use that

**Review by ccfishk — COMMENTED** [review]
Add a few comments.

File: railgun/test/integration/suite_test.go (hunk 2 above)
Comment (rainest) [reply railgun/test/integration/suite_test.go:338]: In the context it's used, yes. It's for things like https://github.com/Kong/kubernetes-ingress-controller/pull/1439/files#diff-3b890c93c344e46a0243585a4ab4a5b3d9c8eba953fc1ad9693ceaa81c70746aR536-R547 where a test needs to override DNS and pretend that some other hostname resolves to the proxy IP.

File: railgun/manager/run.go (hunk 3 above)
Comment (rainest) [reply railgun/manager/run.go:180]: The way we load Secrets is most like Endpoints, which [aren't independent](https://github.com/Kong/kubernetes-ingress-controller/blob/2ce512d67980a29fa6fea73127b6e9037912271e/railgun/manager/run.go#L171-L177) (they share enablement with Services).

Broadly, we load Secrets from other objects, e.g. to provide a certificate for an Ingress, configuration for a plugin, etc. They're used widely across a variety of types, however (versus Endpoints being specific to Services), so there are a number of controllers that potentially depend on them. The "proper" condition would be something like:

```
IsEnabled: &c.ServiceEnabled || &c.IngressNetV1Enabled || &c.IngressNetV1beta1Enabled || &c.IngressExtV1beta1Enabled || &c.TCPIngressEnabled || &c.KongClusterPluginEnabled || &c.KongPluginEnabled || &c.KongConsumerEnabled ...
```
Practically speaking, if you enable almost anything, you also enable the Secret controller. I can only think of very contrived configurations that shouldn't exist in practice where it's not a dependency (e.g. enabling only the KongIngress controller), so simply enabling it always instead of writing out the complete condition seemed appropriate. Does that reasoning make sense/do you still think this would need to change?

Comment (ccfishk) [reply railgun/manager/run.go:180]: hmm... understand. thanks for clarification. Please go as it is.

**Review by ccfishk — APPROVED** [review]
responds
