### PR TITLE
fix: solve the restart caused by kong not starting

### LINKED ISSUE #761: When the pod of kong has not yet provided services normally, start ingress-controller and exit with an error
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

When I deploy kong in DB-less mode, the following error occurs occasionally:

```
F0707 07:17:41.033745       1 main.go:201] making HTTP request: Get "https://127.0.0.1:8444/": dial tcp 127.0.0.1:8444: connect: connection refused
```

<details>
<summary>The complete log is as follows:</summary>

```
root@inspurtest14-5dxzrw2a3j-master-1:~# kubectl get pod -n knative-kong
NAME                            READY   STATUS        RESTARTS   AGE
ingress-kong-5c494f694f-j87p7   2/2     Running       2          38s
ingress-kong-5c494f694f-vtz4z   1/2     Running       2          38s
ingress-kong-5c494f694f-vwbnq   2/2     Running       2          38s
root@inspurtest14-5dxzrw2a3j-master-1:~# kubectl logs -n knative-kong ingress-kong-5c494f694f-j87p7 -c ingress-controller --previous 
-------------------------------------------------------------------------------
Kong Ingress controller
  Release:    0.9.0
  Build:      0aad24a
  Repository: git@github.com:kong/kubernetes-ingress-controller.git
  Go:         go1.14.1
-------------------------------------------------------------------------------

W0707 07:17:41.016935       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0707 07:17:41.017319       1 main.go:492] Creating API client for https://10.150.0.1:443
I0707 07:17:41.028979       1 main.go:536] Running in Kubernetes Cluster version v1.16 (v1.16.2) - git (archive) commit c97fe5036ef3df2967d086711e6c0c405941e14b - platform linux/amd64
F0707 07:17:41.033745       1 main.go:201] making HTTP request: Get "https://127.0.0.1:8444/": dial tcp 127.0.0.1:8444: connect: connection refused
```
</details>

I think this is due to the failure of the request caused by the admin service in the kong proxy container has not been provided normally.

Can this problem be avoided by increasing the number of retries or delaying access? Make pod startup elegant.

**Kong Ingress controller version**

0.9.0

**Kong or Kong Enterprise version**

2.0.4

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"archive", BuildDate:"2020-04-01T07:37:16Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

- **Cloud provider or hardware configuration**: None
- **OS** (e.g. from /etc/os-release): 
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
- **Kernel** (e.g. `uname -a`):
Linux xxxxxxxxxxxx-5dxzrw2a3j-master-1 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: None
- **Others**: None

### What happened

Occasionally a Pod needs to be restarted one or more times to run normally.

### Expected behavior

Pod can start normally without restarting.

### Steps To Reproduce

1. Use this guide to install(Made a small amount of changes to suit my environment): https://docs.konghq.com/2.0.x/kong-for-kubernetes/install/
2. The above problem may occur, Pod's RESTARTS is not zero.
3. If the above problem does not occur, increase the deployment replicas and the problem will occur.

<details>
<summary>Attach my deployment below:</summary>

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"ingress-kong"},"name":"ingress-kong","namespace":"knative-kong"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"ingress-kong"}},"template":{"metadata":{"annotations":{"kuma.io/gateway":"enabled","prometheus.io/port":"8100","prometheus.io/scrape":"true","traffic.sidecar.istio.io/includeInboundPorts":""},"labels":{"app":"ingress-kong"}},"spec":{"containers":[{"env":[{"name":"KONG_PROXY_LISTEN","value":"0.0.0.0:8000, 0.0.0.0:8443 ssl http2"},{"name":"KONG_ADMIN_LISTEN","value":"127.0.0.1:8444 ssl"},{"name":"KONG_STATUS_LISTEN","value":"0.0.0.0:8100"},{"name":"KONG_DATABASE","value":"off"},{"name":"KONG_NGINX_WORKER_PROCESSES","value":"1"},{"name":"KONG_ADMIN_ACCESS_LOG","value":"/dev/stdout"},{"name":"KONG_ADMIN_ERROR_LOG","value":"/dev/stderr"},{"name":"KONG_PROXY_ACCESS_LOG","value":"/dev/stdout"},{"name":"KONG_PROXY_ERROR_LOG","value":"/dev/stderr"},{"name":"KONG_PLUGINS","value":"bundled,fcs-proxy"}],"image":"master2:5000/kong:2.0.4-ubuntu-dev","imagePullPolicy":"Always","lifecycle":{"preStop":{"exec":{"command":["/bin/sh","-c","kong quit"]}}},"livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/status","port":8100,"scheme":"HTTP"},"initialDelaySeconds":5,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"proxy","ports":[{"containerPort":8000,"name":"proxy","protocol":"TCP"},{"containerPort":8443,"name":"proxy-ssl","protocol":"TCP"},{"containerPort":8100,"name":"metrics","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/status","port":8100,"scheme":"HTTP"},"initialDelaySeconds":5,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"securityContext":{"runAsUser":1000}},{"env":[{"name":"CONTROLLER_KONG_ADMIN_URL","value":"https://127.0.0.1:8444"},{"name":"CONTROLLER_KONG_ADMIN_TLS_SKIP_VERIFY","value":"true"},{"name":"CONTROLLER_PUBLISH_SERVICE","value":"knative-kong/kong-proxy"},{"name":"POD_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}}],"image":"master2:5000/kong-ingress-controller:0.9.0","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":10254,"scheme":"HTTP"},"initialDelaySeconds":5,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"ingress-controller","ports":[{"containerPort":8080,"name":"webhook","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":10254,"scheme":"HTTP"},"initialDelaySeconds":5,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1}}],"serviceAccountName":"kong-serviceaccount"}}}}
  creationTimestamp: "2020-06-01T09:38:49Z"
  generation: 12
  labels:
    app: ingress-kong
  name: ingress-kong
  namespace: knative-kong
  resourceVersion: "20576404"
  selfLink: /apis/apps/v1/namespaces/knative-kong/deployments/ingress-kong
  uid: 20f82d45-f36b-4a11-b66b-ab151ffccbbc
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ingress-kong
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kuma.io/gateway: enabled
        prometheus.io/port: "8100"
        prometheus.io/scrape: "true"
        traffic.sidecar.istio.io/includeInboundPorts: ""
      creationTimestamp: null
      labels:
        app: ingress-kong
    spec:
      containers:
      - env:
        - name: KONG_PROXY_LISTEN
          value: 0.0.0.0:8000, 0.0.0.0:8443 ssl http2
        - name: KONG_ADMIN_LISTEN
          value: 127.0.0.1:8444 ssl
        - name: KONG_STATUS_LISTEN
          value: 0.0.0.0:8100
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_NGINX_WORKER_PROCESSES
          value: "1"
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        - name: KONG_PROXY_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_PROXY_ERROR_LOG
          value: /dev/stderr
        - name: KONG_PLUGINS
          value: bundled,fcs-proxy
        image: master2:5000/kong:2.0.4-ubuntu-dev
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - kong quit
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 8100
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: proxy
        ports:
        - containerPort: 8000
          name: proxy
          protocol: TCP
        - containerPort: 8443
          name: proxy-ssl
          protocol: TCP
        - containerPort: 8100
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 8100
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --election-id=elecid-test
        env:
        - name: CONTROLLER_KONG_ADMIN_URL
          value: https://127.0.0.1:8444
        - name: CONTROLLER_KONG_ADMIN_TLS_SKIP_VERIFY
          value: "true"
        - name: CONTROLLER_PUBLISH_SERVICE
          value: knative-kong/kong-proxy
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: master2:5000/kong-ingress-controller:0.9.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: ingress-controller
        ports:
        - containerPort: 8080
          name: webhook
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kong-serviceaccount
      serviceAccountName: kong-serviceaccount
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2020-06-01T09:38:49Z"
    lastUpdateTime: "2020-07-07T03:29:00Z"
    message: ReplicaSet "ingress-kong-5c494f694f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-07-07T07:18:15Z"
    lastUpdateTime: "2020-07-07T07:18:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 12
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
```
</details>

### LINKED ISSUE #766: Retry with timeout during boot to wait for kong to start up
Multiple users have reported that the controller goes into a crash loop backoff state if kong container doesn't start up before the controller or if there is delay in startup of the kong container.

Add in a retry with back-off and timeout (30s) to the initial API call that the controller makes to Kong. This should result in more pods being started without any restarts.

See #761 and multiple posts on Kong Nation.

### PR DESCRIPTION
**Pull request by yuchunyu97**
Added retry when getting data returned by Kong Admin API.

fixes #761 
fixes #766

### CODE REVIEW

File: cli/ingress-controller/main.go [hunk 1]
```diff
@@ -196,9 +196,22 @@ func main() {
 		glog.Fatalf("Error creating Kong Rest client: %v", err)
 	}
 
-	root, err := kongClient.Root(context.Background())
-	if err != nil {
-		glog.Fatalf("%v", err)
+	// fix: https://github.com/Kong/kubernetes-ingress-controller/issues/761
```
Comment (hbagdi) [inline cli/ingress-controller/main.go:199]: Please remove this comment.

File: cli/ingress-controller/main.go [hunk 2]
```diff
@@ -196,9 +196,22 @@ func main() {
...
+	var root map[string]interface{}
+	retry := 0
+	for {
+		root, err = kongClient.Root(context.Background())
+		if err != nil {
+			if retry > 5 {
+				glog.Fatalf("%v", err)
```
Comment (hbagdi) [inline cli/ingress-controller/main.go:206]: Can you please rebase this change on the `next` branch instead?
A lot has changed in the next branch w.r.t. logging.

File: cli/ingress-controller/main.go [hunk 3]
```diff
@@ -196,9 +196,22 @@ func main() {
...
+			} else {
+				retry++
+				time.Sleep(time.Second * 5)
```
Comment (hbagdi) [inline cli/ingress-controller/main.go:209]: We should use exponential backoff instead of a static sleep here.

You can refer how it is done in the following file for reference:
https://github.com/Kong/kubernetes-ingress-controller/blob/master/internal/ingress/election/election.go#L40-L49

File: cli/ingress-controller/main.go [hunk 4]
```diff
@@ -241,9 +242,25 @@ func main() {
...
+			} else {
+				backoff.Next(backoffID, backoff.Clock.Now())
+				delay := backoff.Get(backoffID)
+				time.Sleep(delay)
+				retryCount++
+				klog.Infof("retry %d to fetch metadata from kong: %v", retryCount, err)
+				continue
+			}
+		}
+		break
```
Comment (hbagdi) [inline cli/ingress-controller/main.go:263]: 1. Please use log instead of klog. log is based on logrus, which provided structured logging for this project.
2. The branching could be made more readable:

```
for {
 root, err := kongClient...
  if err == nil {
    break
  }
  if retryCount > 5 {
    klog.Fatalf
  }
  // at this point, there is an error and a retry should be attempted
  
  // log the err
  // backoff logic
}
```
We should try to use minimum number of break and continue statements to avoid edge cases when a change is made to the code in future.

**Comment by hbagdi** [comment]
Thank you for your contribution. Please fill out the following form to claim your contributor swag:
https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#contributor-t-shirt.
