### PR TITLE
Resend config if status reports hash empty

### LINKED ISSUE #2107: Ingress controller leaves replacement proxy containers without pushed configuration
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Please see Kong/kong#8152 for where this started—in particular, starting with https://github.com/Kong/kong/issues/8152#issuecomment-994822052. To summarize, if the ingress controller starts up successfully, pushes configuration to the proxy container at least once, and then the proxy container exits (perhaps killed by the kubelet due to its liveness probe failing), when a replacement proxy container starts, the ingress controller will not bother to push any configuration to the proxy until some observed cluster state changes materially. This is only the case when the "reverse sync" feature is disabled, as it is by default.

The ingress controller decides against pushing the configuration to the proxy as an optimization: Finding that the serialized configuration's message digest hasn't changed since the last successful push, there's seemingly no reason to push what would be the same configuration again. Unfortunately, the proxy container on the other side of that exchange is a different one from the last one that received the intended configuration.

Since the ingress controller's readiness gate is latching, once it's pushed one configuration successfully, it remains ready forevermore. Ideally we'd clear this flag each time that we detect that the proxy container has either no configuration or has fallen behind by some number of attempted updates.

### Expected Behavior

The ingress controller should have a way to detect that the current proxy container lacks the intended configuration. There are several potential approaches; assuming that we wish to retain the current optimization, all of these straw men are more complicated than what we have today:
- Create an `emptyDir` volume in the pod, mount it into both the ingress controller and proxy containers, have the ingress controller create and listen on a domain socket, and have the proxy container connect to it. When the proxy container hangs up, the ingress controller should assume that the next proxy container needs fresh configuration.
- Create an `emptyDir` volume, mount it into both the ingress controller and proxy containers, have the proxy container read its container ID from the _/proc/self/cgroup_ file, and write it to a file in that shared volume. The ingress controller can watch that file's content and react to the container ID changing, assuming that a change means that the next proxy container needs fresh configuration.
- Grant RBAC permission for Kong's ingress controller to watch pods. The ingress controller would demand its own pod namespace and name via the Downward API, and it would open a watch on its own pod. From the updates, it can read the "status.containerStatuses[1].containerID" field to learn when the proxy container gets replaced.

### Steps To Reproduce

```markdown
1. Create a pod with both the ingress controller and proxy containers.
2. Confirm that the ingress controller becomes ready.
3. Use Kong's admin API to confirm that it has a route and service for at least one set of Kubernetes Ingress and Service objects.
4. Ensure that the observable cluster state remains stable.
5. Kill the proxy container.
6. Confirm that a replacement proxy container starts.
7. Wait at least three seconds.
8. Use Kong's admin API to confirm that it has no routes or services.
```

### Kong Ingress Controller version

```shell
v2.0.6
```

### Kubernetes version

```shell
version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:00:06Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rainest**
**What this PR does / why we need it**:
Bumps the Kong version to 2.8, the first version that supports this.

Resends configuration when the proxy instance reports its initial, no config present hash.

Adds tests to verify config recovers after a crash. Fixes a bug where we trusted the standard proxy 404 response when verifying Ingresses due to an improperly-bounded if.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2107

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Comment by rainest** [comment]
Initial E2E run ran this PR's test successfully, but failed on another existing test due to it not actually deploying an Ingress. Second run after fixing that: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/2018941298

File: internal/dataplane/sendconfig/sendconfig.go [hunk 1]
```diff
@@ -49,8 +51,22 @@ func PerformUpdate(ctx context.Context,
...
 			}
-			log.Debug("no configuration change, skipping sync to kong")
-			return oldSHA, nil
+			// we assume ready as not all Kong versions provide their configuration hash, and their readiness state
+			// is always unknown
+			ready := true
+			status, err := kongConfig.Client.Status(ctx)
+			if err != nil {
+				log.Errorf("checking config status failed: %w", err)
+				log.Debug("configuration state unknown, skipping sync to kong")
```
Comment (shaneutt) [inline internal/dataplane/sendconfig/sendconfig.go:60]: Are there any situations you can think of where the status would return an error, but it would still be otherwise possible to push `/config` to the admin API? :thinking:

File: test/e2e/all_in_one_test.go [hunk 2]
```diff
@@ -101,11 +101,25 @@ func TestDeployAllInOneDBLESS(t *testing.T) {
...
 
 	t.Log("running ingress tests to verify all-in-one deployed ingress controller and proxy are functional")
 	deployIngress(ctx, t, env)
 	verifyIngress(ctx, t, env)
+
+	t.Log("killing Kong process to simulate a crash and container restart")
+	killKong(ctx, t, env, &pod)
+
+	t.Log("confirming that routes are restored after crash")
+	verifyIngress(ctx, t, env)
```
Comment (shaneutt) [inline test/e2e/all_in_one_test.go:122]: :+1:

File: internal/dataplane/sendconfig/sendconfig.go (hunk 1 above)
Comment (rainest) [reply internal/dataplane/sendconfig/sendconfig.go:60]: In practice, probably not really. Status shouldn't normally fail unless something something is quite wrong (to the point where Kong APIs aren't able to respond to much of anything) or Kong is unreachable over the network, and it failing implies impending doom for the Pod because it's also the liveness check.

Still, seems prudent to log it/

Comment (shaneutt) [reply internal/dataplane/sendconfig/sendconfig.go:60]: :+1:

**Review by shaneutt — APPROVED** [review]
