### PR TITLE
fix: fix panic when handling KongConsumer without username

### LINKED ISSUE #6552: Providing customID but not username in KongConsumer does not work
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

From FTI-6236.
The customer uses a `KongConsumer` with empty `username` and non-empty `custom_id`, ans see panic in KIC.

### Expected Behavior

`KongConsumer` with non empty `custom_id` but empty `username` should also work. 

### Steps To Reproduce

```markdown
1. Setup a Kong Env using KIC
2. Attempt to apply a KongConsumer with no username, just a custom_id
3. Observe KIC logs, it will Crash Loop shortly after
```

### Kong Ingress Controller version

```shell
3.3.1
```

### Kubernetes version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pmalek**
**What this PR does / why we need it**:

Fix handling `KongConsumer` without `username` specified. Currently we allow to [set just the `custom_id` on the consumer](https://github.com/Kong/kubernetes-ingress-controller/blob/5bcd583300191c5b36daf18c32d22fae0c58d0c4/pkg/apis/configuration/v1/kongconsumer_types.go#L32) (as an alternative to setting just the `username`).

This PR fixes the former case where `username` is not specified.

**Which issue this PR fixes**:

Fixes #6552 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/dataplane/deckgen/consumer_cmp.go [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+
+	// Both usernames are equal, compare custom_id.
+	if f[i].CustomID == nil && f[j].CustomID != nil {
+		return true
+	}
+	if f[i].CustomID != nil && f[j].CustomID == nil {
+		return false
+	}
+	if f[i].CustomID != nil && f[j].CustomID != nil {
+		switch cmp := strings.Compare(*f[i].CustomID, *f[j].CustomID); cmp {
```
Comment (randmonkey) [inline internal/dataplane/deckgen/consumer_cmp.go:39]: We do not need to act differently for the 3 cases so I think just use `<=` here is OK.

Comment (pmalek) [reply internal/dataplane/deckgen/consumer_cmp.go:39]: Can you elaborate? In my mind we have to separate those 3 case because:

- if `strings.Compare()` returns -1 we return `true` (`i`th element is "smaller" than `j`th)
- if `strings.Compare()` returns 1 we return `false` (`i`th element is "bigger" than `j`th)
- if `strings.Compare()` returns 0 we continue comparing


We **can** make this shorter into something like:

```
	if f[i].CustomID != nil && f[j].CustomID != nil {
		return strings.Compare(*f[i].CustomID, *f[j].CustomID) == -1
	}
	return false
```

but IMHO that would make this a bit less readable. Additionally if we ever want to extend the comparison criteria it's easy to do: just add these comparisons below vs if we make it shorter then we need to refactor a lot more.

WDYT?

File: CHANGELOG.md [hunk 2]
```diff
@@ -129,6 +129,8 @@ Adding a new version? You'll need three changes:
   kubernetes event with `KongConfigurationTranslationFailed` will be reported
   for each involved `KongConsumer`.
   [#6585](https://github.com/Kong/kubernetes-ingress-controller/pull/6585)
+- Fix panic when handling `KongConsumer` without `username` specified
```
Comment (randmonkey) [inline CHANGELOG.md:132]:
```suggestion
- Fix panic when handling `KongConsumer` without `username` specified.
```

File: internal/dataplane/deckgen/consumer_cmp.go (hunk 1 above)
Comment (randmonkey) [reply internal/dataplane/deckgen/consumer_cmp.go:39]: Yes, I agree that use the switch-case is clearer that `-1` or `1` stops the comparing, and `0` means we cannot know which one is "less" in the step and may invoke comparing on other attributes.
In this case, I think we could add some comments on the last step.
However, `0` means that we got 2 consumers with the same (non-empty) `username` or `custom_id`, which is invalid. But I believe that it should be processed elsewhere.

File: internal/dataplane/deckgen/consumer_cmp.go [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+		case -1:
+			return true
+		case 1:
+			return false
+		case 0:
+			break
+		}
+	}
+
+	// Both usernames are equal, compare custom_id.
```
Comment (randmonkey) [inline internal/dataplane/deckgen/consumer_cmp.go:31]:
```suggestion
	// Both usernames are empty or equal, compare custom_id.
```
Should we mention that we would compare `custom_id` if both `username` are empty in the comment here?

Comment (pmalek) [reply internal/dataplane/deckgen/consumer_cmp.go:31]: Technically if they are both empty then they are equal :) But I'm OK with adding this note in the comment.

File: internal/dataplane/deckgen/consumer_cmp.go (hunk 1 above)
Comment (pmalek) [reply internal/dataplane/deckgen/consumer_cmp.go:39]: > However, 0 means that we got 2 consumers with the same (non-empty) username or custom_id, which is invalid. But I believe that it should be processed elsewhere.

Yes, that should be caught somewhere else. Here, we're only focused on sorting the slice of consumers rather than validating it.

Added a comment about that in 39071064eae4dabee4d58ccd428389180e31a7dc

**Review by randmonkey — APPROVED** [review]
