### PR TITLE
Test(e2e): List entities instead of dump.Get to fetch Kong config in e2e tests

### LINKED ISSUE #6317: e2e test `TestDeployAllInOneDBLESS` fails on kind environment
Recently `TestDeployAllInOneDBLESS` e2e test case running on kind environment fails on getting configuration from Kong gateway pods. The failure of dumping config is caused by port forwarding not work, like: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/9902467231/job/27356436727.   
The same case running on GKE passed, and also it can run on local kind env.  Also, https://github.com/Kong/kubernetes-ingress-controller/actions/runs/9902467231/job/27356450395 fails for the same reason.
So there maybe some issue on forwarding ports in kind env on the GH runners.

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

List `Services`, `Routes`, `Upstreams` and `Targets` to verify Kong configuration in gateway pods in `verifyIngressWithEchoBackendsInAdminAPI` instead of `dump.Get`. This could reduce the concurrency of streams to forwarded ports.

e2e run passes: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/10173800539. 

**Which issue this PR fixes**:

Fixes #6317 
**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

~- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~  No need to update changelog.

### CODE REVIEW

File: test/e2e/helpers_test.go [hunk 1]
```diff
@@ -528,31 +527,48 @@ func verifyIngressWithEchoBackendsInAdminAPI(
...
+
+		targets, err := kongClient.Targets.ListAll(ctx, upstreams[0].ID)
+		if err != nil {
+			t.Logf("failed to list targets for upstream %s: %v", *upstreams[0].ID, err)
 			return false
 		}
-		if len(d.Upstreams) != 1 {
-			t.Log("still no upstream found...")
+		if len(targets) != noReplicas {
+			t.Log("still no targets found...")
```
Comment (pmalek) [inline test/e2e/helpers_test.go:571]: We might want to add a bit more debugging info. Something along the lines:

```suggestion
			t.Logf("expected %d targets, found %d", noReplicas, len(targets))
```

File: test/e2e/helpers_test.go [hunk 2]
```diff
@@ -528,31 +527,48 @@ func verifyIngressWithEchoBackendsInAdminAPI(
...
 		}
-		if len(d.Routes) != 1 {
+
+		routes, _, err := kongClient.Routes.ListForService(ctx, services[0].ID, &kong.ListOpt{Size: 10})
+		if err != nil {
+			t.Logf("failed to list routes for service %s: %v", *services[0].ID, err)
+			return false
+		}
+		if len(routes) != 1 {
 			t.Log("still no route found...")
```
Comment (pmalek) [inline test/e2e/helpers_test.go:551]: Ditto:

```suggestion
			t.Logf("found %d routes, expected %d", len(routes), 1)
```

File: test/e2e/helpers_test.go [hunk 3]
```diff
@@ -528,31 +527,48 @@ func verifyIngressWithEchoBackendsInAdminAPI(
...
+
+		services, err := kongClient.Services.ListAll(ctx)
 		if err != nil {
-			t.Logf("failed dumping config: %s", err)
+			t.Logf("failed to list services: %v", err)
 			return false
 		}
-		if len(d.Services) != 1 {
+		if len(services) != 1 || services[0].ID == nil {
 			t.Log("still no service found...")
```
Comment (pmalek) [inline test/e2e/helpers_test.go:541]:
```suggestion
			t.Logf("found %d services, expected %d", len(services), 1)
```

File: test/e2e/helpers_test.go [hunk 4]
```diff
@@ -528,31 +527,48 @@ func verifyIngressWithEchoBackendsInAdminAPI(
 	t.Helper()
 
 	require.Eventually(t, func() bool {
-		d, err := dump.Get(ctx, kongClient, dump.Config{})
+		start := time.Now()
+		defer func() {
+			t.Logf("Try fetching config from %q started at %s, duration %v", kongClient.BaseRootURL(), start.Format(time.RFC3339), time.Since(start))
```
Comment (pmalek) [inline test/e2e/helpers_test.go:532]: This fill log after the fetching is done so I believe the log should reflect that:

```suggestion
			t.Logf("Fetched config from %q, started at %s, duration %v", kongClient.BaseRootURL(), start.Format(time.RFC3339), time.Since(start))
```

File: test/e2e/helpers_test.go [hunk 5]
```diff
@@ -528,31 +527,48 @@ func verifyIngressWithEchoBackendsInAdminAPI(
...
-		if len(d.Services) != 1 {
-			t.Log("still no service found...")
+		if len(services) != 1 || services[0].ID == nil {
+			t.Logf("%d services found, expected 1", len(services))
 			return false
 		}
-		if len(d.Routes) != 1 {
-			t.Log("still no route found...")
+
+		routes, _, err := kongClient.Routes.ListForService(ctx, services[0].ID, &kong.ListOpt{Size: 10})
```
Comment (tao12345666333) [inline test/e2e/helpers_test.go:545]: nit: why do we choose `10` for this?

Comment (randmonkey) [reply test/e2e/helpers_test.go:545]: Just an arbitrary value. I think we can leave it empty to use the "default" value.
