### PR TITLE
fix(status) retry updates if LB is pending

### LINKED ISSUE #1925: Ingress Does not Get Assigned Address
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I install Kong from the bit.ly URL in GKE (not sure about anywhere else), and create an Ingress in a script. The Ingress resource does get assigned an IP address. Doing `kubectl -n kong rollout restart deployment ingress-kong` jogs it into working again.

### Expected Behavior

Ingress should be assigned the kong proxy IP address.

### Steps To Reproduce

```markdown
Attached is a script snippet:


kubectl create namespace kong --context $KUBE_CONTEXT

kubectl create secret generic kong-enterprise-license --from-file=./license -n kong --context=$KUBE_CONTEXT

kubectl apply -f https://bit.ly/k4k8s-enterprise-install --context $KUBE_CONTEXT

echo "apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuma-control-plane
  namespace: $NS
  annotations:
    konghq.com/strip-path: 'true'
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: $CP_SERVICE
          servicePort: 5681
        path: /kuma" | kubectl --context $KUBE_CONTEXT apply -f -
```
```


### Kong Ingress Controller version

```shell
v2.0.2
```

### Kubernetes version

```shell
1.19.13-gke.1200
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rainest**
**What this PR does / why we need it**:

If the status subsystem receives a config update and cannot update status because its target LoadBalancer is pending, retry the status update in one minute. Discard retries and retry them no further if we've received a newer config since, to allow the newer config to retry instead

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1925

**Special notes for your reviewer**:
Testing this for the intended issue would require an unusual and unique environment not supported in current KTF (we spawn the cluster, start Kong, check that status is empty after adding an Ingress, install metallb, and then check status again to confirm it populates). Asking for manual confirmation and allowing existing tests to confirm that this does not break status entirely.

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Comment by rainest** [comment]
@doctorwu can you run with `traines/kic:v2.1.1-36-g3923ec1a` in your affected environment to confirm if it clears the slow LB == no status until changes after issue?

Wanted to get integration tests clear, but they're failing because they're exceeding 20m total. Not seeing any actual failures on a spot check though, so it should be ready enough to try on a test instance.

**Comment by rainest** [comment]
New image: `traines/kic:v2.1.1-39-g2b9cc91e`

There were some concurrency goofs earlier. Manual testing by spawning KIND, installing Kong, and then installing metallb after appears to confirm this now works.

**Comment by rainest** [comment]
Per Damon, the latest version clears the issue, and my manual testing in a weird (delayed metallb install) environment show the same. Weird test environment needs mean that CI will only confirm that this does not break normal status operation.

File: internal/ctrlutils/ingress-status.go [hunk 1]
```diff
@@ -120,11 +120,23 @@ func (s *StatusUpdater) PullConfigUpdate(
...
 	cfg := statusConfig{ready: false}
 	status := statusInfo{ready: false}
+	latest := time.Unix(0, 0)
 	var wg sync.WaitGroup
 	var err error
 	for {
 		select {
 		case updateDone := <-s.kongConfig.ConfigDone:
+			s.log.V(util.DebugLevel).Info("status handler received config", "timestamp", updateDone.Timestamp,
+				"latest", latest)
```
Comment (shaneutt) [inline internal/ctrlutils/ingress-status.go:130]: nit: it's very minor but technically the first pass through this will log a timestamp that at best will be meaningless, but at worst confusing for anyone reading the logs. We could wrap the timestamp in an object which could produce a "no previous configuration" string for logging purposes and then the string timestamp after an update has successfully processed.

File: internal/ctrlutils/ingress-status.go [hunk 2]
```diff
@@ -142,13 +154,18 @@ func (s *StatusUpdater) PullConfigUpdate(
 						s.log.Error(err, "failed to look up status info for Kong proxy Service", "service", s.publishService)
 					}
 				}
+				go func() {
+					time.Sleep(time.Minute * 1)
+					s.kongConfig.ConfigDone <- updateDone
+					s.log.V(util.DebugLevel).Info("retrying update", "timestamp", updateDone.Timestamp)
+				}()
```
Comment (shaneutt) [inline internal/ctrlutils/ingress-status.go:161]: It appears this function is at the center of the fix we're trying to provide here as it makes sure that a config update doesn't go out of band. While we expect eventual consistency herein it could theoretically run indefinitely (or at least very long in the case of a slow GKE LB) which I understand to be the reason we've added a `time.Sleep` but I think the minute timing is a bit too long for two reasons:

1. at least currently the updates that result here are effectively for presentation/cosmetics, so we expect a human is watching
2. re-queuing the update is very low cost since we will simply throw it away if it becomes outdated

As such, I'm OK with a slight sleep here so that we're reducing log spam, but I think something with a shorter turnaround might be more ideal:

```suggestion
				go func() {
					time.Sleep(time.Second * 3)
					s.kongConfig.ConfigDone <- updateDone
					s.log.V(util.DebugLevel).Info("retrying update", "timestamp", updateDone.Timestamp)
				}()
```

And then I think we should capture this value in a variable and document it:

```go
// configUpdateRetryWait is a delay that will occur before trying to re-publish
// a configuration update that could not be published because the statusConfig
// was not yet ready.
const configUpdateRetryWait = time.Second * 3
```

**Review by shaneutt — CHANGES_REQUESTED** [review]
Thanks for fixing this :+1: 

Ultimately the code in this area seems to scream rewrite, but since we've already documented that in https://github.com/Kong/kubernetes-ingress-controller/issues/2007 I feel that's already in hand and this is a reasonable patch for the moment.

I understand that you've said before that integration testing this is difficult because you have to engineer a situation where a LoadBalancer implementation is slow, but since we've had to patch this area of code multiple times shortly after the 2.x release (and in spite of our plans to rewrite it later) it seems like we could add some unit tests here that would help verify the logic and also help to avoid the introductions of regressions later.

File: internal/ctrlutils/ingress-status.go (hunk 1 above)
Comment (rainest) [reply internal/ctrlutils/ingress-status.go]: Removed it. Any case latest actually matters to the branch taken it's logged there, after being set to an actual time.

File: internal/ctrlutils/ingress-status.go (hunk 2 above)
Comment (rainest) [reply internal/ctrlutils/ingress-status.go]: Time left as-is. The longer wait is intended more for the case where the LB never actually provisions, in which some retry will continue logging indefinitely, and the log is useless spam.

For the case where a retry actually matters (LB slow to provision), it's a one-off event at startup on a fresh install. I raised the log level and added the duration to make it clearer what's happening.

**Comment by rainest** [comment]
The K8S API interactions in `runningAddresses()` and `UpdateStatuses()` lock us into integration tests without either a mock K8S API or some very convoluted refactoring to try and allow unit testing the rest, unless I'm missing some sort of unit testing strategy that'd be useful here.

**Review by shaneutt — APPROVED** [review]
> The K8S API interactions in `runningAddresses()` and `UpdateStatuses()` lock us into integration tests without either a mock K8S API or some very convoluted refactoring to try and allow unit testing the rest, unless I'm missing some sort of unit testing strategy that'd be useful here.

It looks like we may be able to provide a fake k8s client that could help us with some of this, but I understand your point that this is not straightforward. Due to the fact that we've had multiple regressions or bugs come out of this area of code (so much so that we defined https://github.com/Kong/kubernetes-ingress-controller/issues/2007) I feel tentative about approving a change that doesn't have some level of unit or integration tests, but I also understand that the implication of #2007 is that if it takes a heavy investment to add tests that could feel quite wasted in time. Ultimately I have confidence in the manual testing that you have done and the patch is quite straightforward so I do not want to block, but this is just even more sign that we need to be pursuing #2007 at a high priority so I have [marked it as such](https://github.com/Kong/kubernetes-ingress-controller/issues/2007#issuecomment-1020394966).
