### PR TITLE
Fix(sendconfig): Keep ID of existing plugins

### LINKED ISSUE #7440: Controller tries to Create already existing Kong plugins in DB mode
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

What happened?
Requests that were routed via kong took lots of time, looking at kong logs I saw:

```
 [error] 1407#0: *6433 connect() failed (111: Connection refused) while connecting to upstream, client: IP, server: kong, request: "GET REQUEST", upstream: "HTTP REQUEST", host: "<HOST>", request_id: "b29c2670491fc66a1bd8531cd73b3c25"
```
The ip it tried to reach was of a deleted pod (for some reason kong was not updated).
Then I stated to look at the kong gateway logs and saw admin api errors:

```
 [notice] 1407#0: *119453 [lua] init.lua:234: upsert(): ERROR: duplicate key value violates unique constraint "plugins_cache_key_key"
```

These request came from the ingress controller that also shows errors:
```
failed updating gateway entity
```

I looking at my monitoring tool I saw that the failing SQL in the kong gateway was:
```
INSERT INTO "plugins" ("id", "name", "instance_name", "created_at", "updated_at", "route_id", "service_id", "consumer_id", "config", "protocols", "enabled", "tags", "cache_key", "ws_id")
     VALUES ('31de5e6c-4b20-5310-bead-8d9ff1e436fb', 'prometheus', NULL, TO_TIMESTAMP(1737914272) AT TIME ZONE 'UTC', TO_TIMESTAMP(1747387774) AT TIME ZONE 'UTC', 'fd13a599-6e7b-5b3e-93da-83db3c09d2b3', NULL, NULL, '{"latency_metrics":true,"ai_metrics":false,"per_consumer":true,"status_code_metrics":true,"bandwidth_metrics":true,"upstream_health_metrics":true}', ARRAY['grpc','grpcs','http','https'], TRUE, ARRAY['k8s-name:kong-prometheus','k8s-namespace:NAMESPACE','k8s-kind:KongPlugin','k8s-uid:d2a649c2-bf7e-45e4-8fea-19fb26e6b494','k8s-group:configuration.konghq.com','k8s-version:v1','managed-by-ingress-controller'], 'plugins:prometheus:fd13a599-6e7b-5b3e-93da-83db3c09d2b3::::781ad82e-3fa4-4635-8a39-4d0ed0b0bd7c', '781ad82e-3fa4-4635-8a39-4d0ed0b0bd7c')
ON CONFLICT ("id") DO UPDATE
        SET "name" = EXCLUDED."name", "instance_name" = EXCLUDED."instance_name", "created_at" = EXCLUDED."created_at", "updated_at" = EXCLUDED."updated_at", "route_id" = EXCLUDED."route_id", "service_id" = EXCLUDED."service_id", "consumer_id" = EXCLUDED."consumer_id", "config" = EXCLUDED."config", "protocols" = EXCLUDED."protocols", "enabled" = EXCLUDED."enabled", "tags" = EXCLUDED."tags", "cache_key" = EXCLUDED."cache_key", "ws_id" = EXCLUDED."ws_id"
  RETURNING "id", "name", "instance_name", EXTRACT(EPOCH FROM "created_at" AT TIME ZONE 'UTC') AS "created_at", EXTRACT(EPOCH FROM "updated_at" AT TIME ZONE 'UTC') AS "updated_at", "route_id", "service_id", "consumer_id", "config", "protocols", "enabled", "tags", "ws_id";
```

I saw this SQL error for each plugin entry in the database.
Looking at the database and the entry it tries to insert - they are the same except for the "ID" field - becasue of that, the `ON CONFLICT ("id")` doesn't work and we get the error on the cache_key.

To make a quick fix I deleted the database entries and let the ingress controller reconcile and insert them again.

Here are two entries that should have been the same. One is the original and the other is the new one (you can see that all the fields are identical except the id):

```
226aa112-227a-523b-b1b7-eaf695fa9627	2025-05-18 13:37:21+00	request-transformer	NULL	NULL	77035440-e4b4-5354-809f-dfcf0f915e83	{"add": {"body": [], "headers": ["x-source-type:$(uri_captures[1])"], "querystring": []}, "append": {"body": [], "headers": [], "querystring": []}, "remove": {"body": [], "headers": [], "querystring": []}, "rename": {"body": [], "headers": [], "querystring": []}, "replace": {"uri": "/logs", "body": [], "headers": [], "querystring": []}, "http_method": null}	TRUE	plugins:request-transformer:77035440-e4b4-5354-809f-dfcf0f915e83::::781ad82e-3fa4-4635-8a39-4d0ed0b0bd7c	{grpc,grpcs,http,https}	{k8s-name:ingest-request-transformer,k8s-namespace:onyx,k8s-kind:KongPlugin,k8s-uid:cb0f34c1-0703-41d2-a85b-ec72800a5d3f,k8s-group:configuration.konghq.com,k8s-version:v1,managed-by-ingress-controller}	781ad82e-3fa4-4635-8a39-4d0ed0b0bd7c	NULL	2025-05-18 13:37:21+00

4ddeca04-e880-4bb0-afc8-7597dd8a5230	2025-01-07 08:37:07+00	request-transformer	NULL	NULL	77035440-e4b4-5354-809f-dfcf0f915e83	{"add": {"body": [], "headers": ["x-source-type:$(uri_captures[1])"], "querystring": []}, "append": {"body": [], "headers": [], "querystring": []}, "remove": {"body": [], "headers": [], "querystring": []}, "rename": {"body": [], "headers": [], "querystring": []}, "replace": {"uri": "/logs", "body": [], "headers": [], "querystring": []}, "http_method": null}	TRUE	plugins:request-transformer:77035440-e4b4-5354-809f-dfcf0f915e83::::781ad82e-3fa4-4635-8a39-4d0ed0b0bd7c	{grpc,grpcs,http,https}	{k8s-name:ingest-request-transformer,k8s-namespace:onyx,k8s-kind:KongPlugin,k8s-uid:cb0f34c1-0703-41d2-a85b-ec72800a5d3f,k8s-group:configuration.konghq.com,k8s-version:v1,managed-by-ingress-controller}	781ad82e-3fa4-4635-8a39-4d0ed0b0bd7c	NULL	2025-04-17 17:27:29+00
```

Investigating more shows me that the error started due to a kubernetes node teminration (by karpenter) - I see one of my kong pods showing `FailedPreStopHook: PreStopHook failed`. However, I see it happened from time to time.

### Expected Behavior

There are two things that bothers me - 
1. because of the ingress controller plugin issue - kong didn't work correctly which caused prod issues
2. What happened to the ingress controller? what didn't it reconcile the existing plugins?

### Steps To Reproduce

```markdown

```

### Kong Ingress Controller version

```shell
I'm using the chart:
  - name: ingress
    version: "0.18.0"
    repository: "https://charts.konghq.com"
```

### Kubernetes version

```shell
v1.32.3-eks-bcf3d70
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

Keep the plugin ID (identified by plugin name and attached service, route, consumer, consumer group) to prevent conflicts of two identical plugins (identified by the fields above) having the different ID

**Which issue this PR fixes**:

fixes #7440
**Special notes for your reviewer**:

We also needs to add integration tests/e2e tests for upgrading in DB mode: https://github.com/Kong/kubernetes-ingress-controller/issues/7448. Should we finish it also in this PR?
**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/dataplane/sendconfig/dbmode.go [hunk 1]
```diff
@@ -267,3 +271,52 @@ func (s *UpdateStrategyDBMode) targetState(
...
+		if err != nil {
+			if !errors.Is(err, state.ErrNotFound) {
+				s.logger.Error(err, "failed to get plugin with given fields in the target state")
+			}
+			continue
+		}
+		if existingPlugin.ID != nil && targetPlugin.ID != nil && *targetPlugin.ID != *existingPlugin.ID {
+			// The memdb to store the target state uses `id` to identify the plugin.
+			// So we need to delete the plugin with the new ID first then insert the same plugin with the same ID as the existing plugin.
+			err = targetState.Plugins.Delete(*targetPlugin.ID)
```
Comment (randmonkey) [inline internal/dataplane/sendconfig/dbmode.go:310]: REVIEW: should we directly `return err` when we failed to run the deletion and re-insertion?

File: internal/dataplane/sendconfig/dbmode_test.go [hunk 2]
```diff
@@ -0,0 +1,283 @@
...
+			}
+			err := s.refillPluginIDs(tc.currentState, tc.targetState)
+			require.NoError(t, err)
+			_, err = tc.targetState.Plugins.Get(tc.expectedPluginID)
+			require.NoError(t, err)
+		})
+	}
+}
+
+func mustNewKongStateFromRawState(t *testing.T, rawState *deckutils.KongRawState) *state.KongState {
```
Comment (pmalek) [inline internal/dataplane/sendconfig/dbmode_test.go:279]:
```suggestion
func mustNewKongStateFromRawState(t *testing.T, rawState *deckutils.KongRawState) *state.KongState {
	t.Helper()

```

File: internal/dataplane/sendconfig/dbmode.go [hunk 3]
```diff
@@ -267,3 +271,52 @@ func (s *UpdateStrategyDBMode) targetState(
...
+		// we re-fill the ID of the plugin in the target state to keep the ID the same as the existing plugin.
+		targetPlugin, err := targetState.Plugins.GetByProp(*existingPlugin.Name, serviceID, routeID, consumerID, consumerGroupID)
+		if err != nil {
+			if !errors.Is(err, state.ErrNotFound) {
+				s.logger.Error(err, "failed to get plugin with given fields in the target state")
+			}
+			continue
+		}
+		if existingPlugin.ID != nil && targetPlugin.ID != nil && *targetPlugin.ID != *existingPlugin.ID {
+			// The memdb to store the target state uses `id` to identify the plugin.
```
[the remark this answers is not in the document]
Comment (pmalek) [reply internal/dataplane/sendconfig/dbmode.go:308]: 👍

File: internal/dataplane/sendconfig/dbmode.go (hunk 1 above)
Comment (pmalek) [reply internal/dataplane/sendconfig/dbmode.go:310]: I believe we should. That would mean we'd retain the current behavior when there's an error, right? Which means we'd silently continue on an error and allow broken configuration to propagate.

Q: does this return an error if the target state doesn't contain a plugin with requested ID? If so I believe that particular error should be silenced, right?

Comment (randmonkey) [reply internal/dataplane/sendconfig/dbmode.go:310]: > I believe we should. That would mean we'd retain the current behavior when there's an error, right? Which means we'd silently continue on an error and allow broken configuration to propagate.
> 
> Q: does this return an error if the target state doesn't contain a plugin with requested ID? If so I believe that particular error should be silenced, right?

If the target state does not contain the plugin with the ID, an `ErrNotFound` is returned. So this particular error can be ignored and other errors should be returned.

**Review by pmalek — APPROVED** [review]
