### PR TITLE
fix(log): do not parse error body when response is empty in reloading config

### LINKED ISSUE #4665: When failed to get response from `ReloadDeclarativeConfig`, log "could not unmarshal config error: unexpected end of JSON input" will appear
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When failed to get response from `ReloadDeclarativeConfig` in dbless mode, for example when the client timed out to wait for the response, we will get a `nil` for response, and try to parse it as a resource parsing error. This causes log 
```
level=error msg="failed parsing resource errors" error="could not unmarshal config error: unexpected end of JSON input" 
```
which is misleading.

### Expected Behavior

When failed to get response from `ReloadDeclarativeConfig`, we do not see the misleading error `could not unmarshal`.

### Steps To Reproduce

```markdown
1. Deploy KIC & Kong gateway, and set CONTROLLER_PROXY_TIMEOUT_SECONDS to a short duration (like 1 for 1 second)
2. create many ingresses to generate a configuration with large size
3. When the reloading configuration fails, we will see "could not unmarshal config error: unexpected end of JSON input" in KIC log
```

### Kong Ingress Controller version

```shell
v2.11.1
```

### Kubernetes version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

When Kong client fails to get response from reloading declarative configuration (`POST /config`), do not parse the error body and directly return the error for not getting response, to produce less misleading error log (than `could not unmarshal config error: unexpected end of JSON input`) for the situations.

**Which issue this PR fixes**:

fixes #4665

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/dataplane/sendconfig/inmemory.go [hunk 1]
```diff
@@ -66,6 +66,11 @@ func (s UpdateStrategyInMemory) Update(ctx context.Context, targetState ContentW
 
 	flattenErrors := shouldUseFlattenedErrors(s.version)
 	if errBody, err := s.configService.ReloadDeclarativeRawConfig(ctx, bytes.NewReader(config), true, flattenErrors); err != nil {
+		if len(errBody) == 0 {
+			// if we failed to get response in reloading config, we put the error from reloading in the parseErr return value
```
Comment (programmer04) [inline internal/dataplane/sendconfig/inmemory.go:70]:
```suggestion
			// If we failed to get response in reloading config, we put the error from reloading in the parseErr return value
```

**Review by programmer04 — DISMISSED** [review]

File: CHANGELOG.md [hunk 2]
```diff
@@ -105,6 +105,9 @@ Adding a new version? You'll need three changes:
 
 ### Fixed
 
+- Do not parse error body when failed to get response from reloading declartive
```
Comment (pmalek) [inline CHANGELOG.md:108]:
```suggestion
- Do not parse error body when failed to get response from reloading declarative
```

File: internal/dataplane/sendconfig/inmemory.go [hunk 3]
```diff
@@ -66,6 +66,11 @@ func (s UpdateStrategyInMemory) Update(ctx context.Context, targetState ContentW
 
 	flattenErrors := shouldUseFlattenedErrors(s.version)
 	if errBody, err := s.configService.ReloadDeclarativeRawConfig(ctx, bytes.NewReader(config), true, flattenErrors); err != nil {
+		if len(errBody) == 0 {
+			// If we failed to get response in reloading config, we put the error from reloading in the parseErr return value
+			// to generate a proper error log.
+			return err, nil, err
```
Comment (pmalek) [inline internal/dataplane/sendconfig/inmemory.go:72]: The error is being returned here as parser error put it's not really a parser error right?

File: internal/dataplane/sendconfig/inmemory.go [hunk 4]
```diff
@@ -66,6 +66,11 @@ func (s UpdateStrategyInMemory) Update(ctx context.Context, targetState ContentW
...
+		}
 		resourceErrors, parseErr := parseFlatEntityErrors(errBody, s.log)
```
Comment (pmalek) [inline internal/dataplane/sendconfig/inmemory.go:74]: Wouldn't it be better to handle this in parseFlatEntityErrors?

Comment (randmonkey) [reply internal/dataplane/sendconfig/inmemory.go:74]: The only place where `parseError` is here:
```golang
	if parseErr != nil {
		log.WithError(parseErr).Error("failed parsing resource errors")
		return nil
	}
```
How about returning `nil` here and omit the log when no response get? This might emit better log than returning a fake "parse error".

File: CHANGELOG.md (hunk 2 above)
Comment (randmonkey) [reply CHANGELOG.md]: done.

File: internal/dataplane/sendconfig/inmemory.go (hunk 4 above)
Comment (randmonkey) [reply internal/dataplane/sendconfig/inmemory.go]: moved to `parseFlatEntityErrors`.

**Review by pmalek — COMMENTED** [review]
I believe we best add a test case to https://github.com/Kong/kubernetes-ingress-controller/blob/56a11b9e99253fe1c0d43174173b553126cb4cc0/internal/dataplane/sendconfig/error_handling_test.go for this. WDYT?

**Comment by randmonkey** [comment]
> I believe we best add a test case to https://github.com/Kong/kubernetes-ingress-controller/blob/56a11b9e99253fe1c0d43174173b553126cb4cc0/internal/dataplane/sendconfig/error_handling_test.go for this. WDYT?

Added unit test.

**Review by pmalek — APPROVED** [review]

**Comment by pmalek** [comment]
BTW: when does `POST /config` return an empty body? When returning a 200? Only? Perhaps we should take the status code into account

**Comment by randmonkey** [comment]
> BTW: when does `POST /config` return an empty body? When returning a 200? Only? Perhaps we should take the status code into account

one situation: When `POST /config` took too long and client timed out.
