### PR TITLE
fix(parser): combining overlapping host and service ingress rules

### LINKED ISSUE #3004: ingress rules that have matching  `<hostname><serviceName>` or  `<serviceName><port>` generate wrong kong config
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This issue was found during code analysis.

When a combined routes feature is enabled  - `KONG_CONTROLLER_FEATURE_GATES="CombinedRoutes=true"` - the parser can combine routes into a single service, that should not be combined. 

The condition needed to trigger it is ingress rules that have matching `"<hostname><serviceName>" or "<serviceName><port>"`.

For example, given the Ingress with two rules that match the equality `"company.com"+"ad-service" == "company.co"+"ad-service"`:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
spec:
  ingressClassName: kong
  rules:
  - host: company.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: ad-service
            port:
              number: 80
  - host: company.co
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: mad-service
            port:
              number: 80
```

the parser would generate a kong service for only one of the services (`mad-service`,  `ad-service`) and attach both rules to it.

The same issue can be triggered using service name and ports, i.e  `"ad-service1"+"8080" == "ad-service"+"18080"`:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
spec:
  ingressClassName: kong
  rules:
  - host: company.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: ad-service1
            port:
              number: 8080
  - host: company.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: ad-service
            port:
              number: 18080
```

### Expected Behavior

The ingress rules should be correctly recognized as pointing to different services.

### Steps To Reproduce

```markdown
This issue was found during code analysis and reproduced in unit tests.
```

### Kong Ingress Controller version

```shell
v2.7.0
```

### Kubernetes version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jrsmroz**
**What this PR does / why we need it**:

The translator used to combine the ingress rules into services on rare occasions could combine routes that should not be combined when host and service name in the ingress overlapped.

This commit changes how the ingress translation index computes the key for the entries, preventing overlapping host,serviceName,port combinations from being combined.

**Which issue this PR fixes:**

Fixes #3004 

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/dataplane/parser/translators/ingress.go [hunk 1]
```diff
@@ -98,7 +98,7 @@ func (i *ingressTranslationIndex) add(ingress *netv1.Ingress) {
 			serviceName := httpIngressPath.Backend.Service.Name
 			servicePort := httpIngressPath.Backend.Service.Port.Number
 
-			cacheKey := fmt.Sprintf("%s%s%s%s%d", ingress.Namespace, ingress.Name, ingressRule.Host, serviceName, servicePort)
+			cacheKey := fmt.Sprintf("%s.%s.%s.%s.%d", ingress.Namespace, ingress.Name, ingressRule.Host, serviceName, servicePort)
```
Comment (jrsmroz) [inline internal/dataplane/parser/translators/ingress.go:101]: This alone prevents from overriding rules that have same substring `<ingressRule.Host><serviceName>` or more likely `<serviceName><servicePort>`

**Comment by mlavacca** [comment]
Do we have an issue for this? I feel a bit of context is missing.

**Review by mlavacca — COMMENTED** [review]
Do we have an issue for this? I feel a bit of context is missing.

**Comment by jrsmroz** [comment]
> Do we have an issue for this? I feel a bit of context is missing.

Nope. I've found this key to be fishy when I worked on https://github.com/Kong/kubernetes-ingress-controller/issues/2881

I've created a test case that demonstrates the case how to trigger it. I will open an issue that describes what the test does.

**Comment by jrsmroz** [comment]
Opened #3004

**Review by pmalek — APPROVED** [review]
