### PR TITLE
Fix(controller): Stop reconcilication if KongUpstreamPolicy not referred in reconciled Ingress/HTTPRoute

### LINKED ISSUE #6270: [Kong Ingress Controller Chart] High Load on k8s API with KongUpstreamPolicy and Multiple Ingress Controllers
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using UpstreamPolicy in a Kubernetes cluster with two ingress controllers, there is a cyclic configuration overwrite. Both ingress controllers compete for the UpstreamPolicy resource, leading to high load on the k8s API.

### Expected Behavior

The ingress controllers should handle the UpstreamPolicy resource without cyclic overwrites, avoiding unnecessary load on the k8s API.

### Steps To Reproduce

```markdown
- Set up a Kubernetes cluster
- Deploy two ingress controllers via helm chart.
- Set up debug-level
- Create a CRD UpstreamPolicy for the ingress controllers.
- Observe the cyclic configuration overwrite and high load on the k8s API.
```

### Kong Ingress Controller version

```shell
Kong (version 3.6), KIC (version 3.2)
```

### Kubernetes version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

Stop the reconciliation of `KongUpstreamPolicy` if it is not eventually used in `Ingress` or `HTTPRoute` with matching class. These `KongUpstreamPolicy`s are not loaded into config storage and their status are not updated to prevent races on updating status if there are multiple instances with different ingress classes/controller names are reconciling.  

**Which issue this PR fixes**:

fixes #6270 

**Special notes for your reviewer**:

This may not resolve the problem that in sidecar mode, multiple instances are reconciling the same `KongUpstreamPolicy`. Maybe we should use the similar thing done to other resources like #6395 ?

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/controllers/configuration/kongupstreampolicy_utils.go [hunk 1]
```diff
@@ -106,6 +110,51 @@ func (r *KongUpstreamPolicyReconciler) getServicesReferencingUpstreamPolicy(
...
+}
+
+// getHTTPRoutesReferencingService fetches all HTTPRoutes using a service as its backend.
+func (r *KongUpstreamPolicyReconciler) getHTTPRoutesReferencingService(
+	ctx context.Context,
+	serviceNN k8stypes.NamespacedName,
+) ([]gatewayapi.HTTPRoute, error) {
+	httpRoutes := &gatewayapi.HTTPRouteList{}
+	if err := r.List(ctx, httpRoutes,
+		client.InNamespace(serviceNN.Namespace),
```
Comment (czeslavo) [inline internal/controllers/configuration/kongupstreampolicy_utils.go:135]: An HTTPRoute may refer to a service from a different namespace.

File: internal/controllers/configuration/kongupstreampolicy_utils.go [hunk 2]
```diff
@@ -106,6 +110,51 @@ func (r *KongUpstreamPolicyReconciler) getServicesReferencingUpstreamPolicy(
...
+}
+
+// getHTTPRoutesReferencingServiceFacade fetches all HTTPRoutes using a KongServiceFacade as its backend.
+func (r *KongUpstreamPolicyReconciler) getHTTPRoutesReferencingServiceFacade(
+	ctx context.Context,
+	serviceFacadeNN k8stypes.NamespacedName,
+) ([]gatewayapi.HTTPRoute, error) {
+	httpRoutes := &gatewayapi.HTTPRouteList{}
+	if err := r.List(ctx, httpRoutes,
+		client.InNamespace(serviceFacadeNN.Namespace),
```
Comment (czeslavo) [inline internal/controllers/configuration/kongupstreampolicy_utils.go:150]: Ditto.

File: internal/controllers/configuration/kongupstreampolicy_utils.go [hunk 3]
```diff
@@ -129,6 +178,78 @@ func (r *KongUpstreamPolicyReconciler) maybeGetServiceFacadesReferencingUpstream
 	return serviceFacades.Items, nil
 }
 
+// upstreamPolicyUsedByBackendsOfMatchingClass returns true is the KongUpstreamPolicy is referenced in
+// Services or KongServiceFacades that are used in backends of recociled Ingress or HTTPRoute.
+// If it returns false, the reconciliation is terminated and the controller will not update its status and put it into storage
+// because the KongUpstreamPokicy will not be translated into Kong configuration in such situation.
```
Comment (czeslavo) [inline internal/controllers/configuration/kongupstreampolicy_utils.go:184]:
```suggestion
// because the KongUpstreamPolicy will not be translated into Kong configuration in such situation.
```

File: internal/controllers/configuration/kongupstreampolicy_utils.go [hunk 4]
```diff
@@ -129,6 +178,78 @@ func (r *KongUpstreamPolicyReconciler) maybeGetServiceFacadesReferencingUpstream
...
+// This is implmented for preventing races on updating status of KongUpstreamPolicy.
```
Comment (czeslavo) [inline internal/controllers/configuration/kongupstreampolicy_utils.go:185]:
```suggestion
// This is implemented to prevent races on updating the status of KongUpstreamPolicy.
```

File: internal/controllers/configuration/kongupstreampolicy_utils.go [hunk 5]
```diff
@@ -129,6 +178,78 @@ func (r *KongUpstreamPolicyReconciler) maybeGetServiceFacadesReferencingUpstream
...
+// Ref:.
```
Comment (czeslavo) [inline internal/controllers/configuration/kongupstreampolicy_utils.go:186]:
```suggestion
// Ref: https://github.com/Kong/kubernetes-ingress-controller/issues/6270
```

File: internal/controllers/configuration/kongupstreampolicy_utils.go [hunk 6]
```diff
@@ -129,6 +178,78 @@ func (r *KongUpstreamPolicyReconciler) maybeGetServiceFacadesReferencingUpstream
...
+			}
+			for _, httpRoute := range httpRoutes {
+				attached := r.isRouteAttachedToReconciledGateway(&httpRoute) //nolint:contextcheck
+				if attached {
+					return true, nil
+				}
+			}
+		}
+	}
+	// If no Ingress or HTTPRoute satisfies, return false.
```
Comment (czeslavo) [inline internal/controllers/configuration/kongupstreampolicy_utils.go:240]:
```suggestion
	// If no Ingress or HTTPRoute satisfied, return false.
```

File: internal/controllers/configuration/kongupstreampolicy_controller.go [hunk 7]
```diff
@@ -347,6 +460,27 @@ func (r *KongUpstreamPolicyReconciler) Reconcile(ctx context.Context, req ctrl.R
...
+		}
+	}
+	shouldStore, err := r.upstreamPolicyUsedByBackendsOfMatchingClass(ctx, req.NamespacedName, ctrlutils.IsDefaultIngressClass(class))
+	if err != nil {
+		return ctrl.Result{}, err
+	}
+	if !shouldStore {
+		log.V(logging.DebugLevel).Info("KongUpstreamPolicy is not referenced by Services used as backend of Ingress or HTTPRoute with matching class, skipping reconciliation")
+		return ctrl.Result{}, nil
+	}
```
Comment (czeslavo) [inline internal/controllers/configuration/kongupstreampolicy_controller.go:482]: Can we add an envtest that covers this behavior (status is not populated if a parent HTTPRoute or Ingress is not to be reconciled by KIC)?

**Review by czeslavo — CHANGES_REQUESTED** [review]
In general it looks good to me. 👍  Some nits + a request for an envtest covering the added behavior.

File: internal/controllers/configuration/kongupstreampolicy_controller.go [hunk 8]
```diff
@@ -67,6 +72,12 @@ func (r *KongUpstreamPolicyReconciler) SetupWithManager(mgr ctrl.Manager) error
 		Watches(&corev1.Service{},
 			handler.EnqueueRequestsFromMapFunc(r.getUpstreamPolicyForObject),
 			builder.WithPredicates(predicate.NewPredicateFuncs(doesObjectReferUpstreamPolicy)),
+		).
+		Watches(&netv1.Ingress{},
+			// Watch for Ingress changes to trigger reconciliation for the KongUpstreamPolicies referenced by the Services
+			// used as backend of the Ingress.
+			// REVIEW: add predicate here to filter Ingresses not reconciled by current controller?
```
[the remark this answers is not in the document]
Comment (randmonkey) [reply internal/controllers/configuration/kongupstreampolicy_controller.go]: Added a predicate.

File: internal/controllers/configuration/kongupstreampolicy_utils.go (hunk 1 above)
Comment (randmonkey) [reply internal/controllers/configuration/kongupstreampolicy_utils.go]: Fixed.

File: internal/controllers/configuration/kongupstreampolicy_utils.go (hunk 2 above)
Comment (randmonkey) [reply internal/controllers/configuration/kongupstreampolicy_utils.go]: Done.

File: test/envtest/kongupstreampolicy_test.go [hunk 9]
```diff
@@ -437,3 +437,198 @@ func TestKongUpstreamPolicyWithHTTPRoute(t *testing.T) {
...
+	ctrl.SetLogger(logger)
+
+	diagPort := helpers.GetFreePort(t)
+	ns := CreateNamespace(ctx, t, ctrlClient)
+	RunManager(ctx, t, envcfg,
+		AdminAPIOptFns(),
+		WithPublishService(ns.Name),
+		WithIngressClass(ingressClassName),
+		WithGatewayFeatureEnabled,
+		WithGatewayAPIControllers(),
```
Comment (czeslavo) [inline test/envtest/kongupstreampolicy_test.go:465]:
```suggestion
```

File: internal/controllers/configuration/kongupstreampolicy_controller.go (hunk 7 above)
Comment (randmonkey) [reply internal/controllers/configuration/kongupstreampolicy_controller.go:504]: Added an envtest case.

File: test/envtest/kongupstreampolicy_test.go [hunk 10]
```diff
@@ -437,3 +437,198 @@ func TestKongUpstreamPolicyWithHTTPRoute(t *testing.T) {
...
+				Conditions: discoveryv1.EndpointConditions{
+					Ready:       lo.ToPtr(true),
+					Terminating: lo.ToPtr(false),
+				},
+				TargetRef: testPodReference("pod-1", ns.Name),
+			},
+		},
+		Ports: builder.NewEndpointPort(80).WithName("http").IntoSlice(),
+	}
+	require.NoError(t, ctrlClient.Create(ctx, &es))
```
Comment (czeslavo) [inline test/envtest/kongupstreampolicy_test.go:540]: I think we could skip creating Deployment, Pod, and EndpointSlices in this test as they're not relevant. We just need a dummy Service for a reference in Ingress. This should make the test look more straightforward.

File: test/envtest/kongupstreampolicy_test.go (hunk 9 above)
Comment (randmonkey) [reply test/envtest/kongupstreampolicy_test.go]: Done.

File: test/envtest/kongupstreampolicy_test.go (hunk 10 above)
Comment (randmonkey) [reply test/envtest/kongupstreampolicy_test.go]: Removed unnecessary resource creations.

**Review by czeslavo — APPROVED** [review]
