### PR TITLE
fix: generate routes with hostname match only when GRPCRoute rule does not have matches

### LINKED ISSUE #4154: gRPCRoute tranlator cannot handle wildcard rule
Prior to https://github.com/kubernetes-sigs/gateway-api/pull/1753, the gRPC spec provided a default method match if no matches were specified. This broke the intended meaning of a no-match rule, which should match all requests.

The [gRPC route translator](
https://github.com/Kong/kubernetes-ingress-controller/blob/8f095464f5a9aa55a811bf9792c6458c4fcba11e/internal/dataplane/parser/translators/grpcroute.go#L43-L101) loops over matches to generate routes associated with a GRPCRoute resource. If a rule has no matches, it will result in 0 associated routes. I did not review the ATC generator behavior.

The [current example test manifest](https://github.com/Kong/kubernetes-ingress-controller/blob/8f095464f5a9aa55a811bf9792c6458c4fcba11e/examples/gateway-grpcroute.yaml#L71-L83) uses a 0-match rule. After upgrading the Gateway APIs CRDs to 0.7.1, API requests no longer populated default matches for it. This results in the translator generating 0 routes, whereas it should instead generate a single route that matches any request for `example.com`

To fix:
- [ ] When GWAPI 0.7.1 is installed, a 0-match gRPC rule must generate a single Kong route that matches all requests that match the GRPCRoute hostname with the traditional router.
- [ ] The same is true with the expression router.

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

generate routes matching hostnames only when a `GRPCRoute` rule does not contain a match, covering both traditional and expression routes.

**Which issue this PR fixes**:

fixes #4154 
**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/dataplane/parser/translators/grpcroute.go [hunk 1]
```diff
@@ -48,6 +48,29 @@ func GenerateKongRoutesFromGRPCRouteRule(
 	// gather the k8s object information and hostnames from the grpcroute
 	ingressObjectInfo := util.FromK8sObject(grpcroute)
 
+	// generate a route to match hostnames only if there is no match in the rule.
+	if len(rule.Matches) == 0 {
+		// REVIEW: return an error here to tell parser register a translation error event?
+		if len(grpcroute.Spec.Hostnames) == 0 {
+			return nil
+		}
```
Comment (rainest) [inline internal/dataplane/parser/translators/grpcroute.go:56]: Should this indeed skip the GRPCRoute? https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1alpha2.GRPCRouteSpec indicates Hostname is optional, and doesn't mention special rules for empty-hostname GRPCRoutes.

AFAICT a GRPCRoute that specifies _nothing_ should then match any otherwise unmatched request. We'd want a test case for those also.

If we do fail here yeah, we should modify the signature so that the caller (a parser method) can emit a translation failure event.

File: internal/dataplane/parser/translators/grpcroute_atc.go [hunk 2]
```diff
@@ -29,6 +29,32 @@ func GenerateKongExpressionRoutesFromGRPCRouteRule(grpcroute *gatewayv1alpha2.GR
 	// gather the k8s object information and hostnames from the grpcroute
 	ingressObjectInfo := util.FromK8sObject(grpcroute)
 
+	// generate a route to match hostnames only if there is no match in the rule.
+	if len(rule.Matches) == 0 {
+		// REVIEW: return an error here to tell parser register a translation error event?
+		if len(grpcroute.Spec.Hostnames) == 0 {
+			return nil
+		}
```
Comment (rainest) [inline internal/dataplane/parser/translators/grpcroute_atc.go:37]: Ditto the traditional handler. I think these do result in routes that match any hostname.

**Review by rainest — CHANGES_REQUESTED** [review]
Changelog entry is missing. Probably:

```
- Create routes that match any service and method for GRPCRoute rules with no
  matches.
  [#4512](https://github.com/Kong/kubernetes-ingress-controller/issues/4512)
```

under fixes.

The spec technically does also allow 0-rule GRPCRoutes, but it's not clear to me how we should handle those. Upstream configuration and plugin configuration (via filters) are both handled at the rule level (though our implementation still allows setting plugins at the resource level).

If we do generate configuration from those, we'd need to handle some cases directly in `ingressRulesFromGRPCRoute()`, since the current generator loops over rules and would generate nothing from a 0-rule GRPCRoute. Given the ambiguous purpose I think we defer that from here and see if we can get a response [from upstream](https://kubernetes.slack.com/archives/CR0H13KGA/p1692143402674779).

File: internal/dataplane/parser/translators/grpcroute.go (hunk 1 above)
Comment (randmonkey) [reply internal/dataplane/parser/translators/grpcroute.go:56]: Do you think a rule with no match in a `GRPCRoute` with no hostnames should be a "catch-all" rule that matches ANY request? This behavior is not the same as the current implementation of `HTTPRoute`. I think the proper behavior is to keep the behavior the same as `HTTPRoute`: skip this `GRPCRoute` and report a translation error. If we want to change this behavior, we submit another PR.

File: internal/dataplane/parser/translators/grpcroute_atc.go (hunk 2 above)
Comment (randmonkey) [reply internal/dataplane/parser/translators/grpcroute_atc.go:37]: Ditto here.

File: internal/dataplane/parser/translators/grpcroute.go (hunk 1 above)
Comment (rainest) [reply internal/dataplane/parser/translators/grpcroute.go]: Yeah, this appears to be a regression introduced with combined services/routes for some reason. The spec definitely allows total wildcard hostnames in Listeners and they're an optional field on Route types that support them, so Routes that have no hostnames should match any-hostname requests that otherwise match their rules, inclusive of the total wildcard rule. That is the normal behavior for Kong routes with no hostname.

[generateKongRoutesFromHTTPRouteRule](https://github.com/Kong/kubernetes-ingress-controller/blob/main/internal/dataplane/parser/translate_httproute.go#L211-L285) via [ingressRulesFromHTTPRouteLegacyFallback](https://github.com/Kong/kubernetes-ingress-controller/blob/6f8ae7b27f26e3b5554366d83c2a24b1a6bc1575/internal/dataplane/parser/translate_httproute.go#L159-L187) would generate any-hostname rules, as it's just collecting the list of hostnames (which may be empty) before iterating over the rules.

**Review by rainest — APPROVED** [review]
The empty hostname rule is indeed in place most of the time, although it shouldn't be. Unclear how we wound up with a mix, but it's precedent enough to not fix here if we prefer: https://github.com/Kong/kubernetes-ingress-controller/issues/4526
