### PR TITLE
fix(konnect): update nodes status only when it actually changes

### LINKED ISSUE #4322: KIC node agent reports updates nodes every 3s
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`konnect-refresh-node-period` is `60s` by default, but `NodeAgent` updates nodes on Konnect side more frequently, apparently every 3s. It's considered too often - should be max every 30s.

### Expected Behavior

When KIC runs idle in Konnect mode, it should update Konnect nodes max every 30s.

### Steps To Reproduce

```markdown
1. Run KIC with Konnect mode enabled
2. Observe it sending Node updates every 3s.
```

### Kong Ingress Controller version

```shell
v2.10.1
```

### Kubernetes version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by czeslavo**
**What this PR does / why we need it**:

Makes sure that:

- `NodeAgent` calls Konnect APIs only when the config status actually changes (enforce that on both ends of the notification channel - in `NodeAgent` and in `KongClient`). **This was an actual reason for KIC updating nodes every 3s**.
- `NodeAgent` calls Konnect APIs only when a set of Gateway clients actually changes (enforce that on `ClientsManager` side)

Also improves debug logging to make it visible when the calls are made.

After this change, `NodeAgent` will call Konnect APIs in the following cases:
- configuration status has changed,
- gateways' clients have changed (Gateway deployment scaling, Pod eviction, etc.),
- every 30s.

**Which issue this PR fixes**:

Fixes #4322.

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/konnect/node_agent_test.go [hunk 1]
```diff
@@ -437,10 +439,116 @@ func TestNodeAgent_ControllerNodeStatusGetsUpdatedOnStatusNotification(t *testin
...
+	configStatusQueue.Notify(statusTwo)
+	nodesUpdatesCountEventuallyEquals(2)
+}
+
+func TestNodeAgent_TickerResetsOnEveryNodesUpdate(t *testing.T) {
+	nodeClient := newMockNodeClient(nil)
+	configStatusQueue := newMockConfigStatusNotifier()
+	gatewayClientsChangesNotifier := newMockGatewayClientsNotifier()
+
+	ticker := mocks.NewTicker()
```
Comment (pmalek) [inline internal/konnect/node_agent_test.go:500]: 👍 for using mocked ticker

File: internal/konnect/node_agent_test.go [hunk 2]
```diff
@@ -437,10 +439,116 @@ func TestNodeAgent_ControllerNodeStatusGetsUpdatedOnStatusNotification(t *testin
...
+
+	runAgent(t, nodeAgent)
+
+	t.Run("config status notification", func(t *testing.T) {
+		// Let half of the period pass.
+		ticker.Add(halfOfRefreshPeriod)
+
+		// Trigger update with config status notification.
+		configStatusQueue.Notify(clients.ConfigStatusApplyFailed)
+		require.Eventually(t, func() bool { return nodeClient.NodesUpdatesCount() != 1 }, time.Second, time.Nanosecond)
```
Comment (pmalek) [inline internal/konnect/node_agent_test.go:523]: I'm not saying we change it here but I do see that this might cause contention on weaker (i.e. CI) machines and cause the test to fail because other CPU cores couldn't pick up work because we were in a busy loop here. `time.Microsecond` might be a better choice.

File: internal/clients/manager_test.go [hunk 3]
```diff
@@ -428,21 +460,89 @@ func TestAdminAPIClientsManager_ConcurrentNotify(t *testing.T) {
...
+		testDiscoveredAdminAPI("http://10.0.0.1:8080"),
+	}
 	for i := 0; i < 10; i++ {
+		i := i
 		go func() {
-			m.Notify([]adminapi.DiscoveredAdminAPI{
-				testDiscoveredAdminAPI("http://10.0.0.1:8080"),
-			})
+			// Notify with different clients' sets to trigger notifications as changes are required for them to happen.
+			if i%2 == 0 {
```
Comment (pmalek) [inline internal/clients/manager_test.go:470]: The mod 2 thing seems a bit magic. Can we add more comments or rewrite this a bit so that it's easier to comprehend?

File: internal/clients/manager_test.go [hunk 4]
```diff
@@ -419,7 +451,7 @@ func TestAdminAPIClientsManager_ConcurrentNotify(t *testing.T) {
 			case <-ch:
 				// Call GatewayClients() here to make sure that we can access the clients safely
 				// from the subscriber goroutine without causing a deadlock in the notify loop.
-				require.Len(t, m.GatewayClients(), 1, "expected to get 1 client")
```
Comment (pmalek) [inline internal/clients/manager_test.go:422]: Why remove the assertion?

**Review by pmalek — COMMENTED** [review]
👍 Some minor comments to consider

File: internal/clients/manager_test.go (hunk 3 above)
Comment (czeslavo) [reply internal/clients/manager_test.go]: Yeah, I rewrote it so maybe now it's more direct - we have two sets of clients: odd and even, and we use them interchangeably to cause an actual change that will trigger a notification. PTAL

**Review by pmalek — APPROVED** [review]

**Comment by pmalek** [comment]
I believe the milestone should be set to v2.11, right?
