### PR TITLE
fix: do not translate licenses if Kong gateway is not enterprise edition

### LINKED ISSUE #5638: When configuring Kong Gateway OSS, KIC tries to apply KongLicense regardless and fails
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to apply a license to Kong Gateway OSS (i.e. `kong` repository: https://hub.docker.com/_/kong) KIC will try to apply the license regardless and will fail in doing so without a clear error message.

### Expected Behavior

When trying to apply EE license to Kong OSS KIC should be able to detect that this is the case and emit an error, letting the user know that this is an error.

### Steps To Reproduce

```markdown
1. Deploy KIC + Kong Gateway OSS
2. Apply the following exemplar license

    
    apiVersion: configuration.konghq.com/v1alpha1
    enabled: true
    kind: KongLicense
    metadata:
      name: kong-license
    rawLicenseString: dummy
    ```

3. Observe the following logs in KIC: (pretty printed)

    ```
    │ 2024-02-19T12:40:50Z    error    Failed parsing resource errors    
    {
      "url": "https://10-244-0-12.dataplane-admin-gw-2rz65-7fpfd-xj4xm.bdd98a86-c24e-4c61-8ad4-3e7d26313da1.svc:8444",
      "update_strategy": "InMemory",
      "error": "could not unmarshal config error: json: cannot unmarshal object into Go struct field ConfigError.flattened_errors of type []sendconfig.FlatEntityError"
    }                                                                                                                                                                                           
    ```

    The response as returned by the Gateway is

    ```
    {
      "code": 14,
      "fields": {
        "error": "failed parsing declarative configuration: expected an object"
      },
      "message": "declarative config is invalid: {error=\"failed parsing declarative configuration: expected an object\"}",
      "name": "invalid declarative configuration"
    }
    ```
```

### Proposed solution

KIC could potentially utilize `.version` and/or `.edition` returned by Admin API's `/config`.

The former is set to either `community` or `enterprise`. The latter will have either 3 or 4 segments which can be parsed using https://github.com/kong/semver which will tell if the version if EE or OSS.


### Kong Ingress Controller version

```shell
3.1.0
```

### Kubernetes version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

Add an `EnterpriseEdition` feature flag in translator and disable the translation of licenses if `EnterpriseEdition` is not enabled. 

**Which issue this PR fixes**:

fixes #5638 

**Special notes for your reviewer**:

- Since we added the `EnterpriseEdition` flag, we can actually do more things on translation of "enterprise only" Kong configurations (like consumergroups). Should we do this in later PRs?
- Since Kong 3.6, an `edition` field is added in the response of root endpoint. Should we implement a dedicated function to fetch this field (and fall back to judge by version if the field does not present)?

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/manager/run.go [hunk 1]
```diff
@@ -172,6 +172,7 @@ func Run(
 		featureGates,
 		routerFlavor,
 		c.UpdateStatus,
+		kongStartUpConfig.Version.IsKongGatewayEnterprise(),
```
Comment (pmalek) [inline internal/manager/run.go:175]: This will suffer for the same reasons router flavor suffers: it's being taken from the initial configuration and we assume it won't change.

While router flavor has implications such that the generated configs might break this will potentially try to configure enterprise features/entities (currently only licenses) even after a change from EE to OSS has been made (or the other way around: users won't get EE features until they restart KIC).

There is no easy fix that I can see for this as of now unless we make translators be aware of each Kong instance's config and create those dynamically. This would be a nice UX improvement but might require some non-insignificant effort.

cc: @mheap

**Review by pmalek — APPROVED** [review]

File: internal/manager/run.go (hunk 1 above)
Comment (randmonkey) [reply internal/manager/run.go:175]: Heterogeneous Kong gateways!! This is a big feature which could bring up better UX and less downtime. Maybe also required by KGO.

Comment (czeslavo) [reply internal/manager/run.go:175]: Linking https://github.com/Kong/kubernetes-ingress-controller/issues/3590 for reference.

**Review by pmalek — APPROVED** [review]

**Review by czeslavo — DISMISSED** [review]

File: internal/dataplane/translator/translator.go [hunk 2]
```diff
@@ -51,6 +51,9 @@ type FeatureFlags struct {
 	// ExpressionRoutes indicates whether to translate Kubernetes objects to expression based Kong Routes.
 	ExpressionRoutes bool
 
+	// EnterpriseEdition indicates whether to translate objects that are only available in Kong enterpreise edition.
```
Comment (tao12345666333) [inline internal/dataplane/translator/translator.go:54]:
```suggestion
	// EnterpriseEdition indicates whether to translate objects that are only available in the Kong enterprise edition.
```

**Review by tao12345666333 — APPROVED** [review]
