### PR TITLE
fix: do not set `instance_name` of plugin if Kong version is below 3.2.0

### LINKED ISSUE #5241: `InstanceName` of plugins produces unknown field error in Kong 2.8.x
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When `InstanceName` is specified in `KongPlugin` or `KongClusterPlugin`, the error happens when sending configuration to Kong 2.8.x 
```
 {"name":"invalid declarative configuration","fields":{"plugins":[{"instance_name":"unknown field"}]},"code":14,"message":"declarative config is invalid: {plugins={{instance_name=\"unknown field\"}}}"}
```
This makes Kong gateway stuck on updating configuration.

### Expected Behavior

Valid configuration of plugins (without `instance_name` field) sent to Kong when Kong version is below 3.2.0. 
Ref: 
https://docs.konghq.com/gateway/2.8.x/admin-api/#plugin-object 
https://docs.konghq.com/gateway/3.1.x/admin-api/#plugin-object
https://docs.konghq.com/gateway/3.2.x/admin-api/#plugin-object
The `instance_name` field is first added in Kong 3.2.x.

### Steps To Reproduce

```markdown
1. Create a KongPlugin foo with field InstanceName
2. Create an Ingress referencing this plugin by adding annotation konghq.com/plugins: "foo"
```

### Kong Ingress Controller version

```shell
2.12.2
```

### Kubernetes version

```shell
1.28.0 kind cluster
```

### Anything else?

This does not affect KIC 3.0.x because KIC 3.x only support Kong 3.4.1 and above.

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

Kong added `instance_name` field first in 3.2.0: https://docs.konghq.com/gateway/3.2.x/admin-api/#plugin-object. If Kong version is below 3.2.0, we should not set `instance_name` field to prevent "unknown field" error.

**Which issue this PR fixes**:

Fixes #5241 

**Special notes for your reviewer**:

~Added `KongVersion` in `KongState` structure. This requires setting `KongVersion` every where when `KongState` is used because this field cannot be left empty. Please check if there are any missing places.~ reverted the change after update.
**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR
REVIEW: I did not see CHANGELOG of 2.12.1/2.12.2 in the `release/2.12.x` branch. When do we update the changelog?

### CODE REVIEW

File: internal/dataplane/kongstate/util.go [hunk 1]
```diff
@@ -193,15 +199,16 @@ func kongPluginFromK8SPlugin(
...
+			Name:         k8sPlugin.PluginName,
+			Config:       config,
 			RunOn:        k8sPlugin.RunOn,
 			Ordering:     k8sPlugin.Ordering,
 			InstanceName: k8sPlugin.InstanceName,
 			Disabled:     k8sPlugin.Disabled,
 			Protocols:    protocolsToStrings(k8sPlugin.Protocols),
 			Tags:         util.GenerateTagsForObject(&k8sPlugin),
+
+			KongVersion: kongVersion,
```
Comment (czeslavo) [inline internal/dataplane/kongstate/util.go:211]:
```suggestion
```
How about keeping the version out of `KongState` struct (to keep it clean from feature flags/versions, etc., and leave it just for storing raw generated entities) and just passing the version to `Plugin.toKongPlugin` (propagating from `KongState.FillPlugins`? This way we could avoid e.g. filling this in `ConfigFetcher`.

File: internal/dataplane/configfetcher/config_fetcher.go [hunk 2]
```diff
@@ -83,10 +84,18 @@ func (cf *DefaultKongLastGoodConfigFetcher) TryFetchingValidConfigFromGateways(
...
-		if status.ConfigurationHash != sendconfig.WellKnownInitialHash {
+		var kongVersion semver.Version
+		kongVersionStr, getVersionErr := client.GetKongVersion(ctx)
+		if getVersionErr != nil {
+			errs = errors.Join(errs, fmt.Errorf("failed to fetch configuration from %q, cannot get Kong version: %w", client.BaseRootURL(), getVersionErr))
+			continue
+		}
+		kongVersion, getVersionErr = semver.Parse(kongVersionStr)
+
+		if status.ConfigurationHash != sendconfig.WellKnownInitialHash && getVersionErr == nil {
```
Comment (mlavacca) [inline internal/dataplane/configfetcher/config_fetcher.go:95]: I know it is very unlikely to happen but to make it bulletproof I think we should check the error first and append it to errs if `!= nil`.

File: internal/dataplane/kongstate/kongstate_test.go [hunk 3]
```diff
@@ -788,6 +790,7 @@ func TestKongState_BuildPluginsCollisions(t *testing.T) {
 	for _, tt := range []struct {
 		name       string
 		in         []*kongv1.KongPlugin
+		kv         semver.Version
```
Comment (mlavacca) [inline internal/dataplane/kongstate/kongstate_test.go:793]: can we rename it to `kongVersion`? I imagine other people in the future struggling to understand what `kv` is 😄

File: internal/dataplane/configfetcher/kongrawstate.go [hunk 4]
```diff
@@ -12,8 +13,10 @@ import (
 // -----------------------------------------------------------------------------
 
 // KongRawStateToKongState converts a Deck kongRawState to a KIC KongState.
-func KongRawStateToKongState(rawstate *utils.KongRawState) *kongstate.KongState {
-	kongState := &kongstate.KongState{}
+func KongRawStateToKongState(rawstate *utils.KongRawState, kongVersion semver.Version) *kongstate.KongState {
+	kongState := &kongstate.KongState{
+		KongVersion: kongVersion,
```
Comment (mlavacca) [inline internal/dataplane/configfetcher/kongrawstate.go:18]: Do you know when setting this field has become mandatory? Asking out of curiosity

File: internal/dataplane/kongstate/kongstate.go [hunk 5]
```diff
@@ -337,20 +342,20 @@ func buildPlugins(
...
 		if k8sClusterPlugin != nil {
-			plugin, err = kongPluginFromK8SClusterPlugin(s, *k8sClusterPlugin)
+			plugin, err = kongPluginFromK8SClusterPlugin(s, *k8sClusterPlugin, kongVersion)
 			if err != nil {
 				failuresCollector.PushResourceFailure(err.Error(), k8sClusterPlugin)
 				continue
 			}
 		}
-
+		// REVIEW: skip this step if Kong version < 3.2.0?
```
[the remark this answers is not in the document]
Comment (randmonkey) [reply internal/dataplane/kongstate/kongstate.go]: done.

File: internal/dataplane/configfetcher/config_fetcher.go (hunk 2 above)
Comment (randmonkey) [reply internal/dataplane/configfetcher/config_fetcher.go]: removed this part because we do not need `KongVersion` in struct of `KongState`.

File: internal/dataplane/kongstate/kongstate_test.go (hunk 3 above)
Comment (randmonkey) [reply internal/dataplane/kongstate/kongstate_test.go]: done.

**Review by czeslavo — APPROVED** [review]

**Review by mlavacca — APPROVED** [review]
