### PR TITLE
fix: filter hostnames in HTTPRoute

### LINKED ISSUE #3175: Routes incorrectly use hostname from Listener
Stub bug report that needs further investigation and proper replication steps. Briefly, the route generated from this HTTPRoute should not have the `tls9443.kong.example` hostname, as that's not in its rules. It's somehow coming from an unrelated TLS Listen in the Gateway. Found in 2.7, need to validate if it's still happening for the current nightlies.

```
    {
      "response_buffering": true,
      "hosts": [
        "tls9443.kong.example"
      ],
      "regex_priority": 0,
      "https_redirect_status_code": 426,
      "preserve_host": true,
      "path_handling": "v0",
      "headers": null,
      "created_at": 1668542620,
      "updated_at": 1668542620,
      "strip_path": true,
      "id": "df37c9f6-49a0-5ba9-bac7-932dc09786ce",
      "snis": null,
      "paths": [
        "/echo"
      ],
      "service": {
        "id": "f998693d-c386-5bbf-aea2-aeae52bced58"
      },
      "sources": null,
      "destinations": null,
      "tags": null,
      "methods": null,
      "name": "httproute.default.echo.0.0",
      "protocols": [
        "http",
        "https"
      ],
      "request_buffering": true
    },
```
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  annotations:
    konghq.com/strip-path: "true"
  creationTimestamp: "2022-11-11T20:13:31Z"
  generation: 11
  name: echo
  namespace: default
  resourceVersion: "199603"
  uid: 7519c73c-7522-4989-9dd7-d8526c17a5c3
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: kong
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: echo
      port: 80
      weight: 200
    - group: ""
      kind: Service
      name: echo2
      port: 80
      weight: 100
    matches:
    - path:
        type: PathPrefix
        value: /echo
```

```
apiVersion: v1                                   
items:
- apiVersion: gateway.networking.k8s.io/v1beta1
  kind: Gateway
  metadata:
    annotations:
      konghq.com/gatewayclass-unmanaged: kong/kong-proxy
    creationTimestamp: "2022-11-11T19:01:48Z"
    generation: 15
    name: kong
    namespace: default
    resourceVersion: "199586"
    uid: 072e882e-0e34-4d0b-9fe9-50c458863303
  spec:
    addresses:
    - type: IPAddress
      value: 192.168.96.0
    gatewayClassName: kong
    listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      name: http
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: Same
      name: tcp
      port: 8888
      protocol: TCP
    - allowedRoutes:
        namespaces:
          from: Same
      name: stream9000
      port: 9000
      protocol: TCP
    - allowedRoutes:
        namespaces:
          from: Same
      hostname: tls9443.kong.example
      name: stream9443
      port: 9443
      protocol: TLS
```

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

- Does not filter hostnames when `HTTPRoute` contains empty `spec.hostnames`, and any of compatible listeners does not specify `hostname`
- When no hostnames in `HTTPRoute` could match hostnames in listners, do not accept this `HTTPRoute`: https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRoute

**Which issue this PR fixes**:

fixes #3175 

**Special notes for your reviewer**:

According to API specification of gateway APIs, what should do when `HTTPRoute` does not contain `hostnames`
 but listeners contains `hostname` is not defined. I think the most reasonable behavior is to match the hostname specified by the listener which the `HTTPRoute` attached to. When an `HTTPRoute` is not attached to a listener (has empty `parentRef.SectionName`), I think the reasonable behavior is to match **UNION** of all (compatible) listeners in the gateway. If any of the `HTTP`,`HTTPS`,`TLS` listeners has an empty hostname to match any hostname, the hostname in `HTTPRoute` should be also empty to match any hostname.

Also, gateway API spec tells that when no hostname in `HTTPRoute` can match hostnames in listeners, the `HTTPRoute` should not be accepted.

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [X] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/controllers/gateway/httproute_controller.go [hunk 1]
```diff
@@ -585,3 +600,101 @@ func (r *HTTPRouteReconciler) getHTTPRouteRuleReason(ctx context.Context, httpRo
...
+	// no need to update if no status is changed.
+	return false, nil
+}
+
+// updateAcceptedConditionInRouteParentStatus updates conditions with type "Accepted" in parentStatus.
+// returns true if the parentStatus modified.
+func updateAcceptedConditionInRouteParentStatus(
+	parentStatus *gatewayv1beta1.RouteParentStatus,
+	conditionStatus metav1.ConditionStatus,
+	conditionReason string,
```
Comment (pmalek) [inline internal/controllers/gateway/httproute_controller.go:679]: Can we use `gatewayv1beta1.RouteConditionReason` for this argument? It will avoid us make a type cast in e.g. `internal/controllers/gateway/httproute_controller.go:331` and make this more type safe ( no accidental usage of message in place of reason because they are the same type ). WDYT?

```suggestion
	conditionReason gatewayv1beta1.RouteConditionReason,
```

File: internal/controllers/gateway/httproute_controller.go [hunk 2]
```diff
@@ -585,3 +600,101 @@ func (r *HTTPRouteReconciler) getHTTPRouteRuleReason(ctx context.Context, httpRo
...
+			return false, err
+		}
+		return true, nil
+	}
+	// no need to update if no status is changed.
+	return false, nil
+}
+
+// updateAcceptedConditionInRouteParentStatus updates conditions with type "Accepted" in parentStatus.
+// returns true if the parentStatus modified.
```
Comment (pmalek) [inline internal/controllers/gateway/httproute_controller.go:675]:
```suggestion
// updateAcceptedConditionInRouteParentStatus updates conditions with type "Accepted" in parentStatus.
// returns true if the parentStatus was modified.
```

File: internal/controllers/gateway/httproute_controller.go [hunk 3]
```diff
@@ -585,3 +600,101 @@ func (r *HTTPRouteReconciler) getHTTPRouteRuleReason(ctx context.Context, httpRo
 	}
 	return gatewayv1beta1.RouteReasonResolvedRefs, nil
 }
+
+// ensureParentsAcceptedCondition sets the "Accepted" condition of HTTPRoute status.
```
Comment (pmalek) [inline internal/controllers/gateway/httproute_controller.go:604]: Perhaps mention what are the return values?

File: internal/controllers/gateway/httproute_controller.go [hunk 4]
```diff
@@ -585,3 +600,101 @@ func (r *HTTPRouteReconciler) getHTTPRouteRuleReason(ctx context.Context, httpRo
...
+func (r *HTTPRouteReconciler) ensureParentsAcceptedCondition(
+	ctx context.Context,
+	httproute *gatewayv1beta1.HTTPRoute,
+	gateways []supportedGatewayWithCondition,
+	conditionStatus metav1.ConditionStatus,
+	conditionReason string,
```
Comment (pmalek) [inline internal/controllers/gateway/httproute_controller.go:610]: ditto about the type:

```suggestion
	conditionReason gatewayv1beta1.RouteConditionReason,
```

File: internal/controllers/gateway/httproute_controller.go [hunk 5]
```diff
@@ -585,3 +600,101 @@ func (r *HTTPRouteReconciler) getHTTPRouteRuleReason(ctx context.Context, httpRo
...
+		if existingParent.ParentRef.Namespace != nil {
+			namespace = string(*existingParent.ParentRef.Namespace)
+		}
+		existingParentCopy := existingParent
+		var sectionName string
+		if existingParent.ParentRef.SectionName != nil {
+			sectionName = string(*existingParent.ParentRef.SectionName)
+		}
+		parentStatuses[fmt.Sprintf("%s/%s/%s", namespace, existingParent.ParentRef.Name, sectionName)] = &existingParentCopy
+	}
```
Comment (pmalek) [inline internal/controllers/gateway/httproute_controller.go:626]: Since this is pretty much a copy paste of https://github.com/Kong/kubernetes-ingress-controller/blob/04f4d3b882a3f32402c9d3a7887ce2ba50c38e3f/internal/controllers/gateway/httproute_controller.go#L379-L392 how about we make this a function that accepts e.g. 
 `[]RouteParentStatus` and returns the parent statuses? We can then document it and perhaps add some unit tests for it. WDYT?

File: internal/controllers/gateway/httproute_controller.go [hunk 6]
```diff
@@ -585,3 +600,101 @@ func (r *HTTPRouteReconciler) getHTTPRouteRuleReason(ctx context.Context, httpRo
...
+			changed := updateAcceptedConditionInRouteParentStatus(parentStatus, conditionStatus, conditionReason, conditionMessage, httproute.Generation)
+			statusChanged = statusChanged || changed
+		} else {
+			// add a new parent if the parent is not found in status.
+			newParentStatus := &gatewayv1beta1.RouteParentStatus{
+				ParentRef: gatewayv1beta1.ParentReference{
+					Namespace:   (*gatewayv1beta1.Namespace)(pointer.String(gateway.Namespace)),
+					Name:        gatewayv1beta1.ObjectName(gateway.Name),
+					SectionName: (*gatewayv1beta1.SectionName)(pointer.String(g.listenerName)),
+					// TODO: set port.
```
Comment (pmalek) [inline internal/controllers/gateway/httproute_controller.go:644]: Is this meant to be done in this PR? If not then let's create a tracking issue and link it here.

File: internal/controllers/gateway/httproute_controller.go [hunk 7]
```diff
@@ -318,8 +318,23 @@ func (r *HTTPRouteReconciler) Reconcile(ctx context.Context, req ctrl.Request) (
...
 	// perform operations on the kong store only if the route is in accepted status
 	if isRouteAccepted(gateways) {
-		// remove all the hostnames that don't match with at least one Listener's Hostname
-		filteredHTTPRoute := filterHostnames(gateways, httproute.DeepCopy())
+		// if there is no matched hosts in listeners for the httproute, the httproute should not be accepted
+		// and have an "Accepted" condition with status false.
+		// https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRoute
+		filteredHTTPRoute, err := filterHostnames(gateways, httproute.DeepCopy())
+		if err != nil {
+			debug(log, httproute, "no matching hostnames after filtering, should not accept")
```
Comment (pmalek) [inline internal/controllers/gateway/httproute_controller.go:326]:
```suggestion
			debug(log, httproute, "not accepting a route: no matching hostnames found after filtering")
```

File: internal/controllers/gateway/route_utils.go [hunk 8]
```diff
@@ -313,20 +318,34 @@ func listenerHostnameIntersectWithRouteHostnames[H types.HostnameT, L types.List
 	return false
 }
 
+// isListenterHostnameEffective if the listener could specify an effective hostname to match hostnames in requests.
+// it will return true when the protocol of listener is HTTP, HTTPS, or TLS.
```
Comment (pmalek) [inline internal/controllers/gateway/route_utils.go:322]:
```suggestion
// isListenterHostnameEffective returns true if the listener can specify an effective
// hostname to match hostnames in requests.
// It basically checks if the listener is using any these protocols: HTTP, HTTPS, or TLS.
```

File: internal/controllers/gateway/route_utils.go [hunk 9]
```diff
@@ -313,20 +318,34 @@ func listenerHostnameIntersectWithRouteHostnames[H types.HostnameT, L types.List
...
-				if listenerName := gateway.listenerName; listenerName == "" || listenerName == string(listener.Name) {
-					if listener.Hostname != nil {
-						filteredHostnames = append(filteredHostnames, (*listener.Hostname))
+				listenerName := gateway.listenerName
+				if (listenerName == "" || listenerName == string(listener.Name)) &&
+					isListenerHostnameEffective(listener) {
+					// httpRoute remains an empty hostname if any of the listeners
+					// has not specified hostname to match any host.
+					if listener.Hostname == nil {
+						return httpRoute, nil
```
Comment (pmalek) [inline internal/controllers/gateway/route_utils.go:346]: I don't understand why do we want to return here. There's still more listeners and gateways to look it, is it not?

File: internal/controllers/gateway/route_utils.go [hunk 10]
```diff
@@ -313,20 +318,34 @@ func listenerHostnameIntersectWithRouteHostnames[H types.HostnameT, L types.List
...
 
 	// if no hostnames are specified in the route spec, get all the hostnames from
 	// the gateway
 	if len(httpRoute.Spec.Hostnames) == 0 {
 		for _, gateway := range gateways {
 			for _, listener := range gateway.gateway.Spec.Listeners {
-				if listenerName := gateway.listenerName; listenerName == "" || listenerName == string(listener.Name) {
-					if listener.Hostname != nil {
-						filteredHostnames = append(filteredHostnames, (*listener.Hostname))
+				listenerName := gateway.listenerName
```
Comment (pmalek) [inline internal/controllers/gateway/route_utils.go:340]: This can be moved up out of this for loop as each `supportedGatewayWithCondition` has only 1 `listenerName`

File: CHANGELOG.md [hunk 11]
```diff
@@ -180,6 +180,13 @@ Adding a new version? You'll need three changes:
 - Admin and proxy listens in the deploy manifests now use the same parameters
   as the default upstream kong.conf.
   [#3165](https://github.com/Kong/kubernetes-ingress-controller/pull/3165)
+- Fix the behavior of filtering hostnames in `HTTPRoute` when listeners 
+  of parent gateways specified hostname. Now if an `HTTPRoute` does not 
+  specify hostnames, and one of its parent listeners has not specified
+  hostname, the hostnames will not be filtered in `HTTPRoute`.
```
Comment (pmalek) [inline CHANGELOG.md:186]: Is there any chance we use a different wording for this? It's feel way to complicated for me and I'm having a hard time understanding what it really means.

As for the use of word filtered: I'm not a huge fan because it's awfully ambiguous (at least for me). Are we filtering in (retaining) or filtering out (removing) the hostnames?

File: internal/controllers/gateway/httproute_controller.go (hunk 6 above)
Comment (randmonkey) [reply internal/controllers/gateway/httproute_controller.go:644]: I think it should be depending on issue https://github.com/Kong/kubernetes-ingress-controller/issues/3016 for gateway port matching.

File: internal/controllers/gateway/route_utils.go (hunk 10 above)
Comment (randmonkey) [reply internal/controllers/gateway/route_utils.go:340]: I think we can implement a function `extractListenerFromGateway` to extract the listener from gateway.

File: internal/controllers/gateway/route_utils.go (hunk 9 above)
Comment (randmonkey) [reply internal/controllers/gateway/route_utils.go:346]: In this branch, `hostnames` in `HTTPRoute` is empty to specify that the `HTTPRoute` could match any hostname. So, if any listeners could be attached to this `HTTPRoute` has an empty hostname, that could also match any hostname, the final result of hostname match should be match any hostname. If we finally got a listener with a non-empty hostname, a hostname will be included in the `HTTPRoute`, so that the `HTTPRoute` will be only match certain hostnames, and this is not expected: #3175

File: internal/controllers/gateway/httproute_controller.go (hunk 5 above)
Comment (randmonkey) [reply internal/controllers/gateway/httproute_controller.go:626]: I also found such code in processing other routes. So the function could be also adopted to other kind of routes. Because of the affect on all kinds of route, I think it is better to be done in another PR.

File: internal/controllers/gateway/httproute_controller.go (hunk 1 above)
Comment (randmonkey) [reply internal/controllers/gateway/httproute_controller.go]: done

File: internal/controllers/gateway/httproute_controller.go (hunk 4 above)
Comment (randmonkey) [reply internal/controllers/gateway/httproute_controller.go]: done

File: internal/controllers/gateway/httproute_controller.go (hunk 2 above)
Comment (randmonkey) [reply internal/controllers/gateway/httproute_controller.go]: done

File: internal/controllers/gateway/httproute_controller.go (hunk 7 above)
Comment (randmonkey) [reply internal/controllers/gateway/httproute_controller.go]: done

File: internal/controllers/gateway/route_utils.go (hunk 8 above)
Comment (randmonkey) [reply internal/controllers/gateway/route_utils.go]: done/

File: CHANGELOG.md (hunk 11 above)
Comment (randmonkey) [reply CHANGELOG.md]: Updated. Hope the new version could be easier to understand.

File: internal/controllers/gateway/httproute_controller.go (hunk 5 above)
Comment (pmalek) [reply internal/controllers/gateway/httproute_controller.go:628]: Can we make a tracking issue for this so that we do not forget about this?

File: internal/controllers/gateway/route_utils.go [hunk 12]
```diff
@@ -458,33 +467,74 @@ func listenerHostnameIntersectWithRouteHostnames[H types.HostnameT, L types.List
...
+		if gateway.listenerName != "" {
+			if listener := extractListenerSpecFromGateway(
+				gateway.gateway,
+				gatewayv1beta1.SectionName(gateway.listenerName),
+			); listener != nil {
+				// return true if the listener has not specified hostname to match any hostname.
+				if listener.Hostname == nil {
+					return nil, true
+				}
+				hostnames = append(hostnames, (*listener.Hostname))
```
Comment (pmalek) [inline internal/controllers/gateway/route_utils.go:523]:
```suggestion
				hostnames = append(hostnames, *listener.Hostname)
```

File: internal/controllers/gateway/route_utils.go [hunk 13]
```diff
@@ -458,33 +467,74 @@ func listenerHostnameIntersectWithRouteHostnames[H types.HostnameT, L types.List
...
+			}
+		} else {
+			for _, listener := range gateway.gateway.Spec.Listeners {
+				// REVIEW: which listeners should we take into consideration here if no listener in supported gateways?
+				if isListenerHostnameEffective(listener) {
+					if listener.Hostname == nil {
+						return nil, true
+					}
+					hostnames = append(hostnames, (*listener.Hostname))
```
Comment (pmalek) [inline internal/controllers/gateway/route_utils.go:532]:
```suggestion
					hostnames = append(hostnames, *listener.Hostname)
```

File: test/integration/httproute_test.go [hunk 14]
```diff
@@ -494,3 +494,162 @@ func TestHTTPRouteMultipleServices(t *testing.T) {
...
+				},
+				BackendRefs: []gatewayv1beta1.HTTPBackendRef{{
+					BackendRef: gatewayv1beta1.BackendRef{
+						BackendObjectReference: gatewayv1beta1.BackendObjectReference{
+							Name: gatewayv1beta1.ObjectName(service.Name),
+							Port: &httpPort,
+							Kind: util.StringToGatewayAPIKindPtr("Service"),
+						},
+					},
+				}},
```
Comment (pmalek) [inline test/integration/httproute_test.go:581]: You could use https://github.com/Kong/kubernetes-ingress-controller/blob/cfed6a601fba013fd9135e55cb0153c2eeaed70a/internal/util/builder/httpbackendref.go#L13-L15 to make this more succinct

File: internal/controllers/gateway/route_utils.go [hunk 15]
```diff
@@ -82,6 +84,13 @@ const (
 	// https://github.com/kubernetes-sigs/gateway-api/pull/1516
 	// TODO: swap this out with upstream const when released.
 	RouteReasonNoMatchingParent gatewayv1beta1.RouteConditionReason = "NoMatchingParent"
+	// This reason is used with the "Accepted" condition when the Gateway has no
+	// compatible Listeners whose Port matches the route
+	// NOTE: This should probably be proposed upstream.
+	RouteReasonNoMatchingListenerPort gatewayv1beta1.RouteConditionReason = "NoMatchingListenerPort"
```
Comment (pmalek) [inline internal/controllers/gateway/route_utils.go:90]: Shouldn't we use `RouteReasonNoMatchingParent` (defined above) in this case? How does that differ from `RouteReasonNoMatchingParent`?

File: internal/controllers/gateway/route_utils.go (hunk 12 above)
Comment (randmonkey) [reply internal/controllers/gateway/route_utils.go]: done

File: internal/controllers/gateway/route_utils.go (hunk 13 above)
Comment (randmonkey) [reply internal/controllers/gateway/route_utils.go]: done

File: test/integration/httproute_test.go (hunk 14 above)
Comment (randmonkey) [reply test/integration/httproute_test.go]: done

File: test/integration/httproute_test.go [hunk 16]
```diff
@@ -494,3 +494,162 @@ func TestHTTPRouteMultipleServices(t *testing.T) {
...
+			},
+			Rules: []gatewayv1beta1.HTTPRouteRule{{
+				Matches: []gatewayv1beta1.HTTPRouteMatch{
+					{
+						Path: &gatewayv1beta1.HTTPPathMatch{
+							Type:  &pathMatchPrefix,
+							Value: kong.String("/test-http-route-filter-hosts"),
+						},
+					},
+				},
```
[the remark this answers is not in the document]
Comment (randmonkey) [reply test/integration/httproute_test.go]: done

File: internal/controllers/gateway/route_utils.go (hunk 15 above)
Comment (pmalek) [reply internal/controllers/gateway/route_utils.go:90]: It's not in `main` 😅 

> I think I did not add it

Github says you did :) 

https://github.com/Kong/kubernetes-ingress-controller/commit/510a8ef4c027860760d419008d7f0325ad120984#diff-538cabd873585a7f0cfe12f019e7b14b1945cb5c346265e4f73a026fcb166688R89-R95

All in all: if there are no references to this then let's delete it.

File: internal/controllers/gateway/httproute_controller.go (hunk 5 above)
Comment (randmonkey) [reply internal/controllers/gateway/httproute_controller.go:628]: OK, #3195

File: internal/controllers/gateway/route_utils.go (hunk 15 above)
Comment (randmonkey) [reply internal/controllers/gateway/route_utils.go]: Removed it now.
It seems that there was a conflict after #3181 merged, and that PR removed `RouteReasonNoMatchingListenerPort`, but I resolved the conflict by accepting both changes.

File: internal/controllers/gateway/route_utils.go [hunk 17]
```diff
@@ -458,33 +463,74 @@ func listenerHostnameIntersectWithRouteHostnames[H types.HostnameT, L types.List
...
+			); listener != nil {
+				// return true if the listener has not specified hostname to match any hostname.
+				if listener.Hostname == nil {
+					return nil, true
+				}
+				hostnames = append(hostnames, *listener.Hostname)
+			}
+		} else {
+			for _, listener := range gateway.gateway.Spec.Listeners {
+				// REVIEW: which listeners should we take into consideration here if no listener in supported gateways?
```
Comment (pmalek) [inline internal/controllers/gateway/route_utils.go:523]: I would prefer us not to leave this here (which I believe was the intention behind this comment anyway) and to validate this assumption with Gateway API maintainers.

What would you say about creating an issue or discussion in https://github.com/kubernetes-sigs/gateway-api/ so that we can get a clear guidance on this (and also help the community members that might also struggle with this one)?

File: internal/controllers/gateway/route_utils.go [hunk 18]
```diff
@@ -82,6 +84,9 @@ const (
 	// https://github.com/kubernetes-sigs/gateway-api/pull/1516
 	// TODO: swap this out with upstream const when released.
 	RouteReasonNoMatchingParent gatewayv1beta1.RouteConditionReason = "NoMatchingParent"
+	// This reason is used with the "Accepted" condition when no hostnames in listeners
+	// could match hostname in the spec of route.
+	RouteReasonNoMatchingListenerHostname gatewayv1beta1.RouteConditionReason = "NoMatchingListenerHostname"
```
Comment (pmalek) [inline internal/controllers/gateway/route_utils.go:89]: You might also consider proposing this upstream. This will either guide us into reusing `RouteReasonNoMatchingParent` (and perhaps extending the comment on it) or pushing this change upstream and reusing their `const` - when released). Similarly to what happened to `RouteReasonNoMatchingParent` https://github.com/kubernetes-sigs/gateway-api/pull/1516

Comment (randmonkey) [reply internal/controllers/gateway/route_utils.go:89]: Added issue: https://github.com/kubernetes-sigs/gateway-api/issues/1561. Waiting for more discussions and PRs. What should be done on this PR before the upstream issue resolved? I do not think leaving this PR open until related upstream issues and discussions resolves would be the best choice.

Comment (pmalek) [reply internal/controllers/gateway/route_utils.go:89]: I believe we can reference this (issue link) in comment, stating that this might change given the feedback we receive from the community. I am personally not convinced we need a separate reason for this ( I think `RouteReasonNoMatchingParent` would work as well in here) but let's wait for feedback from community.

File: internal/controllers/gateway/route_utils.go (hunk 17 above)
Comment (randmonkey) [reply internal/controllers/gateway/route_utils.go:523]: Added discussion: https://github.com/kubernetes-sigs/gateway-api/discussions/1563.
Which listeners should we consider here before the discussion finally have a conclusion? I want to keep the implementation here. Because I think considering `TCP` or `UDP` listeners that are not able to specify a hostname is meaningless. And all the listeners that are able to specify a hostname should be condisered.

Comment (randmonkey) [reply internal/controllers/gateway/route_utils.go]: added comments.

File: internal/controllers/gateway/route_utils.go (hunk 18 above)
Comment (randmonkey) [reply internal/controllers/gateway/route_utils.go]: added comments.

File: internal/controllers/gateway/route_utils.go [hunk 19]
```diff
@@ -458,33 +466,76 @@ func listenerHostnameIntersectWithRouteHostnames[H types.HostnameT, L types.List
 	return false
 }
 
+// isListenterHostnameEffective returns true if the listener can specify an effective
```
Comment (pmalek) [inline internal/controllers/gateway/route_utils.go:469]:
```suggestion
// isListenerHostnameEffective returns true if the listener can specify an effective
```

File: internal/controllers/gateway/route_utils.go [hunk 20]
```diff
@@ -82,6 +84,12 @@ const (
 	// https://github.com/kubernetes-sigs/gateway-api/pull/1516
 	// TODO: swap this out with upstream const when released.
 	RouteReasonNoMatchingParent gatewayv1beta1.RouteConditionReason = "NoMatchingParent"
+	// This reason is used with the "Accepted" condition when no hostnames in listeners
+	// could match hostname in the spec of route.
+	// NOTE: This is not in upstream and still under discussion:
+	// https://github.com/kubernetes-sigs/gateway-api/issues/1561
+	// may be changed if upstream decide to use a different reason for this case.
+	RouteReasonNoMatchingListenerHostname gatewayv1beta1.RouteConditionReason = "NoMatchingListenerHostname"
```
Comment (pmalek) [inline internal/controllers/gateway/route_utils.go:92]: Since we've discovered that [it's already available upstream](https://github.com/kubernetes-sigs/gateway-api/blob/v0.5.1/apis/v1beta1/shared_types.go#L216-L218), why not use it here?

Comment (randmonkey) [reply internal/controllers/gateway/route_utils.go]: updated.

File: internal/controllers/gateway/route_utils.go (hunk 19 above)
Comment (randmonkey) [reply internal/controllers/gateway/route_utils.go]: fixed.

**Review by pmalek — APPROVED** [review]
