### PR TITLE
fix: do not prepend ~ before regex paths for Kong < 3.0

### LINKED ISSUE #4237: GRPCRoute is translated to invalid Kong config in Kong 2.x
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I create a `GRPCRoute` with Kong 2.8.x (For example, run integration test `TestGRPCRoute*` against Kong 2.8.x.x images),   applying config always gets `400` response. This is because the parser translate `method` in matches of `GRPCRoute`s to paths starting with `~` in `paths` in Kong routes. Kong versions prior to 3.0 could not recognize the paths starting with `~`, so it will always return 400 for the configs.

### Expected Behavior

When I create a `GRPCRoute`, it should be translated to correct Kong configurations (services/routes/upstreams/...) with Kong 2.x.

### Steps To Reproduce

```markdown
1. Run KIC with Kong 2.8, and GatewayAlpha feature gate turned on (image kong/kong-gateway:2.8)
2. create a GRPCRoute with non-empty method in matches, like kubectl apply -f examples/gateway-grpcroute.yaml
3. The sendconfig requests will always get 400 response and config could not be updated.
```

### Kong Ingress Controller version

```shell
2.10.0, but I think 2.9.x would also have the problem because GRPCRoute is supported since KIC 2.9.
```

### Kubernetes version

```shell
1.27
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

Do not add `~` prefix on paths generated from GRPCRoutes if kong version < 3.0 to generate correct Kong config.

**Which issue this PR fixes**:

fixes #4237 

**Special notes for your reviewer**:

Question: Do we need to backport it to 2.10/2.9?

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/dataplane/parser/translate_grpcroute.go [hunk 1]
```diff
@@ -62,7 +63,8 @@ func (p *Parser) ingressRulesFromGRPCRoute(result *ingressRules, grpcroute *gate
 		if p.featureFlags.ExpressionRoutes {
 			routes = translators.GenerateKongExpressionRoutesFromGRPCRouteRule(grpcroute, ruleNumber)
 		} else {
-			routes = translators.GenerateKongRoutesFromGRPCRouteRule(grpcroute, ruleNumber)
+			prependRegexPrefix := p.kongVersion.GTE(versions.ExplicitRegexPathVersionCutoff)
+			routes = translators.GenerateKongRoutesFromGRPCRouteRule(grpcroute, ruleNumber, prependRegexPrefix)
```
Comment (czeslavo) [inline internal/dataplane/parser/translate_grpcroute.go:67]:
```suggestion
			routes = translators.GenerateKongRoutesFromGRPCRouteRule(grpcroute, ruleNumber, p.featureFlags.RegexPathPrefix)
```
It's already precalculated.

File: internal/dataplane/parser/translators/grpcroute_test.go [hunk 2]
```diff
@@ -196,7 +196,7 @@ func TestGenerateKongRoutesFromGRPCRouteRule(t *testing.T) {
 		tc := tc
 		t.Run(tc.name, func(t *testing.T) {
 			grpcroute := makeTestGRPCRoute(tc.objectName, "default", tc.annotations, tc.hostnames, []gatewayv1alpha2.GRPCRouteRule{tc.rule})
-			routes := GenerateKongRoutesFromGRPCRouteRule(grpcroute, 0)
+			routes := GenerateKongRoutesFromGRPCRouteRule(grpcroute, 0, true)
```
Comment (czeslavo) [inline internal/dataplane/parser/translators/grpcroute_test.go:199]: Can we please add coverage for the `false` case?

Comment (czeslavo) [reply internal/dataplane/parser/translators/grpcroute_test.go:199]: BTW it might be easier to add a golden test case for this. You'd only need to add `internal/dataplane/parser/testdata/golden/grpcroute/in.yaml` (with a sample grpcroute manifest) and `internal/dataplane/parser/testdata/golden/grpcroute/regex-path-prefix-off_settings.yaml` with:

```yaml
feature_flags:
  RegexPathPrefix: false
```

and then just run `make test.golden.update`.

File: internal/dataplane/parser/translate_grpcroute.go (hunk 1 above)
Comment (randmonkey) [reply internal/dataplane/parser/translate_grpcroute.go]: fixed.

File: internal/dataplane/parser/translators/grpcroute_test.go (hunk 2 above)
Comment (randmonkey) [reply internal/dataplane/parser/translators/grpcroute_test.go]: Added unit tests and golden tests.

**Review by czeslavo — APPROVED** [review]
