### PR TITLE
chore(tests): fix flaky konnect node agent unit test

### LINKED ISSUE #3955: Flaky unit test: `TestNodeAgentUpdateNodes/update_status_existing_kic_node`
```
=== RUN   TestNodeAgentUpdateNodes/update_status_existing_kic_node
    node_agent.go:97: konnect-node: "level"=0 "msg"="Starting Konnect NodeAgent" "runtime_group_id"="cluster-00"
?   	github.com/kong/kubernetes-ingress-controller/v2/internal/konnect/runtimegroupsconfig	[no test files]
=== RUN   TestAgent
--- PASS: TestAgent (0.00s)
PASS
    node_agent_test.go:450: 
        	Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/konnect/node_agent_test.go:450
        	Error:      	Condition never satisfied
        	Test:       	TestNodeAgentUpdateNodes/update_status_existing_kic_node
--- FAIL: TestNodeAgentUpdateNodes/update_status_existing_kic_node (2.00s)
```

Related CI failure: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4884294621/jobs/8716840990?pr=3953

### PR DESCRIPTION
**Pull request by pmalek**
**What this PR does / why we need it**:

This aims to fix flaky konnect node update unit test.

**Which issue this PR fixes**:

Fixes #3955

### CODE REVIEW

File: internal/konnect/node_agent_test.go [hunk 1]
```diff
@@ -438,21 +445,22 @@ func TestNodeAgentUpdateNodes(t *testing.T) {
...
+				nodes = nodeService.dumpNodes()
+				return len(nodes) == tc.numNodes
+			}, timeout, tick, "number of nodes in RG should be %d", tc.numNodes)
+
 			require.Eventually(t, func() bool {
-				// check number of nodes in RG.
-				nodes := nodeService.dumpNodes()
-				if len(nodes) != tc.numNodes {
-					return false
-				}
```
Comment (czeslavo) [inline internal/konnect/node_agent_test.go:455]: It might be useful to log all of the actual nodes in case any of the assertions in `Eventually` closure fails, just in case it happens again despite the extended timeout. 

I tried to understand why this test is flaky, but couldn't reproduce it locally (tried `go test -count=1000` a couple of times with no luck). There must be some subtle race condition :/

Comment (pmalek) [reply internal/konnect/node_agent_test.go:455]: 👍 I've changed it to print the nodes but couldn't find a better solution than a for loop ( just printing it using asserts was printing a slice of pointer values). 

Feel free to change it if you know a better way.

**Review by czeslavo — APPROVED** [review]

**Review by czeslavo — APPROVED** [review]
