### PR TITLE
fix: fix KongUpstreamPolicy hash on translation

### LINKED ISSUE #7580: Unable to set apply hashOnFallback set to cookie when using `KongUpstreamPolicy`
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

The following `KongIngress` manifest

```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: cookie-fallback
  namespace: kong
upstream:
  hash_on: header
  hash_on_header: x-lb
  hash_fallback: cookie
  hash_on_cookie: test
  algorithm: consistent-hashing
```

can't be migrated to `KongUpstreamPolicy` e.g.

```
apiVersion: configuration.konghq.com/v1beta1
kind: KongUpstreamPolicy
metadata:
  name: kongupstream
spec:
  hashOn:
    header: x-lb
  hashOnFallback:
    cookie: test
    cookiePath: /
  algorithm: consistent-hashing
```

because it fails to apply:

```
The KongUpstreamPolicy "kongupstream" is invalid:
* <nil>: Invalid value: "object": spec.hashOnFallback.cookie must not be set.
* <nil>: Invalid value: "object": spec.hashOnFallback.cookiePath must not be set.
```

### Kong Ingress Controller version

```shell
3.4.7
```

### Anything else?

https://github.com/Kong/kubernetes-configuration/pull/498 should fix the CRD CEL validation rules but there's still an issue with applying the hash on setting with `cookie` in KIC's translation logic: https://github.com/Kong/kubernetes-ingress-controller/blob/c46527e778a5efd89821537a4371657032c8d20b/internal/dataplane/kongstate/kongupstreampolicy.go#L75-L85

x-ref [FTI-6800](https://konghq.atlassian.net/browse/FTI-6800)

[FTI-6800]: https://konghq.atlassian.net/browse/FTI-6800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by pmalek**
**What this PR does / why we need it**:

Fix `KongUpstreamPolicy` hash on translation.

Currently when users specify cookie as hash fallback the rules are not translated correctly due to peculiar field usage in kong upstream (and `KongUpstreamHash`): cookie and cookie path is used both for hash_on and hash_fallback  in kong upstream but not in `KongUpstreamHash` so we can't simply look at hash_on to set the `KongUpstreamHash`'s `HashOn` to decide how to translate the config.

The way this PR changes the translation, is to retain the "no error" policy, so we rely on CRD validation rules (to be changed in https://github.com/Kong/kubernetes-configuration/pull/498).

In case somehow the invalid config gets pushed to Kong, we are generating `KongConfigurationApplyFailed` events and that's the case when `hash_fallback` is used when cookie is the primary hashing mechanism (docs: https://developer.konghq.com/gateway/entities/upstream/#consistent-hashing).

**Which issue this PR fixes**:

Fixes #7580

FTI-6800

**Special notes for your reviewer**:

This currently uses a commit from release/1.5.x branch [be1d520ac78bc4d46d4335b425ab8e521488316a](https://github.com/Kong/kubernetes-configuration/commit/be1d520ac78bc4d46d4335b425ab8e521488316a). ~https://github.com/Kong/kubernetes-configuration/tree/fix-kongupstreampolicy-hash-on-validation-1.5 branch which has https://github.com/Kong/kubernetes-configuration/pull/498 manually cherry picked.~

Please review together with https://github.com/Kong/kubernetes-configuration/pull/499 which targets the 1.5 release branch of kubernetes-configuration (currently used in KIC).

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/dataplane/kongstate/kongupstreampolicy_test.go [hunk 1]
```diff
@@ -193,6 +193,109 @@ func TestTranslateKongUpstreamPolicy(t *testing.T) {
...
+				HashOnCookie:     lo.ToPtr("cookie-name"),
+				HashOnCookiePath: lo.ToPtr("/cookie-path"),
+				HashFallback:     lo.ToPtr("cookie"),
+			},
+		},
+		{
+			// This will be blocked by CRD validation rules because according to
+			// https://developer.konghq.com/gateway/entities/upstream/#consistent-hashing
+			// if the primary hash_on is set to cookie, the hash_fallback is invalid
+			// and cannot be used.
```
Comment (tao12345666333) [inline internal/dataplane/kongstate/kongupstreampolicy_test.go:280]: Can we add a valid test case for hash_fallback?
e.g. hash_on set to `uri_capture` and hash_fallback set to `header`

Comment (pmalek) [reply internal/dataplane/kongstate/kongupstreampolicy_test.go:280]: Sure: a82d2dddf170c99ed0966350e4818c0e9fc4a1a7. PTAL

**Review by tao12345666333 — APPROVED** [review]
