### PR TITLE
Fix upstream/service collisions for multi-port Kubernetes Services

### LINKED ISSUE #335: kong ingress controller need support for multiple ports per service
### Summary

Kong Ingress controller "0.5.0" not support for multiple ports per service.

**Kong Ingress controller version**
0.5.0

**Kong version**
1.2

### Kubernetes version
Kubernetes Cluster version v1.10 (v1.10.12) - git (clean) commit c757b93cf034d49af3a3b8ecee3b9639a7a11df7 - platform linux/amd64

### What happened

This is my ingress yaml , there have two ports need setting.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    configuration.konghq.com: need-strip-path
    kubernetes.io/ingress.class: kong
  labels:
    app: test-api
  name: test-api
  namespace: staging
spec:
  rules:
  - host: test.mydomain.com
    http:
      paths:
      - backend:
          serviceName: test-api
          servicePort: 5000
        path: /test-api
      - backend:
          serviceName: test-api
          servicePort: 5001
        path: /test-socket
```

kong ingress controller error:
```
E0722 12:39:24.220304       1 controller.go:125] unexpected failure updating Kong configuration:
error creating a valid state for Kong: duplicate upstream definitions found for: 'test-api.staging.svc'
W0722 12:39:24.220345       1 queue.go:113] requeuing staging/test-api, err error creating a valid state for Kong: duplicate upstream definitions found for: 'test-api.staging.svc'
```

### PR DESCRIPTION
**Pull request by rainest**
**What this PR does / why we need it**:
Adds port to Kong service hostnames, in turn adding the port to the associated upstream name.

This prevents collisions and/or misdirected traffic when a Kubernetes Service exposes multiple ports, and Ingress rules use two or more of those ports. Previously, rules for different ports on the same Service would attempt to use the same Kong service/upstream hostname.

**Which issue this PR fixes**
Fixes #335

**Special notes for your reviewer**:
Tests cover Kong service generation only. I reviewed whether it would be useful to separately test `Parser.getUpstreams()` for this, but determined it unnecessary--we do not pass Kubernetes Services to it directly, but rather generate Kong services first and then get upstreams for each Kong service.

### CODE REVIEW

**Comment by gmlp** [comment]
Hi @rainest,
Thanks for this PR. I'm facing the same issue. I would be great if we support another scenario. The problem I had is that I'm working with a headless service and the routing is done using headers.

Regards,
Gonzalo

File: internal/ingress/controller/parser/parser.go [hunk 1]
```diff
@@ -555,7 +555,7 @@ func overrideUpstream(upstream *Upstream,
 func (p *Parser) getUpstreams(serviceMap map[string]Service) ([]Upstream, error) {
 	var upstreams []Upstream
 	for _, service := range serviceMap {
-		upstreamName := service.Backend.ServiceName + "." + service.Namespace + ".svc"
+		upstreamName := service.Backend.ServiceName + "." + service.Namespace + "." + service.Backend.ServicePort.String() + ".svc"
```
Comment (hbagdi) [inline internal/ingress/controller/parser/parser.go]: What happens here when a port is named and is referenced by name in one rule, while referenced by port number in other?
I suspect this will create two different upstreams, which is incorrect.

Could you verify if that's the case or not?

Comment (rainest) [reply internal/ingress/controller/parser/parser.go]: It does, but I don't think we can easily avoid it. The `ServicePort` here isn't a proper `ServicePort` object and we cannot access its `port` value. https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/networking/types.go#L357-L364 simply provides the value itself, presumably directly from the Ingress manifest.

Is there harm beyond superfluous configuration? The targets within still end up correct and traffic is routed normally. I don't think there should be many cases where you'd definitely need both to use the same upstream (healthcheck stuff, though I expect most users rely on K8S healthchecks instead), but for those that do, worst case users just have to make sure they use names or numbers consistently.
