### PR TITLE
fix(manager): Run `AddToScheme` only once in `scheme.Get`

### LINKED ISSUE #7104: `scheme.Get` runs `AddToScheme` multiple times and causes high CPU usage and large amount of temporary objects
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

From FTI-5854.
Customers found KIC 3.4.x has a much higher CPU peak than 2.12.x.
The `Scheme.Get` which is called every time of reconciliation runs `AddToScheme` for every type in each run. The `AddToScheme` calls `AddKnownTypes` which creates temporary objects each time, so large amount of objects are generated in the calls. This brings high CPU usage from both calling of `AddKnownTypes` and gc runners to collect the temporary objects.

[profile-create-3_4.pdf](https://github.com/user-attachments/files/18747633/profile-create-3_4.pdf)

### Expected Behavior

Run `AddToScheme` only once and return the existing scheme in later calls of `scheme.Get`.

### Steps To Reproduce

```markdown
1. Run KIC with `CONTROLLER_PROFILING` env set to true to enable profiling server
2. Expose port 10256 of KIC to localhost
3. run `go tool pprof http://localhost:10256/debug/pprof/profile?seconds=xxx`
4. create multiple ingresses (~1000)
5. Export the result and see the `scheme.Get` and gc calls costed most of CPU time.
```

### Kong Ingress Controller version

```shell
Starting from 3.0.x.
```

### Kubernetes version

```shell
Not related.
```

### Anything else?

Possible fix: run `AddToScheme` only once. But not sure if it is safe to use the same `*runtime.Scheme` everywhere.

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

Run `AddToScheme` in `scheme.Get` only once since `scheme.Get` is called very frequently and `AddToScheme` creates temporary objects. It causes large amount of creation and gc on these objects.

**Which issue this PR fixes**:

fixes #7104 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/manager/scheme/scheme.go [hunk 1]
```diff
@@ -15,46 +17,53 @@ import (
...
-		return nil, err
-	}
-
-	if err := clientgoscheme.AddToScheme(scheme); err != nil {
-		return nil, err
-	}
+var (
+	kicScheme       = runtime.NewScheme()
+	addToSchemeDone atomic.Bool
+)
```
Comment (czeslavo) [inline internal/manager/scheme/scheme.go:23]: If we want to move to a global, we could do something like:

```suggestion
var (
	kicScheme       = initScheme()
)
```

and return the global from `Get()`. We should only be aware that it might get problematic if we have tests that modify the scheme concurrently, as it will lead to data races.

Comment (randmonkey) [reply internal/manager/scheme/scheme.go]: done.

**Comment by czeslavo** [comment]
Added backport label for [feat/kic-as-library](https://github.com/Kong/kubernetes-ingress-controller/tree/feat/kic-as-library) as that's something we should carry over.

**Review by czeslavo — APPROVED** [review]
