### PR TITLE
fix(kongstate): Fill ID for plugins

### LINKED ISSUE #7394: A plugin attached to a KongConsumerGroup and an Ingress can cause configuration error in DB mode
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When I create a plugin attached to a `KongConsumerGroup` and an `Ingress`, the following error will happen in applying configuration to Kong gateway:
```
performing update for http://172.18.128.2:8001 failed: 2 errors occurred:\n\twhile post processing event: inserting plugin response-transformer-advanced for route 7d58209a-68dd-5879-a029-08799f6c67fb and consumer-group 0785e91f-262c-51fd-bb7e-baa9b7b644d4: entity already exists\n\twhile post processing event: inserting plugin response-transformer-advanced for route 7d58209a-68dd-5879-a029-08799f6c67fb and consumer-group 393341ed-a05d-504b-b826-db76f9610dba: entity already exists\n"
```
But we can also see the logs for creating plugins 
```
updated gateway entity	{"v": 1, "action": "create", "kind": "plugin", "name": "response-transformer-advanced for route e60ad185-9a86-4ad1-a22f-97c3a93c5db4.multi.echo..1027 and consumer-group test-consumer-group-1"}
updated gateway entity	{"v": 1, "action": "create", "kind": "plugin", "name": "response-transformer-advanced for route e60ad185-9a86-4ad1-a22f-97c3a93c5db4.multi.echo..1027 and consumer-group test-consumer-group-4"}
```
And a fallback configuration happens then, and a `KongConfigurationApplyFailed` event is observed.

### Expected Behavior

No error happens in applying the configuration with plugin attached to a `KongConsumerGroup` and an `Ingress`.

### Steps To Reproduce

```markdown
1. Run the `TestConsumerGroup` integration test case in DB mode:
KONG_LICENSE_DATA=${KONG_LICENSE_DATA} GOTESTFLAGS="-run=TestConsumerGroup" TEST_KONG_ENTERPRISE=true  make test.integration.postgres
2. Look at the logs during the test and see the error reported from updating configuration to Kong gateway.
```

### Kong Ingress Controller version

```shell
3.4.4
```

### Kubernetes version

```shell
Not related.
```

### Anything else?

Found during the investigation of #7374. Fix of the issue where the fallback configuration is not performed with DB backed mode could cause failure of the integration test case: https://github.com/Kong/kubernetes-ingress-controller/pull/7380#issuecomment-2853878650

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

Fill IDs for plugins based on plugin's name and combination of attached service, route, consumer and consumer group.

**Which issue this PR fixes**:

fixes #7394
**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/dataplane/kongstate/kongstate.go [hunk 1]
```diff
@@ -696,6 +696,15 @@ func (ks *KongState) FillIDs(logger logr.Logger, workspace string) {
 			ks.Vaults[valutIndex] = vault
 		}
 	}
+	// REVIEW: `FillID` is still behind a feature flag that is enabled by default.
+	// Should we enforce filling IDs of plugins no matter whether the feature is enabled (or force filling ID in DB mode)?
```
Comment (pmalek) [inline internal/dataplane/kongstate/kongstate.go:700]: Let's leave this as is. Remember that we're still releasing patch releases.

**Review by pmalek — APPROVED** [review]

**Review by pmalek — APPROVED** [review]
