### PR TITLE
fix(gwapi): only clear status of Gateway API *Routes reconciled by KIC's gateway(s)

### LINKED ISSUE #6067: HTTPRoute status is reconciled regardless of `Gateway`'s `AllowedRoutes` and/or `--gateway-to-reconcile` flag
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When more than 1 KIC is deployed (e.g. using KGO and `Gateway` resources) then HTTPRoutes that are to be reconciled have their status filled in regardless of the listeners' `AllowedRoutes` and/or `--gateway-to-reconcile` flag.

This issue has 2 aspects:

- Not filtering routes per their `Gateway` attachment (consulted with `--gateway-to-reconcile` flag) does make sense to to properly react to situations where an attachment of a route changes (a route was attached to a gateway marked with the flag but now it's not), this could be narrowed down to filtering update events when the route:
  - was created attached to a Gateway that is being reconciled
  - becomes attached to a Gateway that is being reconciled
  - becomes detached from a Gateway that is being reconciled: this should cause the removal of the route from dataplane's configuration

- Because of the above lack of filtering and KIC [clearing the route status only matching on controller name](https://github.com/Kong/kubernetes-ingress-controller/blob/3017d33b724ea084499ece355dff7d43a485fae0/internal/controllers/gateway/httproute_controller.go#L382-L387) (and not taking into account listeners `AllowedRoutes`) this results in perpetual loop of 

    ```
    2024-05-22T12:26:12Z    error   controllers.HTTPRoute   Reconciler error        {"reconcileID": "9418485c-120c-4c51-a2ba-e8a13f648289", "error": "Operation cannot be fulfilled on httproutes.gateway.networking.k8s.io \"httproute-echo\": the object has been modified; please apply your changes to the latest version and try again"}
    2024-05-22T12:26:12Z    debug   controllers.HTTPRoute   Processing httproute    {"GatewayV1HTTPRoute": {"name":"httproute-echo","namespace":"default"}, "v": 1, "namespace": "default", "name": "httproute-echo"}
    2024-05-22T12:26:12Z    debug   controllers.HTTPRoute   Checking deletion timestamp     {"GatewayV1HTTPRoute": {"name":"httproute-echo","namespace":"default"}, "v": 1, "namespace": "default", "name": "httproute-echo"}
    2024-05-22T12:26:12Z    debug   controllers.HTTPRoute   Retrieving GatewayClass and Gateway for route   {"GatewayV1HTTPRoute": {"name":"httproute-echo","namespace":"default"}, "v": 1, "namespace": "default", "name": "httproute-echo"}
    2024-05-22T12:26:12Z    debug   controllers.HTTPRoute   Unsupported route found, processing to verify whether it was ever supported     {"GatewayV1HTTPRoute": {"name":"httproute-echo","namespace":"default"}, "v": 1, "namespace": "default", "name": "httproute-echo"}
    2024-05-22T12:26:12Z    debug   controllers.HTTPRoute   Unsupported route was previously supported, status was updated  {"GatewayV1HTTPRoute": {"name":"httproute-echo","namespace":"default"}, "v": 1, "namespace": "default", "name": "httproute-echo"}
    2024-05-22T12:26:12Z    debug   controllers.Gateway     The request does not match the specified Gateway and will be skipped.   {"v": 1, "gateway": "default/kong2"}
    2024-05-22T12:26:12Z    debug   controllers.HTTPRoute   Processing httproute    {"GatewayV1HTTPRoute": {"name":"httproute-echo","namespace":"default"}, "v": 1, "namespace": "default", "name": "httproute-echo"}
    2024-05-22T12:26:12Z    debug   controllers.HTTPRoute   Checking deletion timestamp     {"GatewayV1HTTPRoute": {"name":"httproute-echo","namespace":"default"}, "v": 1, "namespace": "default", "name": "httproute-echo"}
    2024-05-22T12:26:12Z    debug   controllers.HTTPRoute   Retrieving GatewayClass and Gateway for route   {"GatewayV1HTTPRoute": {"name":"httproute-echo","namespace":"default"}, "v": 1, "namespace": "default", "name": "httproute-echo"}
    2024-05-22T12:26:12Z    debug   controllers.HTTPRoute   Unsupported route found, processing to verify whether it was ever supported     {"GatewayV1HTTPRoute": {"name":"httproute-echo","namespace":"default"}, "v": 1, "namespace": "default", "name": "httproute-echo"}
    2024-05-22T12:26:12Z    debug   controllers.HTTPRoute   Ensuring that dataplane is updated to remove unsupported route (if applicable)  {"GatewayV1HTTPRoute": {"name":"httproute-echo","namespace":"default"}, "v": 1, "namespace": "default", "name": "httproute-echo"}
    2024-05-22T12:26:12Z    debug   controllers.HTTPRoute   Processing httproute    {"GatewayV1HTTPRoute": {"name":"httproute-echo","namespace":"default"}, "v": 1, "namespace": "default", "name": "httproute-echo"}
    2024-05-22T12:26:12Z    debug   controllers.HTTPRoute   Checking deletion timestamp     {"GatewayV1HTTPRoute": {"name":"httproute-echo","namespace":"default"}, "v": 1, "namespace": "default", "name": "httproute-echo"}
    2024-05-22T12:26:12Z    debug   controllers.HTTPRoute   Retrieving GatewayClass and Gateway for route   {"GatewayV1HTTPRoute": {"name":"httproute-echo","namespace":"default"}, "v": 1, "namespace": "default", "name": "httproute-echo"}
    2024-05-22T12:26:12Z    debug   controllers.HTTPRoute   Unsupported route found, processing to verify whether it was ever supported     {"GatewayV1HTTPRoute": {"name":"httproute-echo","namespace":"default"}, "v": 1, "namespace": "default", "name": "httproute-echo"}
    2024-05-22T12:26:12Z    debug   controllers.HTTPRoute   Ensuring that dataplane is updated to remove unsupported route (if applicable)  {"GatewayV1HTTPRoute": {"name":"httproute-echo","namespace":"default"}, "v": 1, "namespace": "default", "name": "httproute-echo"}
    ```

---

This also comes up when running KGO Gateway API conformance tests because that deploys multiple `Gateway`s (and thus KIC instances).

### Expected Behavior

When more than 1 KIC is deployed with `--gateway-to-reconcile`, and that `Gateway` has `allowedRoutes` set, then that is taken into account when setting/clearing routes' statuses.

### Steps To Reproduce

```markdown
Using KGO: 

1. Deploy KGO 
1. Deploy the following manifests:


apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: http
  selector:
    app: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo
  name: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: registry.k8s.io/e2e-test-images/agnhost:2.40
          command:
            - /agnhost
            - netexec
            - --http-port=8080
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: 10m
---
kind: GatewayConfiguration
apiVersion: gateway-operator.konghq.com/v1beta1
metadata:
  name: kong
  namespace: default
spec:
  dataPlaneOptions:
    deployment:
      podTemplateSpec:
        spec:
          containers:
          - name: proxy
            # renovate: datasource=docker versioning=docker
            image: kong/kong-gateway:3.6
            readinessProbe:
              initialDelaySeconds: 1
              periodSeconds: 1
  controlPlaneOptions:
    deployment:
      podTemplateSpec:
        spec:
          containers:
          - name: controller
            # renovate: datasource=docker versioning=docker
            image: kong/kubernetes-ingress-controller:3.1.5
            readinessProbe:
              initialDelaySeconds: 1
              periodSeconds: 1
            env:
            - name: CONTROLLER_LOG_LEVEL
              value: debug
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kong
spec:
  controllerName: konghq.com/gateway-operator
  parametersRef:
    group: gateway-operator.konghq.com
    kind: GatewayConfiguration
    name: kong
    namespace: default
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kong
  namespace: default
spec:
  gatewayClassName: kong
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
      namespaces:
        from: Selector
        selector:
          matchLabels:
            # This label is added automatically as of K8s 1.22 to all namespaces
            kubernetes.io/metadata.name: default
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-echo
  namespace: default
  annotations:
    konghq.com/strip-path: "true"
spec:
  parentRefs:
  - name: kong
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /echo
    backendRefs:
    - name: echo
      kind: Service
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kong2
spec:
  controllerName: konghq.com/gateway-operator
  parametersRef:
    group: gateway-operator.konghq.com
    kind: GatewayConfiguration
    name: kong
    namespace: default
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kong2
  namespace: default
spec:
  gatewayClassName: kong
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
      namespaces:
        from: Selector
        selector:
          matchLabels:
            kubernetes.io/metadata.name: kong-system # this should match 0 routes as the only one deployed here is in 'default' namespace
```

### Kong Ingress Controller version

```shell
3.1.5
```

### Kubernetes version

_No response_

### Proposed solution

- take listeners `allowedRoutes` into account [when clearing the HTTPRoute status](https://github.com/Kong/kubernetes-ingress-controller/blob/3017d33b724ea084499ece355dff7d43a485fae0/internal/controllers/gateway/httproute_controller.go#L384-L387)
- add filtering for HTTPRoutes in HTTPRoute controller so that on updates, HTTPRoute is reconciled when
  - it was created attached to a Gateway that is being reconciled
  - it becomes attached to a Gateway that is being reconciled
  - it becomes detached from a Gateway that is being reconciled: this should cause the removal of the route from dataplane's configuration

### PR DESCRIPTION
**Pull request by pmalek**
**What this PR does / why we need it**:

Fixes an issue when there's more than 1 KIC (or there are other controllers that reconcile ~HTTPRoutes~ Gateway API *Routes) and KIC then tries to clear status of ~`HTTPRoute`~  *Routes that it should not touch (anymore).

**Which issue this PR fixes**:

Fixes #6067

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/controllers/gateway/grpcroute_controller.go [hunk 1]
```diff
@@ -305,22 +322,15 @@ func (r *GRPCRouteReconciler) Reconcile(ctx context.Context, req ctrl.Request) (
...
 	if err != nil {
-		if err.Error() == unsupportedGW {
-			debug(log, grpcroute, "Unsupported route found, processing to verify whether it was ever supported")
+		if errors.Is(err, ErrNoSupportedGateway) {
 			// if there's no supported Gateway then this route could have been previously
 			// supported by this controller. As such we ensure that no supported Gateway
 			// references exist in the object status any longer.
-			statusUpdated, err := r.ensureGatewayReferenceStatusRemoved(ctx, grpcroute)
+			_, err := ensureGatewayReferenceStatusRemoved(ctx, r.Client, log, grpcroute)
 			if err != nil {
```
Comment (programmer04) [inline internal/controllers/gateway/grpcroute_controller.go:330]:
```suggestion
			if _, err := ensureGatewayReferenceStatusRemoved(ctx, r.Client, log, grpcroute); err != nil {
```

File: internal/controllers/gateway/httproute_controller.go [hunk 2]
```diff
@@ -124,22 +125,38 @@ func (r *HTTPRouteReconciler) SetupWithManager(mgr ctrl.Manager) error {
...
-	// simply reconcile ALL HTTPRoute objects. This allows us to drop the backend
-	// data-plane config for an HTTPRoute if it somehow becomes disconnected from
-	// a supported Gateway and GatewayClass.
-	return blder.For(&gatewayapi.HTTPRoute{}).
+	// We enqueue only routes that are:
+	// - attached during creation or deletion
+	// - have been attached or detached to a reconciled Gateway.
+	// This allows us to drop the backend data-plane config for a route if
+	// it somehow becomes disconnected from a supported Gateway and GatewayClass.
+	return blder.
```
Comment (programmer04) [inline internal/controllers/gateway/httproute_controller.go:133]: `blder`? Is it a typo -> `builder`
We have everywhere in the repo like this... 😅

File: internal/controllers/gateway/httproute_controller.go [hunk 3]
```diff
@@ -379,22 +396,15 @@ func (r *HTTPRouteReconciler) Reconcile(ctx context.Context, req ctrl.Request) (
...
 	if err != nil {
-		if err.Error() == unsupportedGW {
-			debug(log, httproute, "Unsupported route found, processing to verify whether it was ever supported")
+		if errors.Is(err, ErrNoSupportedGateway) {
 			// if there's no supported Gateway then this route could have been previously
 			// supported by this controller. As such we ensure that no supported Gateway
 			// references exist in the object status any longer.
-			statusUpdated, err := r.ensureGatewayReferenceStatusRemoved(ctx, httproute)
+			_, err := ensureGatewayReferenceStatusRemoved(ctx, r.Client, log, httproute)
 			if err != nil {
```
Comment (programmer04) [inline internal/controllers/gateway/httproute_controller.go:404]:
```suggestion
			if _, err := ensureGatewayReferenceStatusRemoved(ctx, r.Client, log, httproute); err != nil {
```

File: internal/controllers/gateway/route_predicates.go [hunk 4]
```diff
@@ -0,0 +1,108 @@
...
+	"github.com/kong/kubernetes-ingress-controller/v3/internal/gatewayapi"
+)
+
+func isRouteAttachedToReconciledGateway[routeT gatewayapi.RouteT](
+	cl client.Client, log logr.Logger, gatewayNN controllers.OptionalNamespacedName, obj client.Object,
+) bool {
+	kind := obj.GetObjectKind().GroupVersionKind().Kind
+	route, ok := obj.(routeT)
+	if !ok {
+		log.Error(
```
Comment (programmer04) [inline internal/controllers/gateway/route_predicates.go:23]:
```suggestion
	route, ok := obj.(routeT)
	if !ok {
		kind := obj.GetObjectKind().GroupVersionKind().Kind
		log.Error(
```

File: internal/controllers/gateway/route_utils.go [hunk 5]
```diff
@@ -985,3 +984,65 @@ func isRouteAcceptedByListener[T gatewayapi.RouteT](ctx context.Context,
...
+// implementation to prune status references to Gateways supported by this controller
+// in the provided route.
+func ensureGatewayReferenceStatusRemoved[routeT gatewayapi.RouteT](
+	ctx context.Context, cl client.Client, log logr.Logger, route routeT,
+) (bool, error) {
+	debug(log, route, "Unsupported route found, processing to verify whether it was ever supported")
+	kind := route.GetObjectKind().GroupVersionKind().Kind
+	parents := getRouteStatusParents(route)
+
+	// drop all status references to supported Gateway objects
```
Comment (programmer04) [inline internal/controllers/gateway/route_utils.go:998]:
```suggestion
	// Drop all status references to supported Gateway objects.
```

File: internal/controllers/gateway/route_utils.go [hunk 6]
```diff
@@ -985,3 +984,65 @@ func isRouteAcceptedByListener[T gatewayapi.RouteT](ctx context.Context,
...
+		} else {
+			parentRefNN := string(status.ParentRef.Name)
+			if status.ParentRef.Namespace != nil {
+				parentRefNN = fmt.Sprintf("%s/%s", *status.ParentRef.Namespace, parentRefNN)
+			}
+			debug(log, route, "Removing parentRef from route status", "parentRef", parentRefNN, "kind", kind)
+		}
+	}
+
+	// if the new list of statuses is the same length as the old
```
Comment (programmer04) [inline internal/controllers/gateway/route_utils.go:1012]:
```suggestion
	// If the new list of statuses is the same length as the old
```

File: internal/controllers/gateway/route_utils.go [hunk 7]
```diff
@@ -985,3 +984,65 @@ func isRouteAcceptedByListener[T gatewayapi.RouteT](ctx context.Context,
...
+	// nothing has changed and we're all done.
+	if len(newStatuses) == len(parents) {
+		return false, nil
+	}
+
+	// if the route doesn't have a supported Gateway+GatewayClass associated with
```
Comment (programmer04) [inline internal/controllers/gateway/route_utils.go:1018]:
```suggestion
	// If the route doesn't have a supported Gateway+GatewayClass associated with
```

File: internal/controllers/gateway/route_utils.go [hunk 8]
```diff
@@ -985,3 +984,65 @@ func isRouteAcceptedByListener[T gatewayapi.RouteT](ctx context.Context,
...
+	// ensure that it's removed from the proxy cache to avoid orphaned data-plane
+	// configurations.
+	debug(log, route, "Ensuring that dataplane is updated to remove unsupported route (if applicable)")
+	setRouteStatusParents(route, newStatuses)
+	if err := cl.Status().Update(ctx, route); err != nil {
+		return false, fmt.Errorf("failed to remove Gateway parentRef from %s status: %w", kind, err)
+	}
+
+	debug(log, route, "Unsupported route was previously supported, status was updated")
+	// the status needed to be updated and it was updated successfully
```
Comment (programmer04) [inline internal/controllers/gateway/route_utils.go:1029]:
```suggestion
	// The status needed to be updated and it was updated successfully.
```

File: internal/controllers/gateway/tcproute_controller.go [hunk 9]
```diff
@@ -301,22 +318,15 @@ func (r *TCPRouteReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
...
 	if err != nil {
-		if err.Error() == unsupportedGW {
-			debug(log, tcproute, "Unsupported route found, processing to verify whether it was ever supported")
+		if errors.Is(err, ErrNoSupportedGateway) {
 			// if there's no supported Gateway then this route could have been previously
 			// supported by this controller. As such we ensure that no supported Gateway
 			// references exist in the object status any longer.
-			statusUpdated, err := r.ensureGatewayReferenceStatusRemoved(ctx, tcproute)
+			_, err := ensureGatewayReferenceStatusRemoved(ctx, r.Client, log, tcproute)
 			if err != nil {
```
Comment (programmer04) [inline internal/controllers/gateway/tcproute_controller.go:326]:
```suggestion
			if _, err := ensureGatewayReferenceStatusRemoved(ctx, r.Client, log, tcproute); err != nil {
```

File: internal/controllers/gateway/udproute_controller.go [hunk 10]
```diff
@@ -94,12 +95,28 @@ func (r *UDPRouteReconciler) SetupWithManager(mgr ctrl.Manager) error {
...
+	// We enqueue only routes that are:
+	// - attached during creation or deletion
+	// - have been attached or detached to a reconciled Gateway.
+	// This allows us to drop the backend data-plane config for a route if
+	// it somehow becomes disconnected from a supported Gateway and GatewayClass.
+	return blder.
+		For(&gatewayapi.UDPRoute{},
+			builder.WithPredicates(predicate.Funcs{
+				GenericFunc: func(_ event.GenericEvent) bool {
+					return false // we don't need to enqueue from generic
```
Comment (programmer04) [inline internal/controllers/gateway/udproute_controller.go:107]:
```suggestion
					return false // We don't need to enqueue from generic.
```

File: internal/controllers/gateway/tlsroute_controller.go [hunk 11]
```diff
@@ -296,22 +313,15 @@ func (r *TLSRouteReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
...
 	if err != nil {
-		if err.Error() == unsupportedGW {
-			debug(log, tlsroute, "Unsupported route found, processing to verify whether it was ever supported")
+		if errors.Is(err, ErrNoSupportedGateway) {
 			// if there's no supported Gateway then this route could have been previously
 			// supported by this controller. As such we ensure that no supported Gateway
 			// references exist in the object status any longer.
-			statusUpdated, err := r.ensureGatewayReferenceStatusRemoved(ctx, tlsroute)
+			_, err := ensureGatewayReferenceStatusRemoved(ctx, r.Client, log, tlsroute)
 			if err != nil {
```
Comment (programmer04) [inline internal/controllers/gateway/tlsroute_controller.go:321]:
```suggestion
			if _, err := ensureGatewayReferenceStatusRemoved(ctx, r.Client, log, tlsroute); err != nil {
```

**Review by programmer04 — COMMENTED** [review]
Overall LGTM, some more or less relevant nits

File: internal/controllers/gateway/httproute_controller.go (hunk 2 above)
Comment (pmalek) [reply internal/controllers/gateway/httproute_controller.go:133]: I guess that's named like this to not shadow the `https://github.com/Kong/kubernetes-ingress-controller/pull/6079/files#diff-57886002dd2fd6bfa8d355807bbd169962ca85034ef2cce7835a081b2a15c637R21` import.

Comment (programmer04) [reply internal/controllers/gateway/httproute_controller.go:133]: I see, I think we can do better, but id doesn't matter much

**Review by programmer04 — APPROVED** [review]

File: internal/controllers/gateway/httproute_controller.go (hunk 2 above)
Comment (pmalek) [reply internal/controllers/gateway/httproute_controller.go:133]: Would you prefer us to change this? If so I suggest that this would be a separate PR. Otherwise, please resolve this thread.

Comment (programmer04) [reply internal/controllers/gateway/httproute_controller.go:133]: yes, it's out of scope here
