### PR TITLE
fix(manager): set InitCacheSyncDuration to 5s by default and allow it…

### LINKED ISSUE #5175: Race condition between secret reconciler and object reference index
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We recently noticed similar errors to #4672 where our secrets were getting "Not Found" errors despite very much existing and being referenced by KongConsumer via `credentials`. After checking our CRDs as mentioned in that issue, we added some custom logging to understand why our secrets were not getting populated into the cache. The custom logging revealed that the controller for Secrets was evaluating reference checks before the controller for KongConsumer had reconciled the consumers and populated the references, resulting in 0 secrets being reconciled. 

### Expected Behavior

All initial resources should be loaded before calculating references. 

### Steps To Reproduce

_No response_

### Kong Ingress Controller version

```shell
3.0.0, but appears to be happening in 2.11.* as well
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T12:16:51Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.10-eks-4f4795d", GitCommit:"164dfb62db432c0b28a1fced3956256af68533b6", GitTreeState:"clean", BuildDate:"2023-10-20T23:21:27Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```

### Anything else?

Similer to #4672

### PR DESCRIPTION
**Pull request by backjo**
… to be configured via cli

**What this PR does / why we need it**:
This sets the default value for InitCacheSyncDuration to 5 seconds - as it was in #2249 - to avoid 'partial' writes to the proxy configuration before the Kubernetes objects have a had a chance to sync. This default value appears to have been inadvertently changed as part of #4101 . Additionally, this PR exposes the value for configuration by end-users. 

**Which issue this PR fixes**:

Closes #5175 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [X] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Review by rainest — CHANGES_REQUESTED** [review]
Does this actually need to be configurable, or is fixing the regression sufficient? We'd left it inaccessible originally because we weren't sure if cases where the resource count was large enough where population did exceed 5s were likely in practice.

It's unfortunately not an intuitive setting to understand if you aren't familiar with the implementation internals, so it felt like it'd likely be an obscure knob where nobody knows when/if they should tweak it.

That's not a huge reason to avoid adding it, but if you _have_ encountered a sufficiently large config set to need it and have logs or other indicators that'd show when users need to increase it, that'd be useful for docs.

**Comment by backjo** [comment]
> Does this actually need to be configurable, or is fixing the regression sufficient? We'd left it inaccessible originally because we weren't sure if cases where the resource count was large enough where population did exceed 5s were likely in practice.
> 
> It's unfortunately not an intuitive setting to understand if you aren't familiar with the implementation internals, so it felt like it'd likely be an obscure knob where nobody knows when/if they should tweak it.
> 
> That's not a huge reason to avoid adding it, but if you _have_ encountered a sufficiently large config set to need it and have logs or other indicators that'd show when users need to increase it, that'd be useful for docs.

Yeah, I decided to add it because from the logs we put in, we felt a little too close for comfort (~4ish seconds) on the time it took for the initial configuration to be loaded - especially given that a partial configuration results in 4XX errors all over the place for us. I totally agree it's a non-intuitive setting if one is unfamiliar with the implementation details - and ideally a fix per #2315 would get rid of the need for it altogether - but given that it's the current lever used to solve the cache sync problem and the latency may vary depending on the size / performance of the cluster it's being run on, I think it makes sense to expose for operators to configure.

**Comment by czeslavo** [comment]
Added `backport release/2.12.x` to have it ported to the LTS.

**Review by czeslavo — APPROVED** [review]

File: internal/manager/config.go [hunk 1]
```diff
@@ -196,6 +196,7 @@ func (c *Config) FlagSet() *pflag.FlagSet {
 	flagSet.StringVar(&c.ProbeAddr, "health-probe-bind-address", fmt.Sprintf(":%v", HealthzPort), "The address the probe endpoint binds to.")
 	flagSet.Float32Var(&c.ProxySyncSeconds, "proxy-sync-seconds", dataplane.DefaultSyncSeconds,
 		"Define the rate (in seconds) in which configuration updates will be applied to the Kong Admin API.")
+	flagSet.DurationVar(&c.InitCacheSyncDuration, "init-cache-sync-duration", 5*time.Second, `The initial delay to wait for Kubernetes object caches to be synced before the initial configuration`)
```
Comment (mlavacca) [inline internal/manager/config.go:199]: I would use a const value instead of a hardcoded value for the default, as it is the approach we have for all the flags.

**Review by mlavacca — CHANGES_REQUESTED** [review]
Looks good to me, apart from a minor nit.

**Review by mlavacca — DISMISSED** [review]

**Review by czeslavo — DISMISSED** [review]

**Comment by rainest** [comment]
Blah, forgot that you can't quite suggest doc changes there from the PR due to the need for `make generate` to copy those elsewhere.

**Review by mlavacca — APPROVED** [review]

**Review by czeslavo — APPROVED** [review]

**Review by rainest — APPROVED** [review]

**Comment by piotrwielgolaski-tomtom** [comment]
when can we hope to get this in 3.x line? getting partial configuration is very dangerous
