### PR TITLE
tests: fix flaky TestAgent

### LINKED ISSUE #4200: Flaky unit test `TestAgent`
```
=== FAIL: internal/license TestAgent/initial_license_retrieval_fails_and_recovers/regular_polling_period_is_used_after_the_initial_license_is_retrieved (0.01s)
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:77: license not yet available
    agent_test.go:158: 
        	Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/license/agent_test.go:158
        	Error:      	Max difference between 2023-06-20 13:27:13.216970737 +0000 UTC m=+0.072734417 and 2023-06-20 13:27:13.220446564 +0000 UTC m=+0.076210244 allowed is 1ms, but difference was -3.475827ms
        	Test:       	TestAgent/initial_license_retrieval_fails_and_recovers/regular_polling_period_is_used_after_the_initial_license_is_retrieved
```

Seems like timing issue due to sharing CPU on CI

Failed CI run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5323125476/jobs/9640494963

### PR DESCRIPTION
**Pull request by pmalek**
**What this PR does / why we need it**:

This PR introduces a `Ticker` interface within the license agent and uses that to mock time 🕐 .

This should help us fix #4200.

**Which issue this PR fixes**:

Fixes #4200.

### CODE REVIEW

File: test/mocks/ticker.go [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+	close(t.sigClose)
+}
+
+func (t *Ticker) Channel() <-chan time.Time {
+	return t.ch
+}
+
+func (t *Ticker) Now() time.Time {
+	t.lock.Lock()
+	defer t.lock.Unlock()
```
Comment (programmer04) [inline test/mocks/ticker.go:53]:
```suggestion
	t.lock.RLock()
	defer t.lock.RUnlock()
```
since rw mutex has been used and here there is only reading

File: internal/license/agent_test.go [hunk 2]
```diff
@@ -98,38 +108,51 @@ func TestAgent(t *testing.T) {
...
 
 		// Return an error on the first call to List() to verify that the agent handles this correctly.
 		upstreamClient.ReturnError(errors.New("something went wrong on a backend"))
 
 		const (
 			// Set the initial polling period to a very short duration to ensure that the agent retries quickly.
-			initialPollingPeriod = time.Millisecond
-			regularPollingPeriod = time.Millisecond * 5
-			allowedDelta         = time.Millisecond
+			initialPollingPeriod = time.Minute * 3
```
Comment (programmer04) [inline internal/license/agent_test.go:120]: The above comment is a little misleading, I think it should change or removed. It sounds like we'd like to actually wait (not use a mocked ticker) and 3 minutes is not a "very short duration" for unit tests

File: test/mocks/ticker.go [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+
+	return ticker
+}
+
+type Ticker struct {
+	lock     sync.RWMutex
+	sigTime  chan time.Time
+	sigClose chan struct{}
+	sigReset chan time.Duration
+	sigAdd   chan time.Duration
```
Comment (programmer04) [inline test/mocks/ticker.go:30]: What is the purpose of that channels? I see that they are closed in `Stop()` method, but I don't anywhere that they are used by something else

File: internal/util/clock/ticker.go [hunk 4]
```diff
@@ -0,0 +1,25 @@
+package clock
+
+import "time"
+
+func NewTicker() *TimeTicker {
+	return &TimeTicker{
+		ticker: time.NewTicker(1000 * time.Hour),
```
Comment (programmer04) [inline internal/util/clock/ticker.go:7]: Would you mind adding a small comment or moving to a constant with a meaningful name the `1000 * time.Hour` expression? It's not obvious for reader why we set this like that

**Review by programmer04 — CHANGES_REQUESTED** [review]

File: test/mocks/ticker.go (hunk 3 above)
Comment (pmalek) [reply test/mocks/ticker.go:30]: Leftover from previous implementation. Removing.

File: internal/license/agent_test.go [hunk 5]
```diff
@@ -98,38 +108,50 @@ func TestAgent(t *testing.T) {
...
 			logr.Discard(),
 			license.WithInitialPollingPeriod(initialPollingPeriod),
 			license.WithPollingPeriod(regularPollingPeriod),
+			license.WithTicker(ticker),
 		)
 
 		startTime := time.Now()
 		go func() {
 			err := a.Start(ctx)
 			require.NoError(t, err)
```
Comment (programmer04) [inline internal/license/agent_test.go:135]: `require` is not safe to call in created goroutines - read more https://github.com/stretchr/testify/pull/1392

**Review by programmer04 — CHANGES_REQUESTED** [review]
Just one small thing that I spotted

File: internal/license/agent_test.go (hunk 5 above)
Comment (pmalek) [reply internal/license/agent_test.go]: 👍 The error returned from `Start()` isn't really all that useful since it will only return the error from the cancelled context so we can just fall back to `go a.Start(ctx)` here

**Review by programmer04 — APPROVED** [review]
🍏
