### PR TITLE
fix: register translation failures on translating KongConsumers

### LINKED ISSUE #4311: Redundant error logged constantly when KongConsumer and credential Secret is misconfigured
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**The first example**, for the below
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consumer-1
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: key-auth
username: consumer-1
credentials:
  - the-missing-one
```
where `KongConsumer` references in the `credentials` field non-existing K8s `Secret` **every 3 seconds** the below is logged

```log
ERRO[2016] failed to fetch secret          error="Secret default/the-missing-one not found" kongconsumer_name=consumer-1 kongconsumer_namespace=default secret_name=the-missing-one secret_namespace=default
ERRO[2016] failed to fetch KongPlugin      error="no KongPlugin or KongClusterPlugin was found" kongplugin_name=key-auth kongplugin_namespace=default
```

**Second example**, for the below
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consumer-1
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: key-auth
username: consumer-1
credentials:
  - secret-key
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-key
type: Opaque
data:
  foo: Yy0x
  bar: a2V5LWF1dGg=
```

where K8s `Secret` that is passed to the `credentials` field does not follow the expected format for the section `data`
```yaml
  key: Yy0x
  kongCredType: a2V5LWF1dGg=
```
and no existing plugin `key-auth` is referenced **every 3 seconds** the below is logged
```log
ERRO[2856] failed to provision credential          error="invalid credType: " kongconsumer_name=consumer-1 kongconsumer_namespace=default secret_name=secret-key secret_namespace=default
ERRO[2856] failed to provision credential          error="invalid credType: " kongconsumer_name=consumer-1 kongconsumer_namespace=default secret_name=secret-key secret_namespace=default
ERRO[2856] failed to fetch KongPlugin              error="no KongPlugin or KongClusterPlugin was found" kongplugin_name=key-auth kongplugin_namespace=default
```

**Conclusion**
Those log entries unnecessarily consume the resources of a monitoring system. Moreover K8s `event` is not produced for those situations.

Other situations may exist for such cases, please verify them.

### Expected Behavior

KIC does not spam with redundant log messages and respective K8s `event` is generated.

To consider: when deciding to leave the log entry for the first appearance of such misconfiguration maybe do not log it with an error level (because KIC operates normally)

### Steps To Reproduce

```markdown
1. Apply one of the examples YAMLs from the **Current behavior** section
2. Observe K8s events and logs from KIC
```

### Kong Ingress Controller version

```shell
`main` branch
```

### Kubernetes version

```shell
Irrelevant
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

register a translation failure when `FillConsumersAndCredentials` fails to translate a `KongConsumer` to attach a k8s event to it. This reduces the redundant logs to record the errors. 

**Which issue this PR fixes**:

fixes #4311 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/dataplane/kongstate/kongstate.go [hunk 1]
```diff
@@ -94,6 +103,7 @@ func (ks *KongState) FillConsumersAndCredentials(log logrus.FieldLogger, s store
 				if k == "hash_secret" {
 					boolVal, err := strconv.ParseBool(string(v))
 					if err != nil {
+						// REVIEW: this is not an error blocking translate the consumer to Kong's consumer, do we add a translation error here?
```
Comment (czeslavo) [inline internal/dataplane/kongstate/kongstate.go:106]: I would say that we should treat it as a translation error as well. Despite the fact we'll still attempt to configure the consumer when parsing of `hash_secret` fails, we're defaulting to `false` which might not be something the user desires. IMO it's worth bubbling up as an event.

File: internal/dataplane/kongstate/kongstate.go [hunk 2]
```diff
@@ -106,6 +116,7 @@ func (ks *KongState) FillConsumersAndCredentials(log logrus.FieldLogger, s store
 				if k == "ttl" {
 					intVal, err := strconv.Atoi(string(v))
 					if err != nil {
+						// REVIEW: this is not an error blocking translate the consumer to Kong's consumer, do we add a translation error here?
```
Comment (czeslavo) [inline internal/dataplane/kongstate/kongstate.go:119]: Ditto.

File: internal/dataplane/kongstate/kongstate_test.go [hunk 3]
```diff
@@ -335,64 +346,226 @@ func TestFillConsumersAndCredentials(t *testing.T) {
...
-		assert.Equal(t, want.Consumers[0].KeyAuths[0].Key, state.Consumers[0].KeyAuths[0].Key)
-		assert.Equal(t, want.Consumers[0].Oauth2Creds[0].ClientID, state.Consumers[0].Oauth2Creds[0].ClientID)
-		assert.Equal(t, want.Consumers[0].Oauth2Creds[0].ClientSecret, state.Consumers[0].Oauth2Creds[0].ClientSecret)
-		assert.Equal(t, want.Consumers[0].Oauth2Creds[0].HashSecret, state.Consumers[0].Oauth2Creds[0].HashSecret)
-		assert.Equal(t, want.Consumers[0].Oauth2Creds[0].RedirectURIs, state.Consumers[0].Oauth2Creds[0].RedirectURIs)
-	})
+	for i, tc := range testCases {
+		indexStr := strconv.Itoa(i)
+		tc := tc
+		t.Run(indexStr+"-"+tc.name, func(t *testing.T) {
```
Comment (czeslavo) [inline internal/dataplane/kongstate/kongstate_test.go:526]: Why not just a name? They are unique, aren't they?
```suggestion
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
```

File: internal/dataplane/kongstate/kongstate_test.go [hunk 4]
```diff
@@ -335,64 +346,226 @@ func TestFillConsumersAndCredentials(t *testing.T) {
...
-			KeyAuths: []*KeyAuth{{kong.KeyAuth{
-				Key: kong.String("whatever"),
-				TTL: kong.Int(1024),
-			}}},
-			Oauth2Creds: []*Oauth2Credential{
+	testCases := []struct {
+		name                        string
+		k8sConsumers                []*configurationv1.KongConsumer
+		expectedKongStateConsumers  []Consumer
+		expectedTranslationFailures map[k8stypes.NamespacedName]failures.ResourceFailure
```
Comment (czeslavo) [inline internal/dataplane/kongstate/kongstate_test.go:374]: As I can see we're only using `ResourceFailure.Message()` in the assertions - how about changing this like that:
```suggestion
		expectedTranslationFailuresMessages map[k8stypes.NamespacedName]string
```

File: internal/dataplane/kongstate/kongstate.go [hunk 5]
```diff
@@ -116,22 +127,33 @@ func (ks *KongState) FillConsumersAndCredentials(log logrus.FieldLogger, s store
 			}
 			credType, ok := credConfig["kongCredType"].(string)
 			if !ok {
-				err := fmt.Errorf("invalid credType: %v", credType)
-				log.WithError(err).Errorf("failed to provision credential")
+				failureCollector.PushResourceFailure(
+					fmt.Sprintf("failed to provision credential: invalid credType: type '%T' not string", credType),
```
Comment (czeslavo) [inline internal/dataplane/kongstate/kongstate.go:131]:
```suggestion
					fmt.Sprintf("failed to provision credential: invalid kongCredType: type '%T' not string", credType),
```

File: internal/dataplane/kongstate/kongstate.go [hunk 6]
```diff
@@ -116,22 +127,33 @@ func (ks *KongState) FillConsumersAndCredentials(log logrus.FieldLogger, s store
...
+					consumer,
+				)
+				continue
 			}
 			if !credentials.SupportedTypes.Has(credType) {
-				err := fmt.Errorf("invalid credType: %v", credType)
-				log.WithError(err).Error("failed to provision credential")
+				failureCollector.PushResourceFailure(
+					fmt.Sprintf("failed to provision credential: invalid credType: %v", credType),
```
Comment (czeslavo) [inline internal/dataplane/kongstate/kongstate.go:138]:
```suggestion
					fmt.Sprintf("failed to provision credential: not supported kongCredType: %q", credType),
```

File: internal/dataplane/kongstate/kongstate.go [hunk 7]
```diff
@@ -77,7 +83,10 @@ func (ks *KongState) FillConsumersAndCredentials(log logrus.FieldLogger, s store
 			})
 			secret, err := s.GetSecret(consumer.Namespace, cred)
 			if err != nil {
-				log.WithError(err).Error("failed to fetch secret")
+				failureCollector.PushResourceFailure(
+					fmt.Sprintf("failed to fetch secret: %v", err),
+					consumer,
+				)
```
Comment (czeslavo) [inline internal/dataplane/kongstate/kongstate.go:89]: I think it would be useful to provide context on what credential every failure is reported for. In error logs, we had `secret_name` and `secret_namespace` set, maybe we could prepare a closure in every `for _, cred := range consumer.Credentials {` run, something like this:

```go
pushCredResourceFailures := func(message string) {
    failuresCollector.PushResourceFailure(fmt.Sprintf("credential %q failure: %s", cred, message), consumer)
}
```

File: internal/dataplane/kongstate/kongstate.go (hunk 1 above)
Comment (randmonkey) [reply internal/dataplane/kongstate/kongstate.go]: Added translation failure here.

File: internal/dataplane/kongstate/kongstate.go (hunk 2 above)
Comment (randmonkey) [reply internal/dataplane/kongstate/kongstate.go]: Ditto..

File: internal/dataplane/kongstate/kongstate_test.go (hunk 4 above)
Comment (randmonkey) [reply internal/dataplane/kongstate/kongstate_test.go]: done.

File: internal/dataplane/kongstate/kongstate.go (hunk 5 above)
Comment (randmonkey) [reply internal/dataplane/kongstate/kongstate.go]: done.

File: internal/dataplane/kongstate/kongstate.go (hunk 6 above)
Comment (randmonkey) [reply internal/dataplane/kongstate/kongstate.go]: done.

File: internal/dataplane/kongstate/kongstate_test.go (hunk 3 above)
Comment (randmonkey) [reply internal/dataplane/kongstate/kongstate_test.go:510]: I just wanted to print the index of test case when test fails to find it quickly, because sometimes I will fold the long long struct in the editor and the name is not displayed in such situation.

Comment (czeslavo) [reply internal/dataplane/kongstate/kongstate_test.go:510]: Hm, I see. In GoLand when the test fails I can easily click on the failed test and it will take me to the test case in code. I see your point that it may be quicker this way.

BTW IMO we've made a bad choice by using test names with spaces - that prevents us from just copying the test case name from the output and finding it directly in the code. By using spaces, `go test`'s output gives us test names with spaces transformed into `_`. I tended to use underscores instead of spaces in test cases name in the past and it didn't hurt that much. :)

File: internal/dataplane/kongstate/kongstate.go [hunk 8]
```diff
@@ -66,18 +72,16 @@ func (ks *KongState) FillConsumersAndCredentials(log logrus.FieldLogger, s store
...
+			pushCredentialResourceFailures := func(message string) {
+				failuresCollector.PushResourceFailure(fmt.Sprintf("credential %q failure: %s", cred, message), consumer)
+			}
 			secret, err := s.GetSecret(consumer.Namespace, cred)
 			if err != nil {
-				log.WithError(err).Error("failed to fetch secret")
+				failuresCollector.PushResourceFailure(
+					fmt.Sprintf("failed to fetch secret: %v", err),
+					consumer,
+				)
```
Comment (czeslavo) [inline internal/dataplane/kongstate/kongstate.go:84]:
```suggestion
				pushCredentialResourceFailures(fmt.Sprintf("failed to fetch secret: %v", err))
```

File: internal/dataplane/kongstate/kongstate.go [hunk 9]
```diff
@@ -116,22 +126,29 @@ func (ks *KongState) FillConsumersAndCredentials(log logrus.FieldLogger, s store
...
+				pushCredentialResourceFailures(
+					fmt.Sprintf("failed to provision credential: invalid kongCredType: type '%T' not string", credType),
+				)
+				continue
 			}
 			if !credentials.SupportedTypes.Has(credType) {
-				err := fmt.Errorf("invalid credType: %v", credType)
-				log.WithError(err).Error("failed to provision credential")
+				pushCredentialResourceFailures(
+					fmt.Sprintf("failed to provision credential: unsupported kongCredType: %v", credType),
```
Comment (czeslavo) [inline internal/dataplane/kongstate/kongstate.go:136]:
```suggestion
					fmt.Sprintf("failed to provision credential: unsupported kongCredType: %q", credType),
```

File: test/envtest/kongstate_consumer_failures_test.go [hunk 10]
```diff
@@ -0,0 +1,145 @@
...
+	kongConsumerTranslationFailureMessages := map[string]string{
+		"consumer-empty-cred":  `credential "empty-cred" failure: failed to provision credential: empty secret`,
+		"consumer-no-username": `no username or custom_id specified`,
+	}
+
+	RunManager(ctx, t, cfg, func(cfg *manager.Config) {
+		// Reducing controllers' cache synchronisation timeout in order to trigger the possible sync timeout quicker.
+		// It's a regression test for https://github.com/Kong/gateway-operator/issues/326.
+		cfg.CacheSyncTimeout = time.Millisecond * 500
+		cfg.IngressClassName = testIngressClassName
```
Comment (czeslavo) [inline test/envtest/kongstate_consumer_failures_test.go:119]: I think we could simply use a default ingress class name and prevent custom manager config this way:

```go
Annotations: map[string]string{annotations.IngressClassKey: annotations.DefaultIngressClass},
```

File: test/envtest/kongstate_consumer_failures_test.go [hunk 11]
```diff
@@ -0,0 +1,145 @@
...
+	// KongConsumer name -> event message
+	kongConsumerTranslationFailureMessages := map[string]string{
+		"consumer-empty-cred":  `credential "empty-cred" failure: failed to provision credential: empty secret`,
+		"consumer-no-username": `no username or custom_id specified`,
+	}
+
+	RunManager(ctx, t, cfg, func(cfg *manager.Config) {
+		// Reducing controllers' cache synchronisation timeout in order to trigger the possible sync timeout quicker.
+		// It's a regression test for https://github.com/Kong/gateway-operator/issues/326.
+		cfg.CacheSyncTimeout = time.Millisecond * 500
```
Comment (czeslavo) [inline test/envtest/kongstate_consumer_failures_test.go:118]: It's not relevant for this test I think.
```suggestion
```

File: test/envtest/setup.go [hunk 12]
```diff
@@ -82,3 +82,18 @@ func Setup(t *testing.T, scheme *runtime.Scheme) *rest.Config {
 
 	return cfg
 }
+
+func InstallKongCRDs(t *testing.T, cfg *rest.Config) {
+	projectRoot := os.Getenv("KONG_TEST_ENVTEST_PROJECT_ROOT")
```
Comment (czeslavo) [inline test/envtest/setup.go:87]: I think we should try to not introduce unnecessary test configs - I bumped into the same issue with installing Kong CRDs in my PR and found a solution that allows you to build an absolute path to the CRDs' directory based on the file runtime metadata, PTAL:

https://github.com/Kong/kubernetes-ingress-controller/pull/4409/files#diff-27c645594dcd9d17888cf588882ed1a2e724b27de898e2b70257cd3e9fbfc247R49

File: internal/dataplane/kongstate/kongstate.go (hunk 8 above)
Comment (randmonkey) [reply internal/dataplane/kongstate/kongstate.go]: done.

File: test/envtest/kongstate_consumer_failures_test.go (hunk 10 above)
Comment (randmonkey) [reply test/envtest/kongstate_consumer_failures_test.go]: done.

File: test/envtest/kongstate_consumer_failures_test.go (hunk 11 above)
Comment (randmonkey) [reply test/envtest/kongstate_consumer_failures_test.go]: removed this.

File: test/envtest/setup.go (hunk 12 above)
Comment (randmonkey) [reply test/envtest/setup.go]: Thanks for providing the `options` to configure envtest. I did some modification on your setup there, and added an `OptionModifier` to allow more flexibility and less touch on existing parts.

File: internal/dataplane/kongstate/kongstate.go (hunk 9 above)
Comment (randmonkey) [reply internal/dataplane/kongstate/kongstate.go]: done.

**Review by czeslavo — DISMISSED** [review]

File: test/envtest/setup.go (hunk 12 above)
Comment (czeslavo) [reply test/envtest/setup.go]: Yeah, I like it this way! 🎖️

**Review by czeslavo — APPROVED** [review]
