### PR TITLE
test: fix specifying kind cluster version

### LINKED ISSUE #2957: Nightly integration tests failing - Kind & Kubernetes 1.25 (test-current-kubernetes)
Integration tests in the nightly workflow (est-current-kubernetes job) are failing due to the following error: 
```
Error: tests failed: can't provide kubernetes version when using an existing cluster
FAIL	github.com/kong/kubernetes-ingress-controller/v2/test/integration	47.022s
```

Sample run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3102816618/jobs/5025633342#step:5:136

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

- fixes the failure when creating a cluster in KIND with specified version
- skip `TestIngressClassRegexToggle` in k8s versions <= 1.21 (EOL now) which does not support namespaced ingress class parameters by default.

**Which issue this PR fixes**:

fixes #2957 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: test/integration/suite_test.go [hunk 1]
```diff
@@ -117,29 +124,16 @@ func TestMain(m *testing.M) {
...
-		// even though that
-		// * our CI runners use ubuntu-latest (which at the time of writing this comment was ubuntu20.04)
-		//   which uses kind v0.14 https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md
-		// * when used with ktf (which at the time of writing this comment was set to v0.19.0) we
-		//   should use kind v0.14 since that what ktf has set as dependency
-		//
-		// With all that said, we still managed to get kind v0.15 on our CI
-		// https://github.com/Kong/kubernetes-ingress-controller/runs/8211490522?check_suite_focus=true#step:5:6
-		// which causes issues down the line (metallb manifests using PSP which is not available
-		// in k8s v1.25+).
```
Comment (pmalek) [inline test/integration/suite_test.go:130]: While I like this change I feel that we'll loose the context of why we need this specific version without this comment.

Having said that: as far as I remember we don't need this anymore after https://github.com/Kong/kubernetes-testing-framework/pull/371 got merged (but we can remove this default version override in a separate PR).

Comment (randmonkey) [reply test/integration/suite_test.go:130]: So what is you suggestion here for using the default kubernetes version? just do not specify a default version, and remove this comment, or put the comment back?

Comment (pmalek) [reply test/integration/suite_test.go:130]: Don't change it in this PR and create a separate one where we don't specify the default (just follow whatever the underlying `kind` uses as default, as it was before the 0.15 breakage for k8s v1.25)

Comment (randmonkey) [reply test/integration/suite_test.go:130]: updated.

**Review by pmalek — APPROVED** [review]
