### PR TITLE
Retrieve ports for rules that use ExternalName Services

### LINKED ISSUE #984: 0.10+ port checks break ExternalName Services
https://github.com/Kong/kubernetes-ingress-controller/pull/845 introduced [a function to find ports from Service definitions](https://github.com/Kong/kubernetes-ingress-controller/commit/229390de3f4ee539b474f20eea800490f288aba8#diff-1785016151d1498b2b8d06b5083cc3d17b64e198245cd752a0f30c40ddd9803cR192). This consistently fails with ExternalName Services, as those do not include ports in their definition.

`getServiceEndpoints()` (which has the ExternalName-specific logic) does expect a port that we've retrieved from elsewhere in both versions that exhibit this issue and those that do not. We likely need to restore the old logic for ExternalNames only. For comparison:

https://github.com/Kong/kubernetes-ingress-controller/blob/1.1.0/internal/ingress/controller/parser/parser.go#L345-L366
https://github.com/Kong/kubernetes-ingress-controller/blob/0.9.1/internal/ingress/controller/parser/parser.go#L1288-L1296

### PR DESCRIPTION
**Pull request by rainest**
**What this PR does / why we need it**:
ExternalName Services have no ports of their own. They only receive ports when combined with an Ingress rule that specifies them.

`findPort()` currently returns an error if no port is available on the Service. ExternalName Services will thus [always return the no port error](https://github.com/Kong/kubernetes-ingress-controller/blob/1.1.0/internal/ingress/controller/parser/parser.go#L183).

This change adds the [0.8 logic for ExternalName Services](https://github.com/Kong/kubernetes-ingress-controller/blob/0.8.0/internal/ingress/controller/parser/parser.go#L1447-L1450) to `findPort()`, which just builds a ServicePort from the requested port. It returns errors from the non-numeric port cases indicating that they are not valid for ExternalNames.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #984

### CODE REVIEW

**Review by mflendrich — DISMISSED** [review]
LGTM, one nit attached (and considerations below).

I am concerned about introduction of `TCP` here - the information passed to `findPort` is not sufficient to determine the protocol; we should be cautious about such silent assumptions if we're willing to add UDP support (#925) soon (I know that the former implementation had TCP hardcoded here).

If you have an idea how to avoid TCP here, please consider changing the solution that way. Otherwise good to go.

**Comment by rainest** [comment]
I think we're kinda just stuck there--ExternalName doesn't specify protocol information either (honestly, it kinda feels like it _should_ include port and protocol information, for exactly this kind of hinting). It may not matter, however, since we're using this to build Kong upstreams, which don't actually care about protocol: their targets are just host/IP+port combinations, with the actual protocol determined by the Kong service using the upstream.

We still need protocol information for constructing the Kong service, and the existing implementation of that is a mixed bag: it's determined by the `konghq.com/protocol` annotation (with an effective `http` default) or via dedicated logic for the Ingress-like resource that uses it. A future UDPIngress will presumably use something similar to the [TCPIngress service construction code](https://github.com/Kong/kubernetes-ingress-controller/blob/1.1.0/internal/ingress/controller/parser/translate.go#L369-L389) that just assumes the protocol without caring about the underlying K8S Service.

Kinda convoluted and messy (more evidence for why Service APIs are needed to radically revamp this ecosystem), but I think it's fine to leave the stub configuration here since we'll ignore it when creating the Kong configuration later anyway.

File: internal/ingress/controller/parser/parser.go [hunk 1]
```diff
@@ -154,13 +154,25 @@ func tcpIngressToNetworkingTLS(tls []configurationv1beta1.IngressTLS) []networki
 func findPort(svc *corev1.Service, wantPort kongstate.PortDef) (*corev1.ServicePort, error) {
 	switch wantPort.Mode {
 	case kongstate.PortModeByNumber:
+		// ExternalName Services have no port declaration of their own
+		// We must assume that the user-requested port is valid and construct a ServicePort from it
+		if svc.Spec.Type == corev1.ServiceTypeExternalName {
+			return &corev1.ServicePort{
+				Protocol:   "TCP",
```
Comment (mflendrich) [inline internal/ingress/controller/parser/parser.go:161]:
```suggestion
```

Comment (mflendrich) [reply internal/ingress/controller/parser/parser.go:161]: @rainest

> I think it's fine to leave the stub configuration here since we'll ignore it when creating the Kong configuration later anyway

In such case we should be able to remove the protocol field whatsoever, right?

**Review by mflendrich — APPROVED** [review]

File: internal/ingress/controller/parser/parser.go (hunk 1 above)
Comment (rainest) [reply internal/ingress/controller/parser/parser.go]: Maybe. Tests pass with it gone, but our coverage isn't great, and my concern is that there's something elsewhere that will try to make use of it and panic if it's nil. The original 0.8 code did include it, so IMO safest thing is to just let that persist. However, grep doesn't show anything in our code that looks like it could use it.
