### PR TITLE
Restart Ingress status leader election cycle after premature exit

### LINKED ISSUE #561: No more ip addresses assigned to ingresses after connection refused from k8s api server
### Summary
The ingress controller (control plane) stops working when the k8s api server is not available for a moment. It no longer assigns an ip address to new ingress resources
This situation does not resolve itself. A restart of the kong ingress controller is required to restore the functionality.
Note, as expected, during this time the proxy remains ok.

**Kong Ingress controller version**
kong-ingress-controller 0.7.0   
setup without db
deployed using helm chart 1.1.1

**Kong or Kong Enterprise version**
kong 1.5.0

### Kubernetes version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.22", GitCommit:"be6e649e67f82e64e43e32119b2b14250a7f9542", GitTreeState:"clean", BuildDate:"2020-01-30T19:02:16Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

### Environment
- **Cloud provider or hardware configuration**:
GKE
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened
An update of the cluster made the k8s api server temporarily unavailable (this could happen also for other reasons eg an upgrade or a crash). From then on, new ingress resources (kubectl get ingress) stopped getting ip addresses
The pods and services are running and accessible, but ingress is not.

### Expected behavior
The ingress is available

### Steps To Reproduce
on a GKE cluster
edit a property of the cluster using the GCE console   (eg  enable autoscaling or enable the kubernetes dashboard)
while the update is going on, the k8s api server is not available
following types of error appear in the ingress controller logs
```
I0306 14:34:07.779492       1 kong.go:66] successfully synced configuration to Kong
I0306 14:42:59.696356       1 kong.go:66] successfully synced configuration to Kong
E0306 14:42:59.753710       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to watch *v1.KongPlugin: Get https://10.18.0.1:443/apis/configuration.konghq.com/v1/kongplugins?resourceVersion=153469748&timeout=7m49s&timeoutSeconds=469&watch=true: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:42:59.753764       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to watch *v1.Secret: Get https://10.18.0.1:443/api/v1/secrets?resourceVersion=153470335&timeout=5m47s&timeoutSeconds=347&watch=true: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:42:59.753785       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to watch *v1.Endpoints: Get https://10.18.0.1:443/api/v1/endpoints?resourceVersion=153473503&timeout=5m6s&timeoutSeconds=306&watch=true: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:42:59.753823       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to watch *v1.KongIngress: Get https://10.18.0.1:443/apis/configuration.konghq.com/v1/kongingresses?resourceVersion=153469744&timeout=6m19s&timeoutSeconds=379&watch=true: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:42:59.753839       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to watch *v1.KongCredential: Get https://10.18.0.1:443/apis/configuration.konghq.com/v1/kongcredentials?resourceVersion=153399704&timeout=5m11s&timeoutSeconds=311&watch=true: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:42:59.753868       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to watch *v1beta1.Ingress: Get https://10.18.0.1:443/apis/networking.k8s.io/v1beta1/ingresses?resourceVersion=153470123&timeout=7m13s&timeoutSeconds=433&watch=true: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:42:59.753873       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to watch *v1.KongConsumer: Get https://10.18.0.1:443/apis/configuration.konghq.com/v1/kongconsumers?resourceVersion=153399704&timeout=8m28s&timeoutSeconds=508&watch=true: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:42:59.753969       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to watch *v1.Service: Get https://10.18.0.1:443/api/v1/services?resourceVersion=153469736&timeout=6m9s&timeoutSeconds=369&watch=true: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:43:00.755496       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.KongPlugin: Get https://10.18.0.1:443/apis/configuration.konghq.com/v1/kongplugins?limit=500&resourceVersion=0: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:43:00.756720       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Secret: Get https://10.18.0.1:443/api/v1/secrets?limit=500&resourceVersion=0: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:43:00.757591       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: Get https://10.18.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:43:00.758488       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.KongIngress: Get https://10.18.0.1:443/apis/configuration.konghq.com/v1/kongingresses?limit=500&resourceVersion=0: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:43:00.759657       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.KongCredential: Get https://10.18.0.1:443/apis/configuration.konghq.com/v1/kongcredentials?limit=500&resourceVersion=0: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:43:00.760559       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1beta1.Ingress: Get https://10.18.0.1:443/apis/networking.k8s.io/v1beta1/ingresses?limit=500&resourceVersion=0: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:43:00.761854       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.KongConsumer: Get https://10.18.0.1:443/apis/configuration.konghq.com/v1/kongconsumers?limit=500&resourceVersion=0: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:43:00.762785       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://10.18.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:43:01.756638       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.KongPlugin: Get https://10.18.0.1:443/apis/configuration.konghq.com/v1/kongplugins?limit=500&resourceVersion=0: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:43:01.757696       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Secret: Get https://10.18.0.1:443/api/v1/secrets?limit=500&resourceVersion=0: dial tcp 10.18.0.1:443: connect: connection refused
```
when the update finishes, the errors stop and the ingress controller appears to be ok
```
I0306 14:46:52.074934       1 kong.go:66] successfully synced configuration to Kong
I0306 14:46:55.400113       1 kong.go:66] successfully synced configuration to Kong
I0306 14:46:58.669002       1 kong.go:66] successfully synced configuration to Kong
I0306 14:47:54.409095       1 kong.go:66] successfully synced configuration to Kong
```
but this is not the case
when you deploy a new application, the services and routes are correctly registered in kong
but the ingress itself is never assigned an ip address
ie.  normally following should be visible in the ingress controller logs
```
I0306 14:11:44.021102       1 status.go:342] updating Ingress xxx status to [{11.111.111.111 }]
```
but this never appears

when you do kubectl get ingress
you can see that no address was assigned for the new ingress resource
the ingress resources that were already present are ok. They still have an address pointing to kong 

just restarting the kong pod resolves the issue
all ingresses now have the ip address of kong
Note that this does not happen immediately: after restart it takes almost 2 minutes for the update to be performed. Following shows the logs after restart. This was only a restart, nothing new was deployed.
```
-------------------------------------------------------------------------------
Kong Ingress controller
  Release:    0.7.0
  Build:      e4605db
  Repository: git@github.com:kong/kubernetes-ingress-controller.git
  Go:         go1.13.1
-------------------------------------------------------------------------------

I0306 17:32:35.995117       1 main.go:407] Creating API client for https://10.18.0.1:443
I0306 17:32:36.007248       1 main.go:451] Running in Kubernetes Cluster version v1.14+ (v1.14.10-gke.22) - git (clean) commit be6e649e67f82e64e43e32119b2b14250a7f9542 - platform linux/amd64
I0306 17:32:36.594323       1 main.go:187] kong version: 1.5.0
I0306 17:32:36.594457       1 main.go:196] Kong datastore: off
I0306 17:32:36.828148       1 controller.go:224] starting Ingress controller
I0306 17:32:36.832248       1 status.go:201] new leader elected: kong-ingress-controller-kong-84cbb69b67-6rw6b
I0306 17:32:37.135013       1 kong.go:66] successfully synced configuration to Kong
I0306 17:32:40.355227       1 kong.go:66] successfully synced configuration to Kong
I0306 17:32:43.628054       1 kong.go:66] successfully synced configuration to Kong
I0306 17:32:46.919831       1 kong.go:66] successfully synced configuration to Kong
I0306 17:33:17.063874       1 status.go:201] new leader elected: kong-ingress-controller-kong-84cbb69b67-tmrkp
I0306 17:33:17.162826       1 kong.go:66] successfully synced configuration to Kong
I0306 17:34:17.074996       1 status.go:342] updating Ingress xxx/xxxx status to [{11.111.111.111 }]
I0306 17:34:17.318395       1 kong.go:66] successfully synced configuration to Kong
```

### PR DESCRIPTION
**Pull request by seh**
**What this PR does / why we need it**:
The leader election procedure that ensures no more than one Kong ingress controller will update _Ingress_ "status" subresources should run for the life of the process. However, if the leader renewal attempts take longer than the configured ["renewal deadline"](https://pkg.go.dev/k8s.io/client-go/tools/leaderelection?tab=doc#LeaderElectionConfig) (15 seconds) to succeed, the election procedure terminates.

Since the ingress controller continues running even after such repeated election failure, ensure that the procedure starts again. Delay each restart via exponential backoff.

**Which issue this PR fixes**:
Fixes #561.

**Special notes for your reviewer**
I found that _staticcheck_ is displeased with a lot of this code base. I resolved several of its complaints in this patch (unused fields, nil passed as an argument to a `context.Context` parameter).

Also, as part of testing this patch, I noticed that Kong is susceptible to the following issues:
- kubernetes/kubernetes#84729
- kubernetes/kubernetes#87800

Please see these related patches and the discussion that's still underway:
- kubernetes/kubernetes#84737
- kubernetes/kubernetes#84801
- kubernetes/kubernetes#85216
- kubernetes/kubernetes#87821

### CODE REVIEW

**Comment by seh** [comment]
I revised the shutdown procedure several times, looking to make sure that we only write to _Ingress_ objects so long as we know we're the current leader. I also made the `(*KongController).Stop` method block until all background work is complete. That way, the program won't exit prematurely after receiving a TERM signal (the ten second delay in `handleSigterm` notwithstanding).

File: internal/ingress/election/election.go [hunk 1]
```diff
@@ -76,11 +99,12 @@ func NewElector(config Config) Elector {
...
-			LeaseDuration: ttl,
-			RenewDeadline: ttl / 2,
-			RetryPeriod:   ttl / 4,
-			Callbacks:     config.Callbacks,
+			Lock:            &lock,
+			LeaseDuration:   ttl,
+			RenewDeadline:   ttl / 2,
+			RetryPeriod:     ttl / 4,
+			Callbacks:       config.Callbacks,
+			ReleaseOnCancel: true,
```
Comment (seh) [inline internal/ingress/election/election.go]: My testing today shows that this option does not work as intended: the _ConfigMap_ does not get updated when the `context.Contex` passed to `(*LeaderElector).Run` is done. There's no failure reported in the log. I'm still investigating what could be causing that.

Comment (seh) [reply internal/ingress/election/election.go]: By way of using the Go modules `replace` directive and instrumenting the _client-go_ library, I figured out that this _does_ work—when the process doesn't die too soon. I spent about five hours today experimenting with changes to the shutdown sequence, and had to stop my work for the day before I could offer a proven solution. More detail tomorrow.

File: internal/ingress/controller/controller.go [hunk 2]
```diff
@@ -271,18 +296,22 @@ func (n *KongController) Stop() error {
...
-	close(n.stopCh)
-	go n.syncQueue.Shutdown()
 	if n.syncStatus != nil {
+		// Finish writing to any Ingress objects before giving up leadership.
 		n.syncStatus.Shutdown(n.elector.IsLeader())
 	}
+	glog.Infof("shutting down controller queues")
+	// Closing the stop channel will cause us to give up leadership.
+	close(n.stopCh)
+	n.syncQueue.Shutdown()
```
Comment (seh) [inline internal/ingress/controller/controller.go]: These two lines need to flip. If we close the `n.stop` channel before stopping the queue, the worker goroutine terminates, and the `Shutdown` method never completes, waiting on a channel to be closed. If instead we call `Shutdown` on the queue first, the worker goroutine sees that the queue is shutting down and stops consuming items.

File: internal/ingress/election/election.go (hunk 1 above)
Comment (seh) [reply internal/ingress/election/election.go]: It came down to how the `main` function was arranged. `main` blocked on `(*KongController).Start`. The signal handler started by `main` calls `(*KongController).Stop`. When `Stop` closes the the `KongController.stopCh` channel, `(*KongController).Start` returns. That allowed `main` to return before `(*KongController).Stop` had completed, interrupting the various intended termination procedures.

I revised how `main` interacts with the `handleSigterm` function. Rather than having the latter terminate the program, it instead indicates that it's complete by sending a recommended exit code to a channel. `main` blocks on receiving that exit code and exits when it's sure that it's safe to do so.

**Comment by seh** [comment]
With these changes, Kong now shuts down cleanly—stopping its work queues, releasing a held leader lock, draining its HTTP server—and hands off leadership to another Kong instance in 7.5 seconds or less (per `leaderelection.LeaderElectionConfig.RetryPeriod`, set to 30 seconds divided by four).

**Comment by seh** [comment]
@hbagdi, I rebased this atop "master" today, so it's up to date with [the 0.8.0 realese](https://github.com/Kong/kubernetes-ingress-controller/releases/tag/0.8.0).

We're interested in getting this merged, to alleviate problems we're suffering in production, so I'd appreciate your feedback.

File: internal/ingress/election/election.go [hunk 3]
```diff
@@ -35,9 +36,31 @@ type elector struct {
 	elector *leaderelection.LeaderElector
 }
 
-func (e elector) Run() {
-	// TODO pass the correct context in here
-	e.elector.Run(context.Background())
+func (e elector) Run(ctx context.Context) {
+	backoff := flowcontrol.NewBackOff(1*time.Second, 15*time.Second)
+
+	for session := 0; ; {
```
Comment (hbagdi) [inline internal/ingress/election/election.go:42]: Let's rename this to `retryCount` and define it in the method itself and change the for loop to be infinite:

```go
for {
}
```

File: internal/ingress/election/election.go [hunk 4]
```diff
@@ -35,9 +36,31 @@ type elector struct {
...
+		select {
+		case <-ctx.Done():
+			return
+		default:
+			first := session == 0
+			session++
+			if !first {
```
Comment (hbagdi) [inline internal/ingress/election/election.go:49]: nit: A more readable comparison here would be to do `if retryCount > 0 {`

File: internal/ingress/election/election.go [hunk 5]
```diff
@@ -35,9 +36,31 @@ type elector struct {
...
+				const id = ""
```
Comment (hbagdi) [inline internal/ingress/election/election.go:50]: Can we please add a name here for the `id`?
I don't have a very good name myself but something along the lines of `kong-leader-election` would be fine.
Please move the definition of this outside the loop and at the method level itself.

File: internal/ingress/election/election.go [hunk 6]
```diff
@@ -35,9 +36,31 @@ type elector struct {
...
+				backoff.Next(id, backoff.Clock.Now())
+				delay := backoff.Get(id)
+				glog.Warningf("leader election session %d terminated unexpectedly; waiting %s before proceeding", session, delay)
```
Comment (hbagdi) [inline internal/ingress/election/election.go:53]: Please rename session to retry count.

File: internal/ingress/controller/controller.go [hunk 7]
```diff
@@ -226,25 +230,47 @@ type KongController struct {
...
+		goTallied(func() {
+			n.syncStatus.Run()
+		})
 	}
 
-	go n.syncQueue.Run(time.Second, n.stopCh)
-	// force initial sync
+	goTallied(func() {
+		n.syncQueue.Run(time.Second, n.stopCh)
+	})
```
Comment (hbagdi) [inline internal/ingress/controller/controller.go:265]: Can you simplify this code by using https://godoc.org/golang.org/x/sync/errgroup package?
There is no need of collecting errors but other than that, errgroup package can make this simpler.

File: cli/ingress-controller/main.go [hunk 8]
```diff
@@ -397,12 +402,13 @@ func main() {
...
 	kong.Start()
+	wg.Wait()
+	os.Exit(<-exitCh)
 }
 
 type exiter func(code int)
 
-func handleSigterm(kong *controller.KongController, stopCh chan struct{},
-	exit exiter) {
+func handleSigterm(kong *controller.KongController, stopCh chan<- struct{}, exit chan<- int) {
```
Comment (hbagdi) [inline cli/ingress-controller/main.go:411]: nit: Can we rename the `exit` channel to `exitCh` to make the code easier to follow?

File: cli/ingress-controller/main.go [hunk 9]
```diff
@@ -554,5 +554,19 @@ func registerHandlers(enableProfiling bool, port int, ic *controller.KongControl
 		WriteTimeout:      300 * time.Second,
 		IdleTimeout:       120 * time.Second,
 	}
-	glog.Fatal(server.ListenAndServe())
+	var wg sync.WaitGroup
+	go func() {
+		<-stop
+		wg.Add(1)
```
Comment (hbagdi) [inline cli/ingress-controller/main.go:560]: Can this race with `wg.Wait()` on line 571?
What is the reason for not adding first and then blocking?

Comment (seh) [reply cli/ingress-controller/main.go:560]: I went back and forth on this one several times. I agree that it looks unusual. My concern is this: It's possible for `(*http.Server).ListenAndServe` to fail immediately, before the goroutine launched at line 558 ever starts running. If `ListenAndServe` fails like that, but we had incremented the `WaitGroup` already, we'll then get stuck waiting on it later. Conversely, if we return from the function without waiting when `ListenAndServer` fails without returning `http.ErrServerClosed`—which it can also do in response to being shut down—then we won't wind up waiting for `(*http.Server).Shutdown` to complete its work. Hence, incrementing the `WaitGroup` only after we've received a signal (or for any other reason that the `stop` channel becomes available) ensures that we only wait on graceful shutdown if we know we're about to initiate that shutdown.

If we make it to line 571 and that goroutine has either not started yet or the `stop` channel remains unavailable, then we haven't started a graceful shutdown, and it's fine to proceed out of the function.

One way to appease your concern is to introduce yet another channel. The goroutine would block on either the `done` or this new channel becoming available. We'd close the new channel here if `(*http.Server).ListenAndServe` exits. I'll post that solution shortly.

Comment (seh) [reply cli/ingress-controller/main.go]: Please see commit 6cd76eb1ad90e4485d13a768ff584cdd7702e774 and let me know if that's more to your liking.

File: internal/ingress/controller/controller.go (hunk 7 above)
Comment (seh) [reply internal/ingress/controller/controller.go:262]: Yes, [`(*errgroup.Group).Go` is `goTallied`](https://github.com/golang/sync/blob/master/errgroup/errgroup.go#L51-L66), with the extra error collection. In our case, none of these functions return errors, so we still need to wrap them.

Please see commit bc353043b503ff2062ce6d1786eab508d5b46d80 and let me know if that's more to your liking.

File: cli/ingress-controller/main.go (hunk 9 above)
Comment (hbagdi) [reply cli/ingress-controller/main.go]: I think this will be a little more robust and avoid the race between the two go routines.

Thanks, Steven!

**Comment by hbagdi** [comment]
@seh Please fill in the contributor form to claim your Kong swag: https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#contributor-t-shirt

I forgot to post these before.
