### PR TITLE
fix: bump deck to handle Certificate updates in Konnect sync properly

### LINKED ISSUE #4384: KIC fails to sync with Konnect when updating Certificate
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When an existing `Certificate` generated out of a Kubernetes Secret gets updated, KIC fails to synchronise with Konnect's Runtime Group's Admin API with the following error:

```
time="2023-07-18T14:35:44Z" level=warning msg="Failed pushing configuration to Konnect" error="performing update for https://us.kic.api.konghq.com/kic/api/runtime_groups/5afc1090-6bc7-4b2a-a252-14f28fe1ac57 failed: 1 errors occurred:\n\twhile processing event: {Update} certificate 1fecb0e6-0674-43cd-8d1c-b4446fc23f90 failed: HTTP status 400 (message: \"proto: (line 1:5535): unknown field \\\"snis\\\"\")\n"
```

It's a result of a bug in deck that was already fixed in https://github.com/Kong/deck/pull/978.

### Expected Behavior

KIC succeeds to update existing certificates when syncing with Konnect's Runtime Group's Admin API.

### Steps To Reproduce

```markdown
1. Create an `Ingress` with `tls.[].secretName` pointing to a tls `Secret`.
2. Let KIC synchronise config with Gateways and Konnect (expect no errors).
3. Modify the `Secret`'s by replacing its key and crt with another valid pair. 

This will cause KIC to fail synchronise with the following error in logs:


time="2023-07-18T14:35:44Z" level=warning msg="Failed pushing configuration to Konnect" error="performing update for https://us.kic.api.konghq.com/kic/api/runtime_groups/5afc1090-6bc7-4b2a-a252-14f28fe1ac57 failed: 1 errors occurred:\n\twhile processing event: {Update} certificate 1fecb0e6-0674-43cd-8d1c-b4446fc23f90 failed: HTTP status 400 (message: \"proto: (line 1:5535): unknown field \\\"snis\\\"\")\n"
```

### Kong Ingress Controller version

```shell
v2.10.3
```

### Kubernetes version

_No response_

### Anything else?

Although https://github.com/Kong/deck/pull/978 is already merged in deck, it's not released yet. We need to wait for v1.24.0 to be released.

### PR DESCRIPTION
**Pull request by czeslavo**
**What this PR does / why we need it**:

Bumps deck to a version that fixes #4384 (in this particular [commit](https://github.com/Kong/deck/commit/e337551d3e70004379f952eb3a91ff5af1deb5ec)). Propagates `IsKonnect` flag when creating `diff.Syncer`.

The Certificate update case is now covered in deck's [integration tests](https://github.com/Kong/deck/blob/e337551d3e70004379f952eb3a91ff5af1deb5ec/tests/integration/sync_test.go#L3465). 

**Which issue this PR fixes**:

Closes #4384.

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/dataplane/sendconfig/dbmode.go [hunk 1]
```diff
@@ -59,12 +71,13 @@ func (s UpdateStrategyDBMode) Update(ctx context.Context, targetContent ContentW
 		TargetState:     ts,
 		KongClient:      s.client,
 		SilenceWarnings: true,
+		IsKonnect:       s.isKonnect,
 	})
 	if err != nil {
 		return fmt.Errorf("creating a new syncer for %s: %w", s.client.BaseRootURL(), err), nil, nil
 	}
 
-	_, errs := syncer.Solve(ctx, s.concurrency, false)
```
Comment (czeslavo) [inline internal/dataplane/sendconfig/dbmode.go:67]: Apparently, this `deck` release made a breaking change in the syncer API. It extends `Solve` method with a parameter `isJSONOut` which when turned `true`, returns a non-empty `EntityChanges` struct as a third return value (it includes stats about objects CRUD actions). I set it to false as we won't use it.

**Review by pmalek — APPROVED** [review]
