### PR TITLE
test(e2e): set appProtocol to HTTP for kuma tests

### LINKED ISSUE #5498: Constant e2e failures against unreleased Kong with Kuma
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Recently the daily e2e run against unreleased Kong fails on the 2 cases running with kuma:
 https://github.com/Kong/kubernetes-ingress-controller/actions/runs/7683416231/job/20938806328#logs
- `TestDeployAllInOnePostgresKuma`
- `TestDeployAllInOneDBLessKuma`
Also the validate Kong image tests against `kong/kong-gateway-dev:3.6.0.0-rc1` fails in the same cases:
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/7675532503
The behaviors in the tests are the same: requests are only sent to 2 backend pods but expected all 3 pods:
```
    kuma_test.go:36: waiting for route from Ingress to be operational at http://172.18.128.1/echo and forward traffic to all 3 backends
    kuma_test.go:36: 
        	Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/e2e/helpers_test.go:488
        	            				/opt/hostedtoolcache/go/1.21.6/x64/src/runtime/asm_amd64.s:1650
        	Error:      	"map[With IP address 10.244.0.15.
        	            	
        	            	:{} With IP address 10.244.0.17.
        	            	
        	            	:{}]" should have 3 item(s), but has 2
```

### Expected Behavior

e2e test passes.

### Steps To Reproduce

```markdown
Run e2e tests TestDeployAllInOnePostgresKuma or TestDeployAllInOneDBLessKuma
```

### Kong Ingress Controller version

```shell
`latest` image  3.0.2.
```

### Kubernetes version

All supported k8s versions in this run:
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/7675532503
```
- 1.29.0
- 1.28.0
- 1.27.4
- 1.26.6
- 1.25.11
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

As discussed internally, setting `appProtocol` to `HTTP` will make kuma to load balance at request level. While by default kuma may only load balance at the connection level. When Kong gateway changed the `upstream_keepalive_max_requests` from 1000 to 10000: https://github.com/Kong/kong/pull/12223, the upstream connection is reused during all the test which only send about 3000 requests. So the requests constantly go to the same backend pod from one Kong gateway pod. 

I changed `appProtocol` to `http`, the failure disappears in my local run.

**Which issue this PR fixes**:

maybe fix #5498 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

~- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~ No changelog required

### CODE REVIEW

File: test/e2e/helpers_test.go [hunk 1]
```diff
@@ -411,6 +411,9 @@ func deployIngressWithEchoBackends(ctx context.Context, t *testing.T, env enviro
 
 	t.Logf("exposing deployment %s via service", deployment.Name)
 	service := generators.NewServiceForDeployment(deployment, corev1.ServiceTypeClusterIP)
+	for i := range service.Spec.Ports {
+		service.Spec.Ports[i].AppProtocol = lo.ToPtr("http")
```
Comment (czeslavo) [inline test/e2e/helpers_test.go:415]: Maybe let's leave a comment explaining _why_.
```suggestion
    // Set Service's appProtocol to http so that Kuma load-balances requests on HTTP-level instead of TCP. 
    // TCP load-balancing proved to cause issues with not distributing load evenly in short time spans like in this test.
    // Ref: https://github.com/Kong/kubernetes-ingress-controller/issues/5498
		service.Spec.Ports[i].AppProtocol = lo.ToPtr("http")
```

**Review by czeslavo — DISMISSED** [review]

**Review by programmer04 — APPROVED** [review]
🏅
