### PR TITLE
fix(status) update non-http upstream Ingresses

### LINKED ISSUE #1991: Ingresses for GRPC/GRPCS/HTTPS Services get no status information
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Create an Ingress with `konghq.com/protocols: grpc,grpcs` and a Service with `konghq.com/protocol: grpc`. Use a LoadBalancer Service for the Kong proxy and wait for config to sync successfully. The controller will not update the Service status subResource.

### Expected Behavior

The controller sets the proxy Service's IPs in the Ingress status.

### Steps To Reproduce

```markdown
See Current Behavior. Not directly verified, based on a community chat report and code review.
```

### Kong Ingress Controller version

```shell
2.0.5
```

### Kubernetes version

```shell
Irrelevant
```

### Anything else?

The status update loop uses a switch on the Kong config service protocol to determine whether it needs to update a TCPIngress, UDPIngress, or Ingress resource. The only supported protocols are currently `tcp`, `udp`, and `http`: https://github.com/Kong/kubernetes-ingress-controller/blob/96ad4eed05775830f583bf75a1da38ec33b64e24/internal/ctrlutils/ingress-status.go#L139-L163

There are a number of other allowed protocols, all of which should update an Ingress: https://docs.konghq.com/gateway-oss/2.6.x/admin-api/#add-service

### PR DESCRIPTION
**Pull request by rainest**
**What this PR does / why we need it**:
Currently, we don't update Ingresses or Ingress-likes unless their associated Kong service's protocol is tcp, udp, or http. This adds the rest of the protocols (https, grpc, grpcs) that should result in an Ingress update.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1991

**Special notes for your reviewer**:

The test confirms the status update now works, but not much anything else, largely owing to my lack of familiarity with gRPC. I initially tried this after the status check:

```
	t.Log("waiting for routes from Ingress to be operational")
	require.Eventually(t, func() bool {
		conn, err := grpc.Dial(fmt.Sprintf("%s:%s", proxyURL.Hostname(), "443"), grpc.WithInsecure())
		if err != nil {
			t.Logf("error connecting to %s:%s: %v", proxyURL.Hostname(), "443", err)
			return false
		}
		defer conn.Close()
		client := pb.NewGRPCBinClient(conn)
		res, err := client.DummyUnary(ctx, &pb.DummyMessage{
			FString: "hello",
			FInt32:  42,
		})
		if err != nil {
			t.Logf("failed to send gRPC request: %v", err)
			return false
		}
		fmt.Println(res)
		return true
	}, ingressWait, waitTick)

	t.Log("deleting Ingress")
	require.NoError(t, clusters.DeleteIngress(ctx, env.Cluster(), ns.Name, ingress))
```
using [grpcbin](https://github.com/moul/grpcbin)'s test client stuff (as `pb`) to avoid the (considerable) boilerplate in the grpc-go examples. This just nets me a "connection closed before server preface received" error. Though the route looks similar to our [standard gRPC documentation](https://docs.konghq.com/gateway-oss/2.6.x/getting-started/configuring-a-grpc-service/), but it doesn't respond to the example grpcurl there (it gets a 503 on requests for `/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo` instead, but without errors in the proxy that would suggest a DNS failure).

So not really sure how to make the rest of that work, but it's not necessary for the change this tests.

An additional note: we have a `grpc` option for routes, but I don't think it can ever work--we don't support plaintext HTTP/2 at all because NGINX doesn't support it, so any attempt to do that results in a 400.

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: test/integration/ingress_test.go [hunk 1]
```diff
@@ -173,6 +173,72 @@ func TestIngressEssentials(t *testing.T) {
...
+		annotations.AnnotationPrefix + annotations.ProtocolsKey: "grpc,grpcs",
+		annotations.AnnotationPrefix + annotations.StripPathKey: "false",
+	}, service)
+	require.NoError(t, clusters.DeployIngress(ctx, env.Cluster(), ns.Name, ingress))
+
+	defer func() {
+		t.Log("cleaning up Ingress resource")
+		if err := clusters.DeleteIngress(ctx, env.Cluster(), ns.Name, ingress); err != nil {
+			if !errors.IsNotFound(err) {
+				require.NoError(t, err)
```
Comment (shaneutt) [inline test/integration/ingress_test.go:218]: This is done elsewhere in this patch, but generally we use `asserts` for cleanup instead of requires, the idea being that if one cleanup fails we still want to at least try and perform the others:
```suggestion
				assert.NoError(t, err)
```

**Review by shaneutt — DISMISSED** [review]
LGTM, just one comment :+1: 

Ultimately it sounds like we need to add full integration tests for grpc, I don't think we should block this simple fix on that but I would like to see us create a followup issue for this before we consider this PR resolved and merge it.

**Review by shaneutt — APPROVED** [review]
