### PR TITLE
fix(controller): Do not update existing Programmed condition to Unknown

### LINKED ISSUE #6386: Data race on updating status of KongConsumer/KongConsunmerGroup
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

From FTI-6157.
Customer uses sidecar mode to deploy KIC. When KIC is scaled, multiple KIC are updating the status of the same `KongConsumer`, so lots of reconcile errors occur and may produce excessive requests to k8s APIserver and make other controllers stuck. 

### Expected Behavior

No race happens causing reconciliation errors when multiple instances of KIC are reconciling the same `KongConsumer` or `KongConsumerGroup`.

### Steps To Reproduce

```markdown
1. Deploy KIC with sidecar mode
2. Create a KongConsumer in the cluster
3. Scale the KIC to 3 replicas
4. Check the log of new created KIC pods, and we can see `Reconcile error` or `Reconciler error` happens on KongConsumer because of conflict on updating their status.
```

### Kong Ingress Controller version

```shell
2.11 and later
```

### Kubernetes version

```shell
Not relevant.
```

### Anything else?

Customer need the fix to be backported to 2.12.x LTS.

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

In sidecar deployment mode, when new pod KIC pod is up to reconcile resources like `KongConsumers`, the programmed condition in status would be `Unknown` before the first successful applying configuration to Kong gateway. This will cause flips of status of `KongConsumer` and races on updates. thus producing excessive reconciliation requests and heavy load to API server.

The PR ignores the update of `Programmed` condition when the status is `Unknown` and there are existing `Programmed` condition in the status. 
**Which issue this PR fixes**:

fixes #6386 

**Special notes for your reviewer**:

I did not update the changelog in the PR to prevent from conflicts on automatically created backport PRs.

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: hack/generators/controllers/networking/main.go [hunk 1]
```diff
@@ -725,8 +725,13 @@ func (r *{{.PackageAlias}}{{.Kind}}Reconciler) Reconcile(ctx context.Context, re
 		{{- end }}
 
 		{{- if .ProgrammedCondition.UpdatesEnabled }}
-		log.V(logging.DebugLevel).Info("Updating programmed condition status", "namespace", req.Namespace, "name", req.Name)
 		configurationStatus := r.DataplaneClient.KubernetesObjectConfigurationStatus(obj)
+		log.V(logging.DebugLevel).Info("Updating programmed condition status", "namespace", req.Namespace, "name", req.Name, "configuration_status",configurationStatus)
+		// REVIEW: Should we try to fetch the latest version of updated object to reduce probalility of race on update?
```
Comment (czeslavo) [inline hack/generators/controllers/networking/main.go:730]: I think we should be fine with just using the object fetched from the cache at the beginning of the reconciliation. As I understand, the issue we had was caused by concurrent writes with different statuses that made the "old" instances fight with the "new" instances. Now, if we skip updates to `Unknown` status from "new" instances, there will be no fight between them.

Comment (randmonkey) [reply hack/generators/controllers/networking/main.go]: Done.

**Review by czeslavo — APPROVED** [review]
