### PR TITLE
fix(kong_client): return error in fetching listeners when no ready kong clients

### LINKED ISSUE #7015: Gateway API Objects applied while Kong Gateway Pod is restarting causes UnsupportedProtocol state
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

1. Install GW API CRDs
2. Install KIC + GW
3. Lay down a GatewayClass, Gateway, and HTTPRoute
4. We see everything is accepted / programmed
5. Now we roll the GW pod and delete and recreate the GW API objects in quick succession
6. We now see our Gateway object is stuck in the following state and never recovers

```
Status:
  Addresses:
    Type:   Hostname
    Value:  <elb_address>.elb.us-east-2.amazonaws.com
  Conditions:
    Last Transition Time:  2025-01-21T16:46:04Z
    Message:               this unmanaged gateway has been picked up by the controller and will be processed
    Observed Generation:   1
    Reason:                Accepted
    Status:                True
    Type:                  Accepted
    Last Transition Time:  2025-01-21T16:46:04Z
    Message:
    Observed Generation:   1
    Reason:                Programmed
    Status:                True
    Type:                  Programmed
  Listeners:
    Attached Routes:  1
    Conditions:
      Last Transition Time:  2025-01-21T16:46:04Z
      Message:               no Kong listen with the requested protocol is configured
      Observed Generation:   1
      Reason:                UnsupportedProtocol
      Status:                False
      Type:                  Accepted
      Last Transition Time:  2025-01-21T16:46:04Z
      Message:
      Observed Generation:   1
      Reason:                Invalid
      Status:                False
      Type:                  Programmed
    Name:                    proxy
    Supported Kinds:
      Group:  gateway.networking.k8s.io
      Kind:   HTTPRoute
      Group:  gateway.networking.k8s.io
      Kind:   GRPCRoute
```
7) Delete and recreate the GWAPI objects again once the GW is up and running

```
Status:
  Addresses:
    Type:   Hostname
    Value:  <elb_address>.elb.us-east-2.amazonaws.com
  Conditions:
    Last Transition Time:  2025-01-21T17:01:53Z
    Message:               this unmanaged gateway has been picked up by the controller and will be processed
    Observed Generation:   1
    Reason:                Accepted
    Status:                True
    Type:                  Accepted
    Last Transition Time:  2025-01-21T17:01:53Z
    Message:
    Observed Generation:   1
    Reason:                Programmed
    Status:                True
    Type:                  Programmed
  Listeners:
    Attached Routes:  1
    Conditions:
      Last Transition Time:  2025-01-21T17:01:54Z
      Message:
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2025-01-21T17:01:54Z
      Message:
      Observed Generation:   1
      Reason:                NoConflicts
      Status:                False
      Type:                  Conflicted
      Last Transition Time:  2025-01-21T17:01:54Z
      Message:
      Observed Generation:   1
      Reason:                Programmed
      Status:                True
      Type:                  Programmed
      Last Transition Time:  2025-01-21T17:01:54Z
      Message:
      Observed Generation:   1
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Name:                    proxy
    Supported Kinds:
      Group:  gateway.networking.k8s.io
      Kind:   HTTPRoute
      Group:  gateway.networking.k8s.io
      Kind:   GRPCRoute
Events:       <none>
```

### Expected Behavior

The KIC should be able to recover in the event that a configuration is made while the Gateway is not in a ready state. This is especially important for clients who are using ArgoCD for instance which does blanket kubectl applys

### Steps To Reproduce

```markdown
Detailed above
```

### Kong Ingress Controller version

```shell
3.4.X
```

### Kubernetes version

```shell
1.30
```

### Anything else?

[values.zip](https://github.com/user-attachments/files/18495053/values.zip)

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

Return an error when no ready clients in fetching listeners. It will trigger a `Reconciler Error` in setting listener status in reconciling `Gateway`s.

**Which issue this PR fixes**:

fixes #7015
**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/dataplane/kong_client.go [hunk 1]
```diff
@@ -340,7 +340,18 @@ func (c *KongClient) Listeners(ctx context.Context) ([]kong.ProxyListener, []kon
 	// between reading the client(s) and setting the last applied SHA via client's
 	// SetLastConfigSHA() method. It's not ideal but it should do for now.
 	c.lock.RLock()
-	for _, cl := range c.clientsProvider.GatewayClients() {
+	gwClients := c.clientsProvider.GatewayClients()
+	c.logger.V(logging.DebugLevel).Info("Getting listeners from clients", "clients", lo.Map(gwClients, func(cl *adminapi.Client, _ int) string {
+		return cl.BaseRootURL()
+	}))
+	// If there are no ready clients yet, we should return an error.
+	// REVIEW: define a certain error type to let the gateway controller to requeue the `Gateway` with custom strategy when this happen?
```
Comment (pmalek) [inline internal/dataplane/kong_client.go:348]: 👍 Sounds like a good idea. And that error shouldn't be returned by the `Reconcile` func but only logged in the controller. It's not an application error but rather a transient error which will be fixed at some point.

File: internal/controllers/gateway/gateway_controller.go [hunk 2]
```diff
@@ -583,6 +585,18 @@ func (r *GatewayReconciler) reconcileUnmanagedGateway(ctx context.Context, log l
 		debug(log, gateway, "Determining listener configurations from Kong data-plane")
 		kongListeners, err = r.determineListenersFromDataPlane(ctx, svc, kongListeners)
 		if err != nil {
+			errNoReadyClient := dataplane.NoReadyGatewayClientsError{}
+			if errors.As(err, &errNoReadyClient) {
```
Comment (pmalek) [inline internal/controllers/gateway/gateway_controller.go:589]: If we don't use the error, we can:

```suggestion
			if errNoG := (&dataplane.NoReadyGatewayClientsError{}); errors.As(err, &errNoG) {
```

File: internal/controllers/gateway/gateway_controller.go [hunk 3]
```diff
@@ -583,6 +585,18 @@ func (r *GatewayReconciler) reconcileUnmanagedGateway(ctx context.Context, log l
...
+				// Requeue the request to reconcile the gateway again after `retryAfter` but not return the error to trigger a Reconcile Error
+				// when no gateway is available to fetch information of listeners.
+				// REVIEW: Should we implement some exponential backoff strategy here instead of a fixed retry delay?
```
Comment (pmalek) [inline internal/controllers/gateway/gateway_controller.go:592]: This will be handled by the controller-runtime framework if we do not set the `RequeueAfter` but only set the `Requeue`. I'd suggest we go this route.

File: CHANGELOG.md [hunk 4]
```diff
@@ -122,6 +122,10 @@ Adding a new version? You'll need three changes:
   where KIC is permitted to access only the given workspace but cannot access
   `/status` endpoint.
   [#7233](https://github.com/Kong/kubernetes-ingress-controller/pull/7233)
+- Return error when no ready Kong admin API clients in fetching listeners in
+  the reconciliation of `Gateway`s to trigger a requeue when no Kong gateways
+  are available.
```
Comment (pmalek) [inline CHANGELOG.md:127]: I think we can reword this to make it a little more clear, how about:

```suggestion
- Report an error and requeue when there are no ready Kong admin API clients
  during the reconciliation of `Gateway`s.
```

File: internal/controllers/gateway/gateway_controller.go (hunk 2 above)
Comment (randmonkey) [reply internal/controllers/gateway/gateway_controller.go]: Done.

File: internal/controllers/gateway/gateway_controller.go (hunk 3 above)
Comment (randmonkey) [reply internal/controllers/gateway/gateway_controller.go]: Changed like this.
