### PR TITLE
fix(controller): set creationTimestamp of ancestors of KongUpstreamPolicy status

### LINKED ISSUE #6757: creationTimestamp in anscestor status of KongUpstreamPolicy is not set
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Found in investigating #6497.
The `creationTimestamp` of ancestorStatus in status of `KongUpstreamPolicy` is not correctly set: 
https://github.com/Kong/kubernetes-ingress-controller/blob/eb19b4edab38af6c6072fd03e4a7ff995f9d6e40/internal/controllers/configuration/kongupstreampolicy_utils.go#L299-L308
https://github.com/Kong/kubernetes-ingress-controller/blob/eb19b4edab38af6c6072fd03e4a7ff995f9d6e40/internal/controllers/configuration/kongupstreampolicy_utils.go#L317-L326
We can see the `creationTimestamp` was not set in ancestor status. So in the later phase of building status of `KongUpstreamPolicy` where we sort ancestors by `creationTimestamp`, ancestors was actually not correctly sort. 
So the order of multiple ancestors may change even the status of `KongUpstreamPolicy` should not be changed.

### Expected Behavior

Order of ancestors in status of `KongUptreamPolicy` should not change when the actual status of ancestors not changed.

### Steps To Reproduce

```markdown
1. Create a KongUpstreamPolicy
2. Create multiple Services, and attach the KongUpstreamPolicy to them
3. Use the services as backends of Ingresses/HTTPRoutes to let KIC to reconcile the KongUpstreamPolicy
4. The order of ancestors in KongUpstreamPolicy's status is constantly changing
```

### Kong Ingress Controller version

```shell
Reported in KIC 3.2.3
```

### Kubernetes version

```shell
Not relevant
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

Set creationTimestamp of ancestor status in `KongUpstreamPolicy` to fix the sorting of ancestors in `KongUpstreamPolicy` status.
This fixes an issue where status of `KongUpstreamPolicy` is continuously updated even nothing changed.

**Which issue this PR fixes**:

fixes #6757 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/controllers/configuration/kongupstreampolicy_utils.go [hunk 1]
```diff
@@ -416,8 +418,19 @@ func (r *KongUpstreamPolicyReconciler) buildPolicyStatus(
 	ancestorsStatus []ancestorStatus,
 ) (gatewayapi.PolicyStatus, error) {
 	// Sort the ancestors by creation timestamp and keep only the oldest ones.
+	// If multiple ancestors have the same creation timestamp, sort by kind, namespace and name.
 	sort.Slice(ancestorsStatus, func(i, j int) bool {
-		return ancestorsStatus[i].creationTimestamp.Before(&ancestorsStatus[j].creationTimestamp)
+		if !ancestorsStatus[i].creationTimestamp.Equal(&ancestorsStatus[j].creationTimestamp) {
+			return ancestorsStatus[i].creationTimestamp.Before(&ancestorsStatus[j].creationTimestamp)
+		}
+		// REVIEW: the condition will make KongServiceFacade be prior to Service. Should we customize the comparing of kinds here?
```
Comment (pmalek) [inline internal/controllers/configuration/kongupstreampolicy_utils.go:426]: I think it's OK to leave as is making this "group" the ancestors by kind.

File: CHANGELOG.md [hunk 2]
```diff
@@ -161,6 +161,10 @@ Adding a new version? You'll need three changes:
   point to a `Gateway` as they can point to other kinds of resources like
   `Service` when used in service mesh solutions.
   [#6692](https://github.com/Kong/kubernetes-ingress-controller/pull/6692)
+- Set creationTimestamp of ancestor in ancestor status of `KongUpstreamPolicy`
```
Comment (pmalek) [inline CHANGELOG.md:164]:
```suggestion
- Set `creationTimestamp` of ancestor in ancestor status of `KongUpstreamPolicy`
```

**Review by pmalek — DISMISSED** [review]

**Review by pmalek — APPROVED** [review]
