### PR TITLE
fix: parse ttl to int in key auth credentials

### LINKED ISSUE #2734: Int fields in credential Secrets incorrectly handled as strings
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Creating a key-auth credential secret with a `ttl=1000` field fails to create a credential, because it is parsed as a string:

```
time=“2022-06-30T23:37:36Z” level=error msg=“failed to provision credential: failed to decode key-auth credential: failed to decode credential: 1 error(s) decoding:\n\n* ‘ttl’ expected type ‘int’, got unconvertible type ‘string’, value: ‘1000’” kongconsumer_name=harry kongconsumer_namespace=default secret_name=harry-apikey secret_namespace=default
```

from [decodeCredential](https://github.com/Kong/kubernetes-ingress-controller/blob/8fa3b190ec80115d4d11cab44ef56b65d22e1c77/internal/dataplane/kongstate/credentials.go#L224-L240).

### Expected Behavior

The field is parsed as or coerced to an int, and the credential is created.

### Steps To Reproduce

```markdown
Unverified, but fairly confident:

1. Create a KongConsumer.
2. Create a credential Secret with `kongCredType=key-auth` `key=whatever`, and `ttl=1000`
```

### Kong Ingress Controller version

_No response_

### Kubernetes version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

parse `ttl` field of kong key-auth credentials to `int` type to fix error of invalid type when filling the `ttl` in secret to Kong credential.

**Which issue this PR fixes**:

fixes #2734 
**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/dataplane/kongstate/kongstate.go [hunk 1]
```diff
@@ -100,6 +100,17 @@ func (ks *KongState) FillConsumersAndCredentials(log logrus.FieldLogger, s store
 					}
 					continue
 				}
+				// TODO: ttl is a field that only appears in keyAuth credentials and has int type.
```
Comment (pmalek) [inline internal/dataplane/kongstate/kongstate.go:103]: Do we have something to do here? If so let's state it explicitly, otherwise let's drop the `TODO` or change to to `NOTE`. I'd suggest to make it a plain comment, without any "tag" in the beginning though.

Comment (randmonkey) [reply internal/dataplane/kongstate/kongstate.go]: removed the `TODO`.

**Review by pmalek — APPROVED** [review]
