### PR TITLE
fix: only check if condition contained in ensuring gateway associated of httproute

### LINKED ISSUE #3345: Duplicate update of HTTPRoute status makes code unreachable
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating an `HTTPRoute`, The log `httproute has been configured on the data-plane` will not appear after it sent to dataplane client. This means the code after calling `r.ensureGatewayReferenceStatusAdded` is unreachable:

https://github.com/Kong/kubernetes-ingress-controller/blob/ef97785c0234927d9b2b6b2cc00c08b48a29f18e/internal/controllers/gateway/httproute_controller.go#L378

### Expected Behavior

log `httproute has been configured on the data-plane` is printed after an HTTPRoute is sent to dataplane client.

### Steps To Reproduce

```markdown
1. Create an HTTPRoute object
2. check logs of ingress controller
```

### Kong Ingress Controller version

```shell
latest version of main
```

### Kubernetes version

```shell
1.24
```

### Anything else?

The bug is possibly brought when we add https://github.com/Kong/kubernetes-ingress-controller/pull/2737. Here we added the setting of `ResolvedRefs` in `status.conditions` of HTTPRoute, but the method of checking whether status should be changed is not updated. It still compare the whole conditions of `parentStatus` and the generated `parentStatus`. If more condition are added, the comparing part will always treat it as changed, and the status of HTTPRoute is always updated.

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

Now more than one conditions are added to HTTPRoute.status.parentStatus[*], so we need to change the method to check if parent status for gateways changed. Instead of making a full comparison of conditions, we check if the existing parentStatus contains the expected condtion.

**Which issue this PR fixes**:

fixes #3345

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/controllers/gateway/httproute_controller.go [hunk 1]
```diff
@@ -435,13 +435,10 @@ func (r *HTTPRouteReconciler) ensureGatewayReferenceStatusAdded(ctx context.Cont
...
-			for i := range existingGatewayParentStatus.Conditions {
-				existingGatewayParentStatus.Conditions[i].LastTransitionTime = gatewayParentStatus.Conditions[0].LastTransitionTime
-			}
-
-			// other than the condition timestamps, check if the statuses are equal
-			if reflect.DeepEqual(existingGatewayParentStatus, gatewayParentStatus) {
+			//  check if the parentRef and controllerName are equal, and expected condition presents in conditions
+			if reflect.DeepEqual(existingGatewayParentStatus.ParentRef, gatewayParentStatus.ParentRef) &&
+				existingGatewayParentStatus.ControllerName == gatewayParentStatus.ControllerName &&
+				containsCondition(existingGatewayParentStatus.Conditions, gatewayParentStatus.Conditions[0]) {
```
Comment (pmalek) [inline internal/controllers/gateway/httproute_controller.go:441]: You might consider using https://github.com/samber/lo#containsby. We already import and use this package throughout the codebase.

File: internal/controllers/gateway/httproute_controller.go [hunk 2]
```diff
@@ -435,13 +435,10 @@ func (r *HTTPRouteReconciler) ensureGatewayReferenceStatusAdded(ctx context.Cont
...
 		// then just leave it alone.
 		if existingGatewayParentStatus, exists := parentStatuses[key]; exists {
-			// fake the time of the existing status as this wont be equal
-			for i := range existingGatewayParentStatus.Conditions {
-				existingGatewayParentStatus.Conditions[i].LastTransitionTime = gatewayParentStatus.Conditions[0].LastTransitionTime
-			}
-
-			// other than the condition timestamps, check if the statuses are equal
-			if reflect.DeepEqual(existingGatewayParentStatus, gatewayParentStatus) {
+			//  check if the parentRef and controllerName are equal, and expected condition presents in conditions
```
Comment (pmalek) [inline internal/controllers/gateway/httproute_controller.go:438]:
```suggestion
			//  check if the parentRef and controllerName are equal and whether the new condition is present in existing conditions
```

**Review by pmalek — COMMENTED** [review]
Nice find, some nits but overall 👍

File: internal/controllers/gateway/httproute_controller.go (hunk 1 above)
Comment (randmonkey) [reply internal/controllers/gateway/httproute_controller.go]: changed to `lo.ContainsBy`.

File: internal/controllers/gateway/route_utils.go [hunk 3]
```diff
@@ -630,3 +630,12 @@ func isHTTPReferenceGranted(grantSpec gatewayv1alpha2.ReferenceGrantSpec, backen
 	}
 	return false
 }
+
+// sameCondition returns true if the condition has the same type, status, reason and message
+// with expectedCondition in conditions.
+func sameCondition(expectedCondition metav1.Condition, condition metav1.Condition) bool {
```
Comment (pmalek) [inline internal/controllers/gateway/route_utils.go:636]: It'd idiomatic in Go to just call the params `a` and `b` or something else but at this level of conciseness

```suggestion
func sameCondition(a, b metav1.Condition) bool {
```

**Review by pmalek — COMMENTED** [review]
I wonder if this shouldn't actually get its own changelog entry. Do you mind adding it @randmonkey ?

File: internal/controllers/gateway/route_utils.go (hunk 3 above)
Comment (randmonkey) [reply internal/controllers/gateway/route_utils.go]: updated.

**Comment by randmonkey** [comment]
> I wonder if this shouldn't actually get its own changelog entry. Do you mind adding it @randmonkey ?

Added changelogs.

**Review by pmalek — APPROVED** [review]

**Comment by pmalek** [comment]
Created https://github.com/Kong/kubernetes-testing-framework/issues/489 to cover the failure in tests

> Error: tests failed: failed to deploy addon kong: Error: INSTALLATION FAILED: Service "ingress-controller-kong-admin" is invalid: spec.ports[0].nodePort: Invalid value: 32080: provided port is already allocated

oh, what a chance
